### ISSUE TITLE
ADMIN - WF1 CASE STATUS Updates Needed

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#1024]
SNAP E&T staff reported issues using this script. This script hasn't had an update in over 4 years, so it basically needs a rewrite. Things to resolve in the rewrite: 
- [x] Out of county handling seems buggy
- [x] Add newer functions
- [x] Add functionality for finding a member that isn't MEMB 01

**Comment by C-Love** [comment]
This script no longer supports list items in which there is no case number listed. This used to be supported and is not supported with recent updates.
