### ISSUE TITLE
Discovery and Planning on a supportive Claim Referral Tracking Process that supports Fed and State Requirements

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#1025]
The current Claim Referral Tracking process is a workaround solution to a system gap that exists. It currently uses panels that do not provide good tracking or reporting.

We need to review the available technology and systems to create comprehensive tracking and work continuation on possible claims. This discovery will likely involve other departments in ES, DHS and possibly FNS in determining the best solution to answer the needs of claim tracking and follow up.

This may not be a script solution, but if a script can be supportive of the process, we can develop that after the process is determined.

**Comment by IlseFerris** [comment]
Here's the question of the minute: Can we get a table?

**Comment by courtrightd** [comment]
We will create a new issue in the future if there is movement on this. Won't fix for now.
