### ISSUE TITLE
Housing Support Rate 2 Closure in MMIS

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#103]
Housing Support/GRH workers have requested a script that will close SSR's in MMIS if the case is closing/resident has moved. 

Companion script to ACTIONS - ADD GRH RATE 2 TO MMIS. Action script to close out the SSR agreement in MMIS. Script would do the following steps:

Ensure the SSRT panel is closed if the resident left the facility.
Ensure that the elig results are correct for SSR cases
Navigate to MMIS
Calculate the new SSR units
Update the dates
Case note in MAXIS

**Comment by IlseFerris** [comment]
Duplicate of #136

**Comment by courtrightd** [comment]
Seems demand for this does not outweigh the effort. Won't fix.
