### ISSUE TITLE
Make Appointment Notice and NOMI's into functions and update affected scripts with function

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#1036]
We have these in a few places so it makes sense to make as functions. Functions will handle for both applications and renewals. Available space in spec/memo can be tricky and something to keep in mind.

Create Function
- [x] Create application functions for Appoint & NOMI (ADMIN- INd-NOMI, IND-recertification)
- [x] Create recertification functions for Appoint & NOMI (ADMIN- Review Report 2521 & 3348)

Update Affected Scripts

- [x] Admin- On Demand Waiver Applications
- [x] Admin- Review Report
- [x] Notes- Application Received

**Comment by IlseFerris** [comment]
Moving back to On Deck to add functions into affected scripts.

**Comment by MeganGeissler** [comment]
Pushed to master today.

**Comment by MeganGeissler** [comment]
Nothing broke, good to go!
