### ISSUE TITLE
Make function for office info/digital experience options for MEMO's/WCOM's

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#1037]
We have this all over the place, and it's subject to change with the continued development of these tools. Make into functions to only need to update the one place. Available space in spec/memo can be tricky and something to keep in mind.

See connected issue #1036 and  #1458

Digital Experience: 
      	CALL write_variable_in_SPEC_MEMO("*** Options for Submitting Documents ***")
	CALL write_variable_in_SPEC_MEMO("- Upload documents to case with infokeep.hennepin.us.")
	CALL write_variable_in_SPEC_MEMO("- You can submit documents online at MNBenefits.mn.gov.")
	CALL write_variable_in_SPEC_MEMO("- Mail, Fax, or Drop Boxes at service centers.")

**Comment by MeganGeissler** [comment]
Nothing broke, good to go!
