### ISSUE TITLE
OneSource and MMIS manual: add universal password into fields

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#104]
Scripts would need to be stored on the network drives due to keeping passwords secure. 
Potential script steps include: opening IE, navigating to the websites, and entering the user name/passwords. 

Research needed to see if ID's of fields are known on the websites.

**Comment by C-Love** [comment]
This requires updating the power pad. Connected to issue #113.

**Comment by C-Love** [comment]
Boo - IE11 does not allow for VBscript Automation. 

This might have to be in Javascript.

**Comment by C-Love** [comment]
We need to ask ITRM for help.

**Comment by C-Love** [comment]
Conversation with Holly today. We may need to move away from IE. I will be working with IT, possibly a developer about creating signed code and using ActiveX or some other possible functionality.

**Comment by C-Love** [comment]
New plan - I will do discovery - if I can resolve it by 1/7/22, we will update this in Q1 2022. If the solution is not found by 1/7/22, we will tag this as an issue to be resolved upon conversion.

**Comment by C-Love** [comment]
This is no longer possible in VBScript. We will review this code when we convert to Python.
