### ISSUE TITLE
ADMIN - MAIN MENU: Default script set based on user role/supervisor ID

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#1070]
The ADMIN main menu defaults to opening the ADMIN script set for all users even though most of the ADMIN menu users use ofther script sets. QI team usually uses the QI script set, and same for BZ and OS/SSR's for MONTHLY TASKS. 

To create a better user experience, and reduce a mouse-click for users we will update the ADMIN - MAIN MENU to read information from the COMPLETE LIST OF SCRIPTS to default script set to specific user group.

**Comment by C-Love** [comment]
We might have a new data table to help with this. We also may want a OS specific area for the scripts run by OS staff.

**Comment by C-Love** [comment]
QI workers would default to 'QI'. 'ES-S' workers would default to Report Tasks. 'BZ' workers would default to 'BZ'. Everyone else stays on main ADMIN.

Change 'Monthly Tasks' to 'Report Tasks'

**Comment by C-Love** [comment]
ADMIN Menu functionality updated and working.
