### ISSUE TITLE
UTILITIES-VA VERIFICATION

### ISSUE THREAD

**Issue by MiKaylaH22** [Hennepin-County/MAXIS-scripts#108]
MiKayla - Gather case information to put in the function 

Thought for this. Build the case number gathering at the very beginning of the script, outside of the function created for the main functionality. 

Build the function assuming that you already have the case number because in other uses you will AND it makes it easier to create dropdowns with case specific information.

Just my thoughts to help. Let me know if I can help you in any way.
---
Good morning,

I work in EWS and I have a question about requesting verifications. What information is needed when an eligibility worker/HSR requests verification of VA type and income? My team and I are looking into ways to support our department, and knowing what information is needed ahead of time is really beneficial. 

Thank you, and have a great day!
HI Ilse,

If the verification is for a Veteran the VA requires:

•	Name of Veteran (1st & last) and SSN;

If the verification is for a Spouse or child of the Veteran the VA requires:

1)	Name of Veteran (1st & last) and SSN;
2)	Name of Spouse or child, relationship to the Veteran, and SSN;
3)	If possible the VA file # (gives the VA a better search capability).  The number will appear on VA correspondence usually in the upper right corner (see attached for a redacted example).  If a surviving spouse an “XC” will sometimes appear in the beginning of the file#.  Also, if its an older claim you may see a “C” in the beginning of the file#.
Feel free to contact me if you have questions.

Thanks

Chad Huseby

**Comment by C-Love** [comment]
I'm confused about this. Are we talking about a separate individual script for when the information needed to verify is VA? Or a function to get specific details?

I'm struggling with where this fits holistically. Maybe we need to have a larger conversation about verification handling in general.

**Comment by MiKaylaH22** [comment]
Initial commit

**Comment by MiKaylaH22** [comment]
Updated and completed
