### ISSUE TITLE
New Script Idea: Significant Change Evaluator

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#1089]
From user A. Wallace: 
I wanted to bring some ideas to the attention to the appropriate team. I’ve noticed the significant change script might need some revamping in order to correctly and appropriately approve significant changes. Are there any ways we can add some things to the Script?

Example:
1.            What was THE BUDGETED INCOME IN BUDGET MONTH 
2.            WHAT IS THE REPORTED INCOME IN REQUEST MONTH
3.            IS THE REPORTED INCOME IN THE REQUEST MONTH AT LEAST 50% OR LESS?
4.            WAS THE ANTICIPATED/REPORTED INCOME VERIFIED?

I’VE NOTICED WITH PROCESSING MANY OF THESE AND REVIEWING  A LOT OF THEM THERE ARE VERY IMPORTANT QUESTIONS WE HSR’S ARE MISSING. THERE ARE SOME CASES WHERE THE RESIDENT STATES THEY WERE NOT TOLD ABOUT THEIR ANTICIPATED INCOME, STATES THAT IS NOT WHAT THEY WERE TOLD TO REPORT.

**Comment by courtrightd** [comment]
Six month budgeting takes effect in March 2025, making this obsolete. Won't fix.
