### ISSUE TITLE
Add team emails to FuncLib

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#110]
One of our project goals is to improve service delivery and communication within ES and HHS (department and larger department). Adding team emails to the FuncLib to have call into our scripts is part of that support.

**Comment by C-Love** [comment]
We need to create a processes for knowing about changes to the BASKETS.

**Comment by IlseFerris** [comment]
This issue will be on hold until the team emails project is being finalized.

**Comment by C-Love** [comment]
Given the agency direction with assigning work, team emails are not going to be used as they have been in the past and do not need to be available.
