### ISSUE TITLE
NOTES - MFIP TO SNAP TRANSITION worker comment required

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#111]
Per the [CM 0005.09.06](https://www.dhs.state.mn.us/main/idcplg?IdcService=GET_DYNAMIC_CONVERSION&RevisionSelectionMethod=LatestReleased&dDocName=CM_00050906) - When Not To Require Completion of an Application, when cases switch from MFIP to SNAP "Indicate in the notice for the participant to contact the county only if he/she wishes to decline SNAP." 

POLI TEMP TE02.08.143 - does not give advise on adding a worker comment or giving suggestions on what to write. Will pose this question with DHS.

**Comment by IlseFerris** [comment]
Sent question to SNAP-PAC.QA@state.mn.us on 08/11/2020.

**Comment by IlseFerris** [comment]
Sent question again to SNAP-PAC.QA@state.mn.us on 11/19/2020.

**Comment by C-Love** [comment]
Check two scripts:

1. Add WCOM 
2. MFIP to SNAP Transition

**Comment by IlseFerris** [comment]
Closing as won't fix. DHS has not provided verbiage to date. Is being tracked offline for updates to #123 ELIG SUMMARY, and is already (although not amazing) in NOTICES - ADD WCOM.
