### ISSUE TITLE
ELIGIBILITY SUMMARY - Add WREG Exemption Check Functionality 

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#1112]
When an approval for SNAP is complete, we need to review WREG and double check for possible exemptions if coded as an ABAWD. This will be part of the review and could also lead to case review selection.

This functionality is in FuncLib and is currently in a DAIL Scrubber.

**Comment by courtrightd** [comment]
Won't fix this issue - we will look at providing wreg guidance in other scripts and updating Elig Summary for comprehensive review selection in the future.
