### ISSUE TITLE
Find and Replace in all scripts 'ECF' in Case Note Verbiage

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#1139]
We shouldn't use a county specific system name in CASE NOTE. Find 'ECF' and replace with 'Case File' or something similar.

**Comment by IlseFerris** [comment]
Scripts that require updates in application resident/state outputs (CASE/NOTE, SPEC/MEMO, etc.):
- [ ] ADMIN - CS GOOD CAUSE
- [ ] DAIL - CATCH ALL
- [ ] DAIL - INCARCERATION
- [ ] DAIL - MEDI CHECK
- [ ] DAIL - NEW HIRE
- [ ] DAIL - NEW HIRE NDNH
- [ ] DEU - BULK MATCH CLEARED
- [ ] DEU - MATCH CLEARED
- [ ] DEU - OVERPAYMNET CLAIM ENTERED
- [ ] IV-E - IVE ADOPTION ASSISTANCE
- [ ] IV-E - MA NEEDY CHILD
- [ ] NOTES - APPEALS
- [ ] NOTES - APPLICATION CHECK
- [ ] NOTES - APPLICATION RECEIVED
- [ ] NOTES - AVS
- [ ] NOTES - CHANGE REPORTED
- [ ] NOTES - DOCUMENTS RECEIVED
- [ ] NOTES - HEALTH CARE TRANSITION
- [ ] NOTES - IMIG STATUS
- [ ] NOTES - RETURNED MAIL
- [ ] NOTES - SMRT
- [ ] SHELTER - SHELTER CHANGE REPORTED

**Comment by IlseFerris** [comment]
No issues reported. Closing issue.
