### ISSUE TITLE
OUT OF STATE INQUIRY

### ISSUE THREAD

**Issue by MiKaylaH22** [Hennepin-County/MAXIS-scripts#114]
Adding the National Directory to the script to create an email and case note.

**Comment by MiKaylaH22** [comment]
Add the ECF checkbox to dialog to ensure workers are sending verification request

**Comment by MiKaylaH22** [comment]
PARIS matches will have a very specific process that is expedited with the changes to this script

**Comment by C-Love** [comment]
This is a duplicate issue for #86 - will close this issue and work off of the #86 issue.
