### ISSUE TITLE
Create FIATer with CASE/NOTE for SNAP Homeless Shelter Deduction

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#1141]
New policy clarification and procedure to correctly budget a deduction for SNAP for households that are reported as homeless with a housing expense as there is a minimum deduction for shelter expenses that is not correctly determined in ELIG. 

This issue will address:
- [ ] Review unapproved ELIG/FS results and STAT panels to determine if FIAT is needed
- [ ] FIAT functionality to update ELIG/FS if the deduction is incorrect
- [ ] CASE/NOTE details of determination of Shelter Expense for SNAP cases coded as homeless regardless of if ELIG had to be FIATed or not
- [ ] Updates to Eligibility Summary to review ELIG and stop if an incorrect shelter deduction exists
- [ ] Updates to Eligibility Summary to create CASE/NOTE about details of Shelter Expense for SNAP if missing AND if no FIAT was needed.

Additional details, logic map, and policy reference will be added as we have them.

**Comment by IlseFerris** [comment]
Closing as a won't fix. #123 has a task to support identifying these cases, but the plan above is no longer valid due to the small scope of impact.
