### ISSUE TITLE
Review password handling in all BULK scripts

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#1156]
There are some bugs with how the password handling is working in many BULK scripts. We need to review this functionality and update.

**Comment by IlseFerris** [comment]
Reviewed all BULK scripts. The following scripts require password handling in the dialogs (missing): 
- [ ] ADMIN - COPY CASE DATA FOR TRAINING
- [ ] ADMIN - MEMO FROM LIST
- [ ] ADMIN - ON DEMAND DASHBOARD
- [ ] ADMIN - RESOLVE HC EOMC in MMIS
- [ ] BULK - CASE NOTE FROM LIST
- [ ] BULK - CASE TRANSFER
- [ ] BULK - FSS INFO (might retire this)
- [ ] BULK - HEALTH CARE BUDGET REPORT
- [ ] REPT - EOMC LIST
- [ ] REPT - INAC LIST
- [ ] REPT - MFCM LIST
- [ ] REPT - PND1 LIST
- [ ] REPT - INTR LIST (has no dialog at all, will be adding)
