### ISSUE TITLE
NOTES - OVERPAYMENT: Create collectable/non collectable indicators

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#1161]
Request from tester AR: 

> I just completed a non-collectible claim (overpayment) for a case.
> There is no option on the Overpayment case note to select collectible or non-collectible.
> This may be a good enhancement as it needs to be very clear for the next worker so they don’t accidentally tell the resident they have an overpayment.
> I had to put it in manually on the case note.
> The resident does not receive an overpayment notice for non-collectible claims, only for collectible claims.

This is a great idea. Will add collectable/non collectable indicator to the claims.

**Comment by C-Love** [comment]
This appears to be working just fine.
