### ISSUE TITLE
Audit check_for_MAXIS in the project and align with Dialog1 conventions 

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#1166]
The check_for_MAXIS function has a different dialog name than the standard Dialog1. We would like to get this function aligned. First we need to audit the whole project to ensure that check_for_MAXIS is not inside any dialog loops (because this would cause the deletion of dialog definition for that loop). 

Make sure that all the calls for this function are outside of dialog loops.
Once these are done, update the function to use Dialog1 as the dialog name.

**Comment by courtrightd** [comment]
Scripts to fix for this:

- BILS updater: complete
- NOTES - Vendor, currently testing solutions
- NOTICES - LTC Asset Transfer, currently testing solutions
- LTC - Intake Approval: Will be retired with #1517 
- LTC - COLA Summary: Retired
- LTC - MA Approval: Retired

**Comment by courtrightd** [comment]
Notes - Vendor had other problems, moved to its own issue. 
All scripts effected are now updated and ready for testing, or on deck for retirement.
This issue is resolved when #1549 and #1233 are completed.
