### ISSUE TITLE
NOTES - Interview needs a check_for_MAXIS after dialogs once function dialog is updated

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#1168]
The check_for_MAXIS updates being completed in Issue #1166 will allow check_for_MAXIS to be added to NOTES - Interview after the dialogs to be sure we are still in the MAXIS system as the script continues.

**Comment by IlseFerris** [comment]
Work on this after #1166 is completed.

**Comment by C-Love** [comment]
This appears resolved with no isuses.
