### ISSUE TITLE
NOTES-APPEAL

### ISSUE THREAD

**Issue by MiKaylaH22** [Hennepin-County/MAXIS-scripts#117]
Multiple issues

**Comment by MiKaylaH22** [comment]
Sent a project request form requesting more information about the appeal process

**Comment by MiKaylaH22** [comment]
There are 4 existing scripts: Appeal Summary Completed, Appeal Hearing Info, Appeal Decision received, and Appeal Resolution.
Appeal Summary Completed: Add “Other” selection box
Appeal Hearing Info: Add “Docket#”; Don’t make anticipated decision date a mandatory section
Appeal Decision Received: Add “Docket#”
Appeal Resolution: Add “Confirmed Resolution/Withdraw with Appellant Y/N”; “Referred Appellant to DHS Apppeals (651-431-3600) Y/N:” “Notified Hennepin EWS of Withdraw Y/N”; Leave section to write what action was taken to resolve/withdraw appeal.

**Comment by MiKaylaH22** [comment]
Request policy references

**Comment by MiKaylaH22** [comment]
review can take place, in ECF, CASE/NOTE, or SPEC/MEMO
make a script to print case notes from this date to this date
create an option for "Appeal process need additional verification to resolve pending" - TIKL

**Comment by MiKaylaH22** [comment]
Updated script after speaking with Jonathan may have more enhancements in the future will wait until more documentation is completed.

**Comment by MiKaylaH22** [comment]
Reevaluate - "other" on the checkbox and using droplist for Y/N answer
take a look at the ADH hearing list

**Comment by IlseFerris** [comment]
[State Agency Appeals Summary](https://edocs.dhs.state.mn.us/lfserver/Public/DHS-0035-ENG) on Edocs. Notes on appeal summary completed option: 
1. There are some additional programs listed here that we should account for. 
2. There is also an OTHER line with a field so adding an other programs field to note the other program. 
3. Docket # - This isn't established at the time the appeal summary is completed. Remove option.

**Comment by MiKaylaH22** [comment]
Discussion- what to do when next steps come in possibility of sequential steps reading case notes.
Creating separate dialogs for each step.

**Comment by MiKaylaH22** [comment]
1)Appeal received add to drop list 
2) add transportation burial assistance revenue recapture emergency  sanction checkboxes to programs
3) other is for "didnt like the verbiage used in the document"
4) Update to confirm entry mandatory why benefits are continuing

**Comment by IlseFerris** [comment]
Final updates before pull:
- Check/Add Dialog1 = "" to all dialogs
- Add YES/NO drop list, remove checkboxes from 'Resolution' dialog

**Comment by MiKaylaH22** [comment]
Nothing received from users
