### ISSUE TITLE
Task Based Assistor -Automate review process of TB Assignments

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#118]
Laurie is working on a project where she is reviewing the work completed during task based assignments. This in in conjunction with Faughn and Mark. 

She has a spreadsheet with cases and worker names for a specific date. She needs to gather:
- How many DAILS are on the case
- The CASE NOTE header of the notes created by that worker for that specific date
- Items in ECF 

She then needs to do some review/assessment of these items. In particular if the note is from a BZ Script or not. We may want to offer some suggestions on other criteria for assessing the quality of the CASE NOTE Header.

**Comment by C-Love** [comment]
We are asking Faughn and Mark about some of this. 

We might do this but we need more information and background and support as well.

**Comment by IlseFerris** [comment]
I met with Faughn today. I'll be setting up a meeting between our team, Mark and Abdimalik to talk out the entire process. I think this one will be an all team consult based on our skill sets.

**Comment by IlseFerris** [comment]
Reopening issue. More feedback came in from project team. Make the following updates:
- [ ] Move comments to column N from O. DAIL TYPE was COL K, but that was removed. 
- [ ] Add Boolean value to COL I output "Does Case Note Title Contain a Keyword?"
