### ISSUE TITLE
Case Assignment - Application Received add SHIBA to drop down 

### ISSUE THREAD

**Issue by MiKaylaH22** [Hennepin-County/MAXIS-scripts#119]
Securely Hosted Integrated Benefits Application added as an option for how app recvd

**Comment by MiKaylaH22** [comment]
Updated with #176

**Comment by C-Love** [comment]
Change the droplist option to have ApplyMN and SHIBA as seperate options.

**Comment by MiKaylaH22** [comment]
Checking with  CA staff about SHIBA confirmation number

**Comment by MiKaylaH22** [comment]
Remove the SHIB/APPLY/MN

**Comment by C-Love** [comment]
This is all done and working
