### ISSUE TITLE
DAY THIRTY Work assignment - Might be mostly families

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#120]
Jacob suggested that many of these DAY THIRTY cases are families.

This would need more discovery. 

We may want to add counts to the Work Assignment Completed script OR add functionality to the EXP SNAP Assignment Creation script to identify adults vs families cases. This might inform future assignments or functionality.

There are process decisions still being made on this and we do not have any active development to do yet.

**Comment by IlseFerris** [comment]
Closing issue. This will be a non-issue soon as we are moving into task-based processing.
