### ISSUE TITLE
Add all scripts to COMPLETE LIST OF SCRIPTS

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#1207]
Not all the scripts are in the COMPLETE LIST OF SCRIPTS (that's right....). Specialty groups NOT in the ADMIN menu are currently excluded which means they don't have dynamic dialogs or access to script instructions with the ? button. This also means that we have redirect files in some of these specialty menus, and that handling could be added to the script files themselves.
 This issue will enhance the CLoS to include the following groups: 
- [ ] CA - Case Assignment
- [ ] DEU - Debt Establishment Unit
- [ ] IV-E
- [ ] MMIS - Managed Care
- [ ] SHELTER

**Comment by C-Love** [comment]
All scripts are now included and nothing broke.
