### ISSUE TITLE
Create Closing Project Documentation

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#122]
To ensure a consistent experience for our users, will be creating closing project documentation for documenting steps taken when completing a script project. 

@IlseFerris has started this, @MiKaylaH22 is going to take this over.

**Comment by MiKaylaH22** [comment]
Cancel confirmation in each loop
Dialog1
Err_msg handling
Passworded out
Change Log
Script end procedure

Gather script details/ideas/process
Create script map and output
Confirm actions with sponsor
Write script
Comment script
Identify testers
Write Instructions
Scriptwriter testing
HSR testing
Hot Topic
Release

**Comment by IlseFerris** [comment]
Template finalized and ready to use. Closing issue.
