### ISSUE TITLE
NOTES - OVERPAYMENT: Ensure claim #'s are numeric

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#1222]
LB, BZS user, reported an issue where the script did not create the claim note, and this was due to them not entering the claim # into the claim # field(s), but person information. Add handling in do...loop to ensure that claim #'s are all numeric before moving past the main dialog.

**Comment by MeganGeissler** [comment]
No issues reported, closing issue.
