### ISSUE TITLE
Update 200% FPG NOTES - EMERGENCY 

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#1224]
Changes effective 04/01/23 from [CM0016.18.01](https://www.dhs.state.mn.us/main/idcplg?IdcService=GET_DYNAMIC_CONVERSION&RevisionSelectionMethod=LatestReleased&dDocName=CM_00161801)

**Comment by IlseFerris** [comment]
For the EGA screening functionality within NOTES - EMERGENCY using the correct FPG is determined by the date of application. 

EGA uses last year’s FPG to determine if it meets NET income limits based on the policy in CM0016.18.01 [200 PERCENT OF FEDERAL POVERTY GUIDELINES (state.mn.us)](https://www.dhs.state.mn.us/main/idcplg?IdcService=GET_DYNAMIC_CONVERSION&RevisionSelectionMethod=LatestReleased&dDocName=CM_00161801). This is updated every 04/2023, following cash-program rules.

This update will include having a date of application read on PROG (or a place to enter the date if not found), and use the correct FPG based on the date. 

Will also remove HH member count to 4 max - this is only used for EGA, and currently supports 20 HH members. 

Waiting for updates to SPO prior to updating issues.

**Comment by C-Love** [comment]
FPG amounts updated to align with current year.
