### ISSUE TITLE
Update Redirect files with New Teammates ID's

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#1225]
We have special handling in all of our redirect files to make sure that the 'Scripted Desktop' or Local, dev environement of BZ uses ONLY the local files, including Global Variables, Func Lib, menus, and script files. 

We hard code the windows user ids here and we need to update for our current team complement.

**Comment by C-Love** [comment]
Disregard NAV scripts for now.

**Comment by C-Love** [comment]
Additional Issue #1273 to handle some incorrect redirect functionality.

**Comment by MeganGeissler** [comment]
Done and working!
