### ISSUE TITLE
Function determine_program_and_case_status_from_CASE_CURR: REIN status has dates

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#1228]
CAF testing/script low down shows GRH date is cut off. Review and update outputs.

**Comment by C-Love** [comment]
This is actually an issue with ALL programs on REIN. The MM/YY is listed next to the REIN status. We need to reset that status to exclude the MM YY from the prog_status variable.

**Comment by C-Love** [comment]
This appears to be functioning - AND we didn't break the function or the func lib.
