### ISSUE TITLE
Create Eligibility Summary Script

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#123]
Needs a script that combines Approved Programs, Denied Programs, Closed Programs. 

This should include more detail about HOW the budget was determined. 

This may be an 'APPROVER' script.

Once this is done we need to change NOTES - HRF to Processing HRF Form or something along those lines because the APPROVAL of a HRF will be noted with Eligibility Summary. 

We will also need to remove NOTES - DWP Budget because this information will be in Eligibility Summary

**Comment by C-Love** [comment]
Look very strongly at making this an APPROVER.

**Comment by C-Love** [comment]
Moving this to LATE Q4 - possibly Q1 depending on other projects.

**Comment by C-Love** [comment]
Include information about screening for MA EPD when DENYING for HC

**Comment by C-Love** [comment]
Include note specifics about MA EPD Med B manual reimbursement requests and determinations. This should enter in CNote and PNote.

**Comment by C-Love** [comment]
SEND MEMO to Clt at APP with  Reporting Detail based on the APP

**Comment by C-Love** [comment]
Make sure to include any cash Opt Outs and read PACT for that relevant information in determining the budget to case note.

**Comment by C-Love** [comment]
Add review of TE 02.05.108 - Denying/Closing SNAP for No Income Verification

This outlines that the PIC must be $0 income when denying or closing for no verification. This creates a correct notice to the resident about why we are denying. We need Eligibility Summary to check the PIC about income when denying or closing snap to make sure we have coded things correctly.

**Comment by C-Love** [comment]
Check SNAP cases for CCAP and ensure cat elig/DCEX is correct. https://hennepin.sharepoint.com/teams/hs-economic-supports-hub/SitePages/Episode-43.aspx

**Comment by C-Love** [comment]
Include GRH/HS specific handling.

**Comment by IlseFerris** [comment]
Support for aligning non-HC programs to renew together. Identify 24 month certification SNAP folks.

**Comment by C-Love** [comment]
Check ACCT and CASH to ensure assets are counted for SNAP.

**Comment by IlseFerris** [comment]
Consideration for SNAP - Setting TIKLs or reminders automatically for anyone that is a 24 month reporter.

**Comment by IlseFerris** [comment]
Another consideration for SNAP - MA-EPD premium/spenddown/waiver obligation/Medicare costs as FMED deductions.

**Comment by C-Love** [comment]
Include MFIP Special DIET MONY/CHCK approval.
https://hennepin.sharepoint.com/teams/hs-es-manual/SitePages/Budgeting_Special_Diet.aspx 
https://hennepin.sharepoint.com/teams/hs-es-manual/SitePages/Processing_Special_Diet_Referral.aspx

**Comment by C-Love** [comment]
Once core functionality is done, review all WCOMs #740 to determine if any of them need to be Core Functionality of Elig Summ. Any that are not core functionality should have issues created to incorporate them into Elig Summ.

**Comment by C-Love** [comment]
Core functionality is completed is completed and Approved, Closed, and Denied programs are retired.

There is some ongoing work/enhancements to make in the next few months:
#1783 
#1884 
#1885

**Comment by C-Love** [comment]
ELIGIBILITY SUMMARY IS DONE!!!! Core functionality completed.
