### ISSUE TITLE
NOTES - LTC Asset Transfer Penalty: Update to reflect current project standards

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#1232]
Q2 is the quarter of health care, so let's do some housekeeping on this script. This one hasn't been touched hardly at all in the past 10 years, and could use some updates. Updates to include: 
- [x] Add in functions for validating MAXIS Case number and MAXIS footer month/year
- [x] Determine if math is needed, and if so add math or 'calculate' button- Not needed
- [x] Replaced spaces with __ to handle for date read/write into dialog
- [x] Added comments to code and removed unnecessary coding
- [x] Update err msg based on dialog edits
- [x] Closing issue documentation.
- [x] Add policies and procedures to Complete list of scripts.
- [x] Update script documentation

Dialog: 
- [x] Removed transfer type, added "uncompensated transfer" to case note, and field to describe transfer items
- [x] Replaced check boxes with drop down for waiver, added notes field to correlate
- [x] Added N/A as an option for waiver drop down
- [x] Adding policy buttons vs. having policy written out in the dialog- Added policy buttons
- [x] Added IsDate to and Trim to err_msg do loop for dialog
- [x] Tab order

**Comment by MeganGeissler** [comment]
Complete list of scripts updated. Scripts works.
