### ISSUE TITLE
LTC Approval-Based Scripts to Retire/Update w/ Eligibilty Summary Core Functionality Release

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#1233]
With core functionality for health care programs completed and tested, let's look at retiring/updating elig based scripts for Health Care. These will include:
- [x] DAIL - COLA Review and Approve
- [x] NOTES - LTC - COLA Summary
- [x] NOTES - LTC - Intake Approval
- [x] NOTES - LTC - MA Approval

**Comment by C-Love** [comment]
Evaluation of these scripts indicates we should do the following:

1. Update DAIL - COLA Review and Approve to be more of a COLA income summary to document the income information. #1518 
2. Remove all 3 LTC scripts
3. LTC Intake Approval has some functionality that should be a part of HC Evaluation and will need to be supported before the script can be removed #1517 

None of these scripts will have support to document approvals directly any longer. This also supports the work in #1166 as these scripts have some weird check_for_MAXIS calls - but they won't be a problem once the scripts are gone.

**Comment by C-Love** [comment]
This is done, these have been retired.
