### ISSUE TITLE
NOTES - MAIN MENU: Update to include IMIG into regular alpha structure

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#1234]
Currently we have 2 separate buttons for LTC and IMIG based scripts in the NOTES - MAIN MENU. With several scripts being incorporated into single script functionality and upcoming retirements, it's time to update these. Tasks will include: 
- [ ] Updating the Complete List of scripts
- [ ] Reviewing/updated the automated functionality that creates the buttons. 
- [ ] Update instructions on SharePoint so ?'s still work in the NOTES - MAIN MENU dialog. 
- [ ] Create changelog communicating change to staff.

**Comment by IlseFerris** [comment]
This issue will be worked on at the same time as #1218.

**Comment by courtrightd** [comment]
Updated instructions file names for both scripts, help buttons now function, closing issue.
