### ISSUE TITLE
HCRE_panel_bypass function clean up

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#1238]
#1237 will be adding in the function to the Funclib, this issue will address removing the code/local function, and adding in the new functions call. Script to update are: 
- [x] ACTIONS - ADD GRH RATE 2 TO MMIS
- [x] ADMIN - CLOSE MMIS RATE 2 IN MMIS
- [x] ADMIN - INDIVIDUAL RECERTIFICATION NOTICES
- [x] ADMIN - ODR STATS ONLY
- [x] ADMIN - ON DEMAND NOTES
- [x] NOTES - CAF 
- [x] NOTES - ELIGIBILITY SUMMARY
- [x] NOTES - HEALTH CARE EVALUATION
- [x] NOTES - INTERVIEW
- [x] UTILITIES - QI AVS REQUEST
- [x] TEST - Ilse- Restart Scripts - BULK - Restart IMIG
- [x] TEST - Ilse- Find AFFLIATED MMIS Case Info

Retired scripts and desert island script files are out-of-scope for this update.

**Comment by MeganGeissler** [comment]
Removed local functionality. Casey added funct in the library which it will reference instead. All went well!
