### ISSUE TITLE
Audit ADMIN - RESOLVE HC EOMC IN MMIS

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#1243]
This script hasn't been used since the PHE started. Audit script to review for enhancements and updated capitation rates.

**Comment by IlseFerris** [comment]
PPHP Capitation date for June is 06/23/2023. Man Care Enrollment Cutoff 06/21/2023.

**Comment by C-Love** [comment]
This appears to be working
