### ISSUE TITLE
NOTICES - LTC ASSET TRANSFER: Update to meet project standards

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#1258]
Q2 is the quarter of health care, so let's do some housekeeping on this script. This one hasn't been touched hardly at all in the past 10 years, and could use some updates. Updates to include:
- [x]  Add in functions for validating MAXIS Case number and MAXIS footer month/year
- [x] Dialog: Remove check box & logic for case/note, make it automatic. 
- [x] Stat: Added 1 to the stat counter since case/note occurs every time the script is run. 
- [x] Dialog: Add policy buttons to onesource and EPM on dialog.  
- [x] Dialog: Add functionality to autofill footer month/year, client, spouse.
- [x] Dialog: Added functionality to handle for blank footer month/year.
- [x] Dialog: Reorganize dialog tab order.
- [x] Script End: Minimal revision.
- [x]  Closing issue documentation. 
- [x]  Complete list of scripts: add policies and procedures.

**Comment by MeganGeissler** [comment]
Working well.
