### ISSUE TITLE
Don't Forget the Period of Confusion - ER version

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#126]
MAXIS don't do all the things - cases that REIN after cutoff be problematic.

We don't have a solution - we just know there needs to be a solution. 

This is here so we never forget.

**Comment by MiKaylaH22** [comment]
HSR brought a case that had missed appt letter due to being xferrered from county on 18th of the month

**Comment by C-Love** [comment]
This is actually Issue #42
