### ISSUE TITLE
NOTES - EMERGENCY: Adding user experience handling

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#1263]
There's a big gap in user experience handling now that we're looking at the date of application for the 200% FPG. See issue #1224. Adding in month handling, stronger mandatory field handling, etc. 
Only adding in life saving measures, and closing issue documentation on this issue. Will look a rewrite or merger in the future.

**Comment by C-Love** [comment]
Updates complete - no issues reported.
