### ISSUE TITLE
Workflows - Can we do this thing?

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#127]
This is future state.

BOWIE
![image](https://user-images.githubusercontent.com/13418322/88483981-ebd1da80-cf30-11ea-858c-a64efd6f5fab.png)

**Comment by C-Love** [comment]
NOTE - there is a variable in the script_end_procedure functions - disable_StopScript  - that will prevent the script from ending after stopscript and will allow for daisy chaining. There is no notification or messaging changes or details. This has not been tested in a production environment - but by script writers alone.

**Comment by IlseFerris** [comment]
Closing as a won't fix. Workflow and user experience are in our daily work, and workflows tied to databases are listed in their own issues.
