### ISSUE TITLE
Remove BZST specific redirects from MMIS Manual and OneSource Manual redirects

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#1273]
These scripts are maintained only on the TDrive at this time as they are planned to be enhanced with PW handling.

- [x] Removed C drive and GitHub redirect, replaced with TDrive location for all users (did not add any PW handling at this time).

**Comment by MeganGeissler** [comment]
@C-Love - I'm looking for a little more context on this issue when you have time, thanks!

**Comment by MeganGeissler** [comment]
Works well. Closing.
