### ISSUE TITLE
NOTICES - PA Verif Request - remove person specific direction for Public Housing Form and direct users to HSR Manual

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#1275]
The HSR manual has been updated to direct workers to complete PA Verification Forms themselves instead of sending them to individual workers. We are going to align this script.

Additionally, we might need to update the selection verbiage to make it not specific to Public Housing.

**Comment by IlseFerris** [comment]
Knowledge Coordinator OK'd the change. Closing issue.
