### ISSUE TITLE
Update Complete List of Scripts with Known Policies/Procedures for DHS Processes

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#1283]
There is a list of 'scripts to support DHS requirements' that I recently pulled off of SharePoint since we've moved these supports into the Complete List of Scripts (CLoS). These should be added since we already did the research on them.

**Comment by IlseFerris** [comment]
Since this issue is a clean up issue, I'm also going to add the NOTES - OVERPAYMENT policies/procedures in (with an array since there are SO many of them), and add recent Hot Topic links as well.

**Comment by C-Love** [comment]
CLOS did not break. Closing.
