### ISSUE TITLE
NOTES - AVS: TIKL update

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#1284]
QI Member YY sent the following request: When an AVS submission casenote is ran, a TIKL is automatically set for 10 day out but is there a way to set the TIKL for the 11 day instead? 
We will make this update. Policy/procedural reference to come.

**Comment by C-Love** [comment]
NOTE - in reviewing the functionality, I recommend we leave the CASE/NOTE to say '10 day check' as that is how it is referenced in OneSource. The TIKL is moved to 11 days to allow for return of information but the NOTE still references the 10. @IlseFerris - any concerns?

**Comment by IlseFerris** [comment]
Nope, it makes sense to me. I don't want to confuse staff.

**Comment by IlseFerris** [comment]
No issues reported. Closing issue.
