### ISSUE TITLE
Ex Parte- BULK script- TPQY: Read, update, case note  

### ISSUE THREAD

**Issue by MeganGeissler** [Hennepin-County/MAXIS-scripts#1305]
For Ex Parte, we need to create script to support and automate the handling of ex parte as much as possible. This portion will be a bulk script that will read, write and case note TPQY information. 
- [ ] Read all panels of TPQY for each person
- [ ] Write claim numbers and income from TPQY into MAXIS (UNEA & MEDI)
- [ ] Case note TPQY info

**Comment by C-Love** [comment]
Initial functionality for this work is completed
