### ISSUE TITLE
Ex Parte - Phase 1 - Display, Verify, and CASE NOTE Ex Parte Information

### ISSUE THREAD

**Issue by MDR22** [Hennepin-County/MAXIS-scripts#1307]
- [x] Display known ex parte and case information
- [x] Add navigation and policy/instructions buttons to display
- [x] Check, update, and recheck the REVW HC ER month and year to match the determination
- [x] Create CASE NOTE of the ex parte phase 1 determination
- [x] Create data connections for variables to SQL table

**Comment by C-Love** [comment]
This is done and is working in the current functionality for phase 1.
