### ISSUE TITLE
Ex Parte UC Information Updater

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#1309]
For Ex Parte process if RAP project exists for UC information, and updater will be needed to upload the UC information into UNEA panels and case note the information provided.

**Comment by IlseFerris** [comment]
De-prioritizing this issue due to the small number of recipients that are on UC for HC cases post PHE.

**Comment by C-Love** [comment]
Initial functionality for this work is completed.
