### ISSUE TITLE
Scripts for Fraud/FPIs 

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#131]
There are number of processes and tools the fraud workers or other workers could use.

**Comment by C-Love** [comment]
https://hennepin.sharepoint.com/teams/hs-economic-supports-hub/SitePages/Updated-fraud-referral-process.aspx

**Comment by IlseFerris** [comment]
Closing as won't fix. Will continue to work with ES Workflow and QI teams to support fraud and FPI.
