### ISSUE TITLE
Ex Parte create BULK Script Report to act on the Ex Parte list through each Phase

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#1311]
This BULK report will run off the cases listed on the SQL table to take any BULK actions or evaluations and reduce workload on HSRs in completing the Ex Parte tasks. This BULK list is the method for maintaining access to the list and status of the Ex Parte list/cases. 

This work is to create the structure for the BULK report and will incorporate functionality created in other issues:
#1305 
#1306 
#1308
#1309

This issue will resolve:
- [x] Creating a selection dialog to choose one of the three BULK runs we have (Prep, Phase 1, Phase 2) NOTE: additional runs/functionality may be determined as the process is documented and clarified.
- [x] Creating an array from the data table to use within the script operation.
- [x] Ensure each case is run through background for Phase 1 and Phase 2 runs.
- [ ] Read Elig results and Budget details for Phase 1 and Phase 2 runs.
- [ ] Read MMIS open spans for Phase 1 runs.
- [x] Incorporate send TPQY functionality built in Ilse's Test file for BULK SSI/RSDI Updater for Prep run.

**Comment by IlseFerris** [comment]
Add BUDG support in Prep run. 
Add Ex Parte Phase 1 cases that end up on REPT/REVS.

**Comment by C-Love** [comment]
The BULK script is created an it has the following functionality:

- Selection of BULK run option
- Prep phase to evaluate cases for potential Ex Parte, send a QURY, and create a list of UNEA verifications
- Prep 2 phase to read the first TPQY and send a second QURY if a new claim number is indicated.
- Phase 1 to update the final TPQY and incorporate the other UNEA verifications.
- Phase 2 run to update BUGD to align with the renewal month
- ADMIN Review to track the progress of the cases

This BULK run facilitates the Ex Parte review, case tracking, any automation, and ES Workflow assignments.

This work will be followed up in:
#1382 
#1384
