### ISSUE TITLE
Script to request a BULK run from an OS Worker

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#132]
![image](https://user-images.githubusercontent.com/13418322/88483912-85e55300-cf30-11ea-98d0-175f5dd33eb5.png)

**Comment by MiKaylaH22** [comment]
Lets take a look at standardizing the way we set up the REPT headers/BULK lists

**Comment by C-Love** [comment]
We know there is a need to review our ad-hoc reports and output of reports. We do not need to change/update this at this time.
