### ISSUE TITLE
MMIS Service Authorization Automation for Waivers, PCA and AC

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#134]
Financial Case Aides on the Service Authorization team in Contract Management Services (CMS) are responsible for entering screenings and service authorizations for waivered services and personal care assistance in the Medicaid Management Information System (MMIS). Many of the tasks completed in MMIS are repetitive, and seem to be potential candidates for the development of a BlueZone script. CMS is currently exploring how BlueZone script could be used to make these MMIS tasks more efficient.

CMS would like to request that EWS develop a BlueZone script for entering service authorizations in MMIS and assist with developing of a Power Pad so that the Service Authorization team can test the script in MMIS. CMS will coordinate the testing of this script with staff on the Service Authorization team. Then, two Senior Planning Analysts on CMS’ Waiver Finance team, Abdiweli Ali and Kathryn Diaz, will review the script developed by EWS to develop additional BlueZone scripts to support the work of the Service Authorization team.

How: EWS will review existing procedures for entering service authorization in MMIS, as well as consult with the Service Authorization team, in order to develop a preliminary BlueZone script for entering service authorizations in MMIS. 

What: EWS will develop a preliminary BlueZone script for entering service authorizations in MMIS, and will also assist with developing a Power Pad so that the Service Authorization team can test the script in MMIS. 

### A prioritized list of specific and measurable deliverables:
•	A BlueZone script for entering service authorizations in MMIS
•	Development of a Power Pad for use in MMIS with BlueZone script

### Processes to Develop Automation For:

1. New waiver input
2. Renewals
3. Changes to service agreements
4. COLA (low priority) - twice a year: AC/EW only and then all waivers)

**Comment by C-Love** [comment]
Are there other scripts or functionality we would add to an MMIS specific power pad? 

I am thinking about MHC scripts because we are still trying to decide what to do with the specialty groups as we redesign our structure and power pad.

**Comment by IlseFerris** [comment]
Moving to main project for Q2 2021.

**Comment by IlseFerris** [comment]
Closing issue as a won't fix. DHS is planning to use BlueZone scripts to pass data between the new MNCHOICES 2.0 application and MMIS. This reduces the need for this automation.
