### ISSUE TITLE
EDRS scripts: Add checking ALIA for SSN's

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#1348]
Request from AGK, HSR: I don't think the EDRS part of the script does not check the ALIA panel for SSNs to run. It is common for them to appear there when there is a duplicate PMI.

Checking the ALIA panel isn’t in the instructions provided in the policy at CM0025.24.08 [SNAP ELECTRONIC DISQUALIFIED RECIPIENT SYSTEM (state.mn.us)](https://www.dhs.state.mn.us/main/idcplg?IdcService=GET_DYNAMIC_CONVERSION&RevisionSelectionMethod=LatestReleased&dDocName=CM_00252408) or in the procedure at [TE 02.08.127 SNAP EDRS.docx (sharepoint.com)](https://hennepin.sharepoint.com/:w:/r/sites/hs-es-poli-temp/_layouts/15/Doc.aspx?sourcedoc=%7BA44F0F9C-65AE-4E12-8D2A-DAF9B5E327CB%7D&file=TE%2002.08.127%20SNAP%20EDRS.docx&action=default&mobileredirect=true&DefaultItemOpen=1&cid=4427e4c4-5143-415c-b100-56ef336f0dbe), but since duplicate PMI's are a known issue we should be doing more discovery around when this would happen and when we should review the ALIA-based SSN instead. 

Other considerations: May be time to make EDRS a function since it's a stand-alone script and functionality is also in the interview script. Maybe also add to the CAF during the interview waivers?

**Comment by courtrightd** [comment]
Due to this not being required by policy, we do not have capacity. Won't fix.
