### ISSUE TITLE
Update StaffHeirarchyDim to include HSR not in ES

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#1361]
HSRs that are organizationaly not in in ES (most likely in Well Being) and not included on our view of the Staff table. 

We need to connect with BI on how to resolve this.

**Comment by IlseFerris** [comment]
DaNM - Email from Matt on BI team.

**Comment by C-Love** [comment]
This looks amazing and is working. We can now work on #1034 to access staff info from the table directly.
