### ISSUE TITLE
Updated IMIG to clearly case note what the status is when selecting 50 Lawfully Residing

### ISSUE THREAD

**Issue by MiKaylaH22** [Hennepin-County/MAXIS-scripts#137]
DACA - August CM 11.03.24 Updating to include DACA as other lawfully residing effective 08/01/2020. They ARE eligible for state-funded CASH benefits. IMIG should be coded as 50. MAXIS will create inelig results for children under 18. FIAT will be required. POLI TEMP requested by Hennepin County MAXIS Mentors

**Comment by C-Love** [comment]
Waiting for POLI TEMP to support this policy/direction.

**Comment by IlseFerris** [comment]
At the current MAXIS Mentor meeting on 08/26/2020, it was announced that a POLI TEMP will be created to address all code 50 residents. This issue will wait until that is published.

**Comment by IlseFerris** [comment]
Close as won't fix. Will reopen if POLI TEMP instructions are provided by DHS.
