### ISSUE TITLE
IV-E Script Updates

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#1376]
7 scripts need updating and new one created for Adoption Assistance, IVE, MA Needy Child, and Trial Home Visit. 
Project request submitted by HSS, BS. Saved request in LAN drive. 

Scripts to Update:

- [x] Trial Home Visit
- [x] Adoption Assistance
- [x] IVE
- [x] Elig Review
- [x] MA Needy Child
- [x] Northstar Kinship - New Script

**Comment by C-Love** [comment]
Discussed with IVE Team - test for 2 weeks unless issues or changes are needed.

**Comment by C-Love** [comment]
Script changes confirmed by the team, completed.
