### ISSUE TITLE
ACTIONS - MA FIATer for MSA/GRH - Assess inclusion of other Approved Programs

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#1403]
The current functionality for the script ACTIONS - MA FIATer for MSA/GRH does not FIAT in any income from the PA program that is approved on the case (such as MSA, GRH, GA). The requirement here is unclear and we need resolution of if this is needed. 

JA will be meeting with SH, RZ, YY this Thursday (7/13/23) and will discuss this to have an answer around this issue. Once information is received, we can take next steps in the script.

**Comment by C-Love** [comment]
Clarification - the script SOMETIMES does this thing and sometimes does not.

**Comment by IlseFerris** [comment]
DANM - Any updates from the QI crew on this?

**Comment by C-Love** [comment]
Updates from QI.

The policy this supports is in OneSource: https://www.dhs.state.mn.us/main/idcplg?IdcService=GET_DYNAMIC_CONVERSION&RevisionSelectionMethod=LatestReleased&dDocName=ONESOURCE-170112 

This policy has some inefficiencies in how the process is explained, specifically that it does not clarify explicitly that this should be operated on X Budgets. It is a logical inference that this fiater is to support the changing of Method X to Method B, however, since the process is a little fuzzy around that detail, we should updated this script to be clear that it is intended to FIAT a Method X budget to Method B budget. Workers can then use this script to support that action for this process, but the script is not intended to necessarily support every possible update needed for this process. 

We can have the script reference this in a button but I suggest we change the name of this script to be specific about the actions it will be taking. 

Secondly, some of the feedback that we have received is that the MSA/GRH benefit has not been FIATed into the HC budget. JA has found this for us:
Per [EPM 2.3.3.3.2.3 – MA-ABD Excluded Income](https://hcopub.dhs.state.mn.us/epm/2_3_3_3_2_3.htm), the following income is excluded: Public assistance payments from the following programs: Housing Support (HS) and Minnesota Supplemental Aid (MSA).

We should cite this and make sure it is clear the script does not add these amounts to the budget (even if they do end up being excluded, this is not something we do in HC). 

An additional note in the discovery on this issue, RZ and JA have found that completing this FIAT does not typically change eligibility for HC and is a heavily error prone and manual process without benefit to the resident and perhaps we should push this back on DHS as something we cannot accommodate with accuracy.
