### ISSUE TITLE
Update function Create_Outlook_Email Clean Up

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#1409]
Associated with issue #540. Will need to add new parameters that were added to the function to the files they are called in. The function is called in the following scripts: 

- [x] FUNCLIB: function create_outlook_email
- [x] ACTIONS - JOB CHNAGE REPORTED
- [x] ADMIN - DELETE DAIL TASKS
- [x] ADMIN - EXPEDITED DETERMINATION REPORT
- [x] ADMIN - MONT REPORT
- [x] ADMIN - ON DEMAND DASHBOARD
- [x] ADMIN - ON DEMAND WAIVER APPLICATIONS
- [x] ADMIN - REVIEW REPORT
- [x] ADMIN - TASK BASED DAIL CAPTURE
- [x] ADMIN - WORK ASSIGNMENT COMPLETED
- [x] ADMIN - WORK ASSIGNMENT FROM EXCEL
- [x] CASE ASSIGNMENT - MIPPA
- [x] DEU - ADH INFO AND HEARING
- [x] DEU - MATCH CLEARED
- [x] DEU PARIS MATCH CC CLAIM ENTERED
- [x] FUNCLIB: function select_testing_file
- [x] FUNCLIB: function script_end_procedure_with_error_report
- [x] MISC - DESERT ISLAND
- [x] MISC - TAGS MAIN MENU
- [x] NOTES - APPLICATION RECEIVED
- [x] NOTES - CAF
- [x] NOTES - CSR TESTING
- [x] NOTES - EXPEDITED DETERMINATION
- [x] NOTES - IMIG STATUS
- [x] NOTES - INTERVIEW
- [x] NOTES - METS RETRO HEALTH CARE
- [x] #1427
- [x] NOTES - SUBSEQUENT APPLICATION
- [x] TEST SCRIPTS/ILSE/TEMP FILES FOR DHS/HSS MAXIS FACILITY REPORT
- [x] TEST SCRIPTS/ILSE/TEMP FILES FOR DHS/HSS SERVICE AUTHORIZATION UPDATE
- [x] UTILITIES - APPLICATION INQUIRY
- [x] UTILITIES - CONTACT KNOWLEDGE NOW
- [x] UTILITIES - QI AVS REQUEST
- [x] UTILITIES - REPORT TO THE BZST
- [x] UTILITIES - REQUEST ACCESS TO PRIV CASE
- [x] UTILITIES - UC VERIFICATION REQUEST
- [x] UTILITIES - VA VERIFICATION REQUEST
- [x] SCRIPT FILES (T DRIVE) - COMPLETE LIST OF TESTERS
- [x] SCRIPT FILES - REDIRECT NAV CASE CURR
- [x] SCRIPT FILES - REDIRECT NAV CASE NOTE
- [x] SCRIPT FILES - REDIRECT NAV FIND MAXIS CASE IN MMIS
- [x] SCRIPT FILES - REDIRECT NAV FIND MMIS PMI IN MAXIS
- [x] SCRIPT FILES - REDIRECT NAV MMIS GRH
- [x] SCRIPT FILES - REDIRECT NAV PERS
- [x] SCRIPT FILES - REDIRECT NAV POLI TEMP
- [x] SCRIPT FILES - REDIRECT NAV STAT ADDR
- [x] SCRIPT FILES - REDIRECT NAV STAT MEMB

The following desert island scripts will need to be updated locally once the updates have been pulled into MASTER:
- [x] NOTES - APPLICATION RECEIVED
- [x] NOTES - CAF
- [x] DESERT ISLAND MENU
- [x] NOTES - EXPEDITED DETERMINATION
- [x] NOTES - INTERVIEW
- [x] FUNCLIB

**Comment by IlseFerris** [comment]
Good morning @MDR22, local Desert Island files have been updated so you're good to go to update our other local files.

**Comment by MDR22** [comment]
I updated the local script files with the updated function. Should be fully implemented now.
