### ISSUE TITLE
Update to NOTES - Case Discrepancy to have a unique header

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#1424]
Request came in to update this script to make a CASE/NOTE header that is more descriptive of the discrepancy being handled. This would increase readability of the CASE/NOTE list.

This could be a ComboBox that allows for some common discrepancy details. We would need to review the usage and look at the cases for some common discrepancies. Pulled YTD (Jan-Oct) of Case Discrepancy and reviewed 33% of the data: 
 https://hennepin-my.sharepoint.com/:x:/g/personal/casey_love_hennepin_us/EWBiqxc6njNGujqsJfIV0eEBTa_dJb9aFOpQMRM8A5It2Q?email=Megan.Geissler%40hennepin.us&e=4%3Astz1cc&fromShare=true&CID=2FA84517-F607-493E-A87C-6C8956CC153E&wdLOR=cB70669BD-DF85-4596-97D1-B7F60E90F11C

**Common Discrepancies:** 
-Select or Type...
-Household Error
-Incorrect Approval
-Incorrect Panel Information
-Insufficient Documents/ Missing Verifications
-MAXIS/MMIS Discrepancy
-Policy Change

This script might also need a bit of clean up and project alignment work.

**Comment by MeganGeissler** [comment]
Updated script with discrepancy options listed above, error handling, case noting and general script formatting.
