### ISSUE TITLE
NOTES - MAIN MENU: Update to include LTC into regular alpha structure

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#1446]
Currently we have 2 separate buttons for LTC and IMIG based scripts in the NOTES - MAIN MENU, See #1234. With several scripts being incorporated into single script functionality and upcoming retirements, it's time to update these. Tasks will include:

- [x]  Updating the Complete List of scripts
- [x]  Reviewing/updated the automated functionality that creates the buttons. No action required.
- [x]  Update instructions on SharePoint so ?'s still work in the NOTES - MAIN MENU dialog.
- [x]  Create changelog communicating change to staff.

**Comment by MeganGeissler** [comment]
Removed LTC button from Notes Main Menu
Updated ChangeLog to notify users of this change. 
No action required for CLOS or ? for sharepoint.
