### ISSUE TITLE
Digital Drop Box is Sundowning

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#1447]
I just met with SF, our IT business partner, and the digital drop box is sundowning at the end of the year. The only active script that has this reference is ADMIN - INDIVIDUAL RECERTIFICATION NOTICES. 

- [x] Remove verbiage that points to digital dropbox (hhsews@hennepin.us) and replace with verbiage in screenshot of Appointment Notices in Review Report/Application Received.
- [x] Verify it is using English and not another language. Verified that 'English' is hard coded into the script.

**Comment by C-Love** [comment]
This is completed.
