### ISSUE TITLE
NOTES - HEALTH CARE TRANSITION enhancement for no IC #

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#1449]
METS worker requested to fix script to allow a 10-digit person record vs. having to enter an 8-digit IC (Integrated Case) METS case number. This doesn't happen often, but can happen if someone doesn't have a basis of elig in the METS system (over 65 & on Medicare, etc.). 

Update script to enter either a METS case number OR a person record number. 
May need drop down to select case number or person record number. Need check to make sure they entered the correct number of digits for the respective numbers.

**Comment by MeganGeissler** [comment]
No issues reported. Closing.
