### ISSUE TITLE
Exp Det functionality - SNAP Applications page has been depreciated - replace

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#1469]
The SNAP Applications page has been depreciated and there is only an Applications page (https://hennepin.sharepoint.com/teams/hs-es-manual/SitePages/Applications.aspx).

There is a resource button in all of the places where Expedited Determination functionality exists.

Need to change the button text to remove 'SNAP' and change the URL to open when the button is pressed.  

Needs to be updated:

- [x] - NOTES - CAF (button: 4890, 5103: HSR Manual - SNAP Applications, 5245: hsr_snap_applications_btn)
- [x] - NOTES - Interview (button: 2964, 3333: HSR Manual - SNAP Applications, 3472: hsr_snap_applications_btn, 
- [x] - NOTES - Expedited Determination (button: 1376, 2245: HSR Manual - SNAP Applications, 2375: hsr_snap_applications_btn)

Steps: 
- [x]  Changing button name from "HSR Manual - SNAP Applications" to "HSR Manual - Applications"
- [x] Changing button var from "hsr_snap_applications_btn" to "hsr_applications_btn"
- [x] Changing link from https://hennepin.sharepoint.com/teams/hs-es-manual/SitePages/SNAP_Applications.aspx to https://hennepin.sharepoint.com/teams/hs-es-manual/SitePages/Applications.aspx
- [x] Update Instructions: Exp Determination and Interview complete. CAF didn't have anything pertinent listed.

**Comment by MeganGeissler** [comment]
good to go
