### ISSUE TITLE
Replacing Stolen EBT Food

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#1473]
New procedures in POLI TEMP have been added effective 09/2023 for how an eligibility worker would support a request for replacing stolen EBT food benefits. 

The procedure is detailed and fussy and would benefit from automation and script guidance through the process. What happens if eligibility staff don't fully complete each step of the process, a back and forth via SIR email occurs, which could result in residents getting degrade or no customer service. 

This functionality could be merged with NOTES - DISASTER FOOD REPLACEMENT to create a comprehensive SNAP replacement support. 

Refer to the following POLI TEMP references: 
- TE.02.11.18 Food Destroyed in a Misfortune or Disaster
- TE02.11.127 Replacing Stolen EBT Food - Client Requests
- TE02.11.126 Replacing Stolen EBT Food - Client Notified
-

**Comment by MDR22** [comment]
Megan and I reviewed each of the POLI TEMP references and the current NOTES - DISASTER FOOD REPLACEMENT script.  Identified opportunities to combine processes into a single script due to overlap in process steps. I plan to work on further planning out and developing script later in November. Background materials and files saved here: T:\Eligibility Support\Restricted\QI - Quality Improvement\BZ scripts project\Projects\Unclear Information

**Comment by MDR22** [comment]
Reviewed proposed approach to issue. Plan to create a script that incorporates the Food Destroyed in Disaster script into a script with the Food Benefits Stolen process. Will include options to document steps in process to allow for multiple workers to work through request - same as current Food Destroyed script. Inquired with DHS regarding lack of SPEC/MEMO direction for Food Destroyed in Disaster in POLI/TEMP, will update script based on direction received.

**Comment by MDR22** [comment]
RE

> Reviewed proposed approach to issue. Plan to create a script that incorporates the Food Destroyed in Disaster script into a script with the Food Benefits Stolen process. Will include options to document steps in process to allow for multiple workers to work through request - same as current Food Destroyed script. Inquired with DHS regarding lack of SPEC/MEMO direction for Food Destroyed in Disaster in POLI/TEMP, will update script based on direction received.

Received response from DHS. SNAP policy currently working on updates to Food Destroyed in Misfortune/Disaster (TE02.11.18) that will include information about sending notices. DHS noted that MAXIS will send notices when denial reasons are provided (TE02.11.07) but this may be outside the scope of current script.

**Comment by IlseFerris** [comment]
@MDR22 and @MeganGeissler, check out [SIR announcement dated 12/21/2023](https://www.dhssir.cty.dhs.state.mn.us/MAXIS/Lists/MAXIS%20Announcements/DispForm.aspx?ID=8225&RootFolder=%2FMAXIS%2FLists%2FMAXIS%20Announcements&Source=https%3A%2F%2Fwww%2Edhssir%2Ecty%2Edhs%2Estate%2Emn%2Eus%2FPages%2FDefault%2Easpx). There's some updates listed in that communication.

**Comment by MDR22** [comment]
Reviewed the [SIR announcement dated 12/21/2023](https://www.dhssir.cty.dhs.state.mn.us/MAXIS/Lists/MAXIS%20Announcements/DispForm.aspx?ID=8225&RootFolder=%2FMAXIS%2FLists%2FMAXIS%20Announcements&Source=https%3A%2F%2Fwww%2Edhssir%2Ecty%2Edhs%2Estate%2Emn%2Eus%2FPages%2FDefault%2Easpx). DHS has created a new webform to request replacement of stolen food benefits. This appears to be separate from previous TSS BENE request webform. DHS has not yet released updated POLI/TEMP guidance for the use of this webform. 

I updated the script to better align with the updated POLI/TEMP directions for Food Destroyed in a Misfortune or Disaster (TE02.11.18). However, as noted previously, DHS is currently working on updates to this to provide clearer instructions on sending notices after making a decision on the request.

**Comment by MDR22** [comment]
Updated EBT STOLEN BENEFITS - CLIENT NOTIFICATION - POLI/TEMP: TE02.11.126 includes additional reasons for replacement request denials. Will need to add additional options to denials for SPEC/MEMO.
