### ISSUE TITLE
Review Interview script and update DropListBoxes to ComboBoxes where it makes sense

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#1539]
If a person is not in MAXIS before the interview script is started, they won't be in the list of options in any droplistbox. We can change these to ComboBoxes to allow for manual entry of people that are reported in the interview or aren't in MAXIS for whatever reason.

**Comment by IlseFerris** [comment]
This should be worked on at the same time as #560 so this will also travel to another quarter.

**Comment by MeganGeissler** [comment]
INTV/CAF 1: who are we completing the interview with - COMBO
CAF MEMBs: Add Person uses new_clt and sets selected_memb = new_clt to determine new count for array and to store info 
Q7-11: Principal wage earner - DROP BOX
CAF QUAL Q: Qualifying questions HH member - COMBO
CAF Last Page: Signatures of primary/other - COMBO

I think we are covered w/ combo boxes at this point.
