### ISSUE TITLE
Create function Determine_200_of_FPG

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#1541]
Much like function Determine_130_of_FPG, let's us a function vs. updating this every year. The function will need include support for EA and EGA, as well as any other program that would use this determination. 

Additionally the NOTES - EMER and NOTES - ELIG SUMMARY scripts would need to be updated to replace the current functionality with the function.

**Comment by MDR22** [comment]
See function determine_130_percent_of_FPG(footer_month, footer_year, hh_size, fpg_130_percent). Information for EA/EGA can be found in NOTES - ELIG SUMMARY starting at Line 15790. Information on 200% FPG can be found in [Combined Manual](https://www.dhs.state.mn.us/main/idcplg?IdcService=GET_DYNAMIC_CONVERSION&RevisionSelectionMethod=LatestReleased&dDocName=CM_001906)
