### ISSUE TITLE
Update Exp Det Report to Email Spot Check Team if run late

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#1545]
The Expedited Spot Checks process has a bit of an issue if the Exp Det Report is run too late in the day. The power app script has a set run time. 

If the script is run late and the report update is after the process time, we should have this script send an email if the report saving happens after a set time to request the process be rerun.

Things to follow up on:

- Determine what time the process is automated.
- Confirm who should receive the email.

This should help support the Expedited Spot Checks work and SNAP timeliness.

**Comment by IlseFerris** [comment]
Closing as a won't fix. When this project comes back it will need to have data stored in a database vs temp data storage and management.
