### ISSUE TITLE
Browsers are a thing we need to address

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#158]
We currently have two ways to open a web page:
1. Just a 'open_url' 
2. Open a specific application then navigate to a specific URL

We may need to change the project to remove all of the application specific code to make the movement non-browser specific. 

IE might be going away and that is the application we usually open. 

We are also looking into some specific functionality that interacts more directly with a webpage but this is a larger functionality issue and question and may feed back directly to this issue. See Issue #104

**Comment by C-Love** [comment]
There is code in the favorites script to open a URL in Edge specifically.

**Comment by C-Love** [comment]
UPDATE

The new Interview script uses code to open in Edge instead of IE so we can update to open in Edge specifically.

Scripts to Update:
- [ ] NOTES - CSR 
- [ ] NOTES - HC Renewal
- [ ] NOTES - METS Retro Health Care
- [ ] NOTES - HC Transition
- [ ] ACTIONS - Transfer Case

**Comment by IlseFerris** [comment]
No issues reported. Closing issue.
