### ISSUE TITLE
NOTES - IMMIGRATION STATUS 

### ISSUE THREAD

**Issue by MiKaylaH22** [Hennepin-County/MAXIS-scripts#164]
User reported that the email address was incorrect, verified email address as HP.Immigration

**Comment by C-Love** [comment]
This does not need to be fixed - the email is correct.

**Comment by IlseFerris** [comment]
Cheryl K reported a "message could not be delivered" message when using the 'send email to HP Immigration' option. Reopening issue, and I will add some stability to the email functionality by creating variables for the strings of information outside of the email function.
