### ISSUE TITLE
Record Script Usage outside of Script End Procedure function

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#1650]
Currently, the only way we have to record if a script is run is if we get to the end of a script run and the SQL INSERT to the dbo usage log is triggered. There is no reason we can't enter records outside of the script_end_procedure and this would be made easier with a new function meant to record script usage. 

First, we are going to create this function and test it in the updates to the DAIL scrubber with COLA Review and Approve. 

Once we confirm that this works on it's own, we can change both script_end_procedure functionalities to call this function to be sure it works to in this instance as well. 

We will have to make sure the reporting doesn't change with this new functionality.

**Comment by C-Love** [comment]
Testing seems complete on this, no issues reported and the functionality is in play in Client Contact. 

Leaving this in discuss at next meeting to review the functionality naming conventions and structure of recording the parts of functionality. Need a plan to make this cohesive.

**Comment by C-Love** [comment]
DaNM - this functionality generally works but our naming and verbiage conventions are not created. Do we want to close this issue since the functionality is done? Or should we spend a little time finishing these conventions?

**Comment by MeganGeissler** [comment]
> DaNM - this functionality generally works but our naming and verbiage conventions are not created. Do we want to close this issue since the functionality is done? Or should we spend a little time finishing these conventions?

The only insight I've received from the PowerBI team regarding where dbos.usage.log file is that it is used as the underlying data file for the data sources: HsScriptFact and HsScriptDim which are the tables they use to build our power bi graphics. 

Beyond that, we don't have much insight into where else this data file is being used and how changing the naming conventions would impact other areas. Considering this, we could wrap this up by deciding on a naming convention for function/incremental script measurements and provide these categories to Ernie so he can incorporate it into our powerbi dashboard. Thoughts and hashing out naming format and wrapping this up?

**Comment by MeganGeissler** [comment]
Spoke with ME- You cannot see from the underlying data source (such as dbos.usage.log) where it is being used. You have to work backwards from a dashboard. Processing dashboard, activity report, and BZ report are the sources ME is aware of that use dbos.usage.log. 

If we add something at the beginning of our naming convention such as "FUNCTION" this would be easy for them to exclude or group in a different way in order to display it in say our BZ report graphics, however tacking additional words onto the end (DAIL -COLA REVEIW AND APROVE - COLA SUMMARY NOTE CREATED) would be trickier to handle for.

**Comment by C-Love** [comment]
Documentation created on this process and is available in OneNote. Function has been created and tested - ready for use.
