### ISSUE TITLE
Reported issues with accessing the MHC menu

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#1663]
Unclear if this is an issue in the code of the menu or somewhere else in the line of functionality. 

Discovery and testing to be completed.

**Comment by C-Love** [comment]
No additional reports, this might have actually been due to VPN issues that were happening at the same time.

**Comment by MDR22** [comment]
Received new report of dialog issues with DEU - MAIN Menu script so reopening issue. Also, will activate links to DEU script instructions.
