### ISSUE TITLE
NOTES - HRF Remove eligibility details

### ISSUE THREAD

**Issue by MeganGeissler** [Hennepin-County/MAXIS-scripts#1682]
User reported that approval amounts were not pulling through correctly to case notes on case #836273. Notes: MFIP was approved with significant change, but the approved amounts don't show in the HRF case note, I manually put them in.

Found that the script was pulling the unapproved version through to the case note ($0.00) instead of the approved version. This happens because the HRF script is not built to handle for unapproved layered over an approved version. Based on this finding, we will be revising the HRF to remove the eligibility portion and direct users to ELIG SUMM.

**Comment by C-Love** [comment]
Remove all Eligibility details from the HRF script as eligibility details is supported by Eligibility Summary.
