### ISSUE TITLE
Add appointment notice function to NOTES - SUBSEQUENT APPLICATION

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#1691]
The `create_appointment_letter_notice_application` function needs to be added to the NOTES - SUBSEQUENT APPLICATION script to complete our work on centralizing our notice information. #1685 is associated, and will also be using the functions vs. the office information being hard coded into the scripts.

**Comment by C-Love** [comment]
This appears to be working.
