### ISSUE TITLE
On Demand Recertification Script make the actions in line with the review

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#171]
Right now there are two loops - first to reseerach, then to take action - we gonna make them all in one loop to save time and make resuming better. 

Also change the name so the script buttons work.

**Comment by C-Love** [comment]
The script now does each case to completion one at a time. Tested with STATs, NOMIs, and APT NOTC.

**Comment by IlseFerris** [comment]
let's chat about the NOMI run for 11/20 recerts. When starting from a row that wasn't 2 the script gives the option to use existing data, but the drop lists don't contain the columns to select. It's just a blank drop list.
