### ISSUE TITLE
Expedited SNAP with SPON requires FIAT

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#173]
Maybe we make a fiater?

**Comment by IlseFerris** [comment]
MAXIS Help Desk provided a process to ensure that the case will auto-close correctly due to postponed verification(s). Will be sending a PQ to get the process in writing. Casey is checking with Mandora to see if we have a pending PQ for this issue on 08/20/2020.

**Comment by IlseFerris** [comment]
Duplicate of #208
