### ISSUE TITLE
Pending Caseload Clean Up Project

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#1737]
ES is taking on a clean up effort to finalize pending baskets to wrap up the Work Structure project initiative of de-regionalizing caseloads. To date, there is not documentation on how/when to transfer cases inner county, or which criteria to use to determine which population cases belong. Resolving these unknowns is in scope for the project, and may be subject to change at a later date (the process, not the need for those directives). 

Directive: In a nutshell, pending baskets/case loads will become regular caseloads, and we will use Case Assignments 'as is' process to move cases to population caseloads vs. population PENDING caseloads, which would then need to be transferred again once the case was no longer pending. Exceptions to the CA 'as is' process: 
- How to determine which population the case belongs in will be enhanced. 
- Cases previously had secondary criteria to determine which caseload they would go to (based on how the application was received). That is no longer necessary. 
- Automated supports will be built to randomize the correct basket once the population was been determined or selected. 
- Supports for cases that do not require transfers.

**Comment by C-Love** [comment]
Additional decision point, we are going to turn the case transfer process off for subsequent application.

**Comment by C-Love** [comment]
We need to update Subsequent Application to no longer support case transfers at all.

**Comment by IlseFerris** [comment]
The two items need to be addressed prior to this issue closing: 
- X127EG4 basket – This is an identified basket for MIPPA applications per Case Assignment’s current process, but was identified as a basket to close.
- X127EP6 basket – basket is closed in ECF Next, but has been identified as Adults. This is currently not an option for the Case Assignment team to send to this basket via NOTES – APPLICATION RECEIVED.

**Comment by C-Love** [comment]
DaNM - maybe we just move on.

**Comment by C-Love** [comment]
We are moving on - no one is going to speak to this.
