### ISSUE TITLE
NEW SCRIPT to support MFIP Designated Spousal Income policy

### ISSUE THREAD

**Issue by MiKaylaH22** [Hennepin-County/MAXIS-scripts#174]
0022.11 - NEW SPOUSE INCOME create a separate script to support this process. 
0017.11 - DETERMINING NEW SPOUSE INCOME

MFIP Designated Spousal Income

**Comment by IlseFerris** [comment]
MAXIS system has been updated to resolve this issue. Closing as a won't fix.
