### ISSUE TITLE
ADMIN-Review Report -- Update Review Report to unwind Interview Waiver

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#1753]
We need to start sending appointment notices for SNAP cases and not just MFIP cases. Update to Review Report to do this by the appt notice run in April (usually 4/25/24). 

NOMIs should not have to be changed as they are selected based on if an appointment notice was sent for the case but this should be confirmed. 

Additionally, no changes to individual scripts or supports for the application process should be needed because we did not change the notice process during the interview waiver for these cases.

**Comment by MeganGeissler** [comment]
No changes were made, scripts was already updated. Branch closed without merging.

**Comment by IlseFerris** [comment]
Line 3285 addresses the NOMI, but the APPT notices is where this code needs to be updated. Added @C-Love to the issue as well. 
@MeganGeissler can you look at Line 2514? And then we can remove all the PHE temp codes as well

**Comment by MeganGeissler** [comment]
SNAP Waived interview extended through oct, 31st '24. Postponing this until then.

**Comment by C-Love** [comment]
Notices are now sent for all SNAP and MFIP cases.
