### ISSUE TITLE
Combine Application Rcvd and CA Application Rcvd

### ISSUE THREAD

**Issue by MiKaylaH22** [Hennepin-County/MAXIS-scripts#176]
Associated with #113, update the main menu to call the notes script and ensure that is called in the desert island

**Comment by IlseFerris** [comment]
Closing associated issues, and reopening this issues. A few enhancements/issues have been identified by staff. Closed issue #180 and#183.

Another enhancement was reported by a user, and that was around the same day pop up box. This is not fitting into current processes. We will instead ask the worker if they are filling out the CAF and completing the interview currently. 

Actions to complete this issue:
- [ ] Add Fax option to how_recd drop list
- [ ] Remove duplicate header
- [ ] Update same day interview question to worker (see above)

**Comment by MiKaylaH22** [comment]
#232 Update Application Received with removal of same day interview everything. If same day is offered a worker should use interview completed script.
