### ISSUE TITLE
ADMIN - INTERVIEW REQUIRED enhancement 

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#179]
Add ER's without an interview to the final output of the lists if they do not have a CSR due, and are not found to have an interview required (GA, GRH, MSA only cases).

**Comment by IlseFerris** [comment]
To ease the need for weekly data on ER and CSR cases I will update the script to output all cases (including the phone numbers, language and interpreter needs) with the following data added: Interview required, No Interview and CSR. These data fields will update with a boolean status for each field for each case. Individual lists will still be created.

**Comment by IlseFerris** [comment]
Ask @C-Love for program status coding. Ask team about changing output of report case by case, and about creating a single list vs. individual lists for CSR and ER and ER without an interview.

**Comment by IlseFerris** [comment]
Notes from meeting with team: Continue to create separate Interview Required list. Boolean status for each program type Example: CASH - SR True/False, CASH ER True/False, 

Also adding discovery mode to the rebuild. Associated with issue #42 

See function determine_program_and_case_status_from_CASE_CURR for program status coding.

**Comment by IlseFerris** [comment]
Initial version ready and tested. Still need to add discrepancy list, and possible restart. Will plan with Casey as she will be adding data gathering to this code as well.

**Comment by IlseFerris** [comment]
ADMIN - INTERVIEW REQUIRED is going to retire, and will be replaced by ADMIN - REVIEW REPORT.

**Comment by IlseFerris** [comment]
Retired script. Active script REVIEW REPORT replaces INTERVIEW REQUIRED. REVIEW REPORT is live and an amazing enhancement.

**Comment by C-Love** [comment]
Some bugs to squish

**Comment by C-Love** [comment]
Fixes have been added - we should be good to go!
