### ISSUE TITLE
SNAP Waived Interview - noting qual questions wrong

### ISSUE THREAD

**Issue by courtrightd** [Hennepin-County/MAXIS-scripts#1818]
The Waived interview script and return contact functionality are noting the felony/disqual questions wrong, listing only the question not answered line.
Similar issue with "Other" questions noting as info needed when blank.

**Comment by C-Love** [comment]
DaNM - won't fix?

**Comment by courtrightd** [comment]
With the waiver ending 10/31 this is not worth the time to fix.
