### ISSUE TITLE
NEW SCRIPT On Demand case notes for QI

### ISSUE THREAD

**Issue by MiKaylaH22** [Hennepin-County/MAXIS-scripts#189]
Taking the template that was created and turning into a script perhaps having it generate emails for corrections along with completion email. also an idea to have it update PROG for missed interview handling and read for possible interview completed case notes. 

Case note script template for notes that are not created by the script
 
Correction needed:
Script - Application Received - not used when pending case
PROG not updated but interview has been completed
Migrant/Seasonal Farmworker field not updated
Script - CAF - used but no interview completed
Script - CAF - not used but approval made
Case not put in to PND2
Worker completed denial for no interview on PND2
Worker completed denial for no interview in ELIG
Interview completed on NOMI day and NOMI was not cancelled
Programs pended on 2 different dates
Clear case note for FS interview requirement not mentioned
Client contact was made no interview offered
Worker completed denial for no interview and did not use PND2

~ Client completed application interview --/--/-- PROG updated ~      
* Completed by previous worker per case note dated: --/--/--          
---                                                                   
EWS Quality Improvement Team                                                         

~ Client completed application interview --/--/-- TYPE & PROG updated ~       
* Completed by previous worker per case note dated: --/--/--
* Per CM 0005.12.03 -aligned CASH application to request for SNAP -           
  Applicants request another assistance program or in some other way amend    
  the application before the agency acts on their initial application.        
  Interview was not completed until 08/28/19 FS still pending                 
*Per CM 0030.03.01 - PROCESSING RCA APPLICATIONS we cannot require another interview for SNAP                                                          
~ Client has not completed CASH F2F application interview ~                       
 * Face to face required because client has not been open on CASH in the last
 12 months  
 * SNAP completed by previous worker per case note dated: 01/30/20             
 ---                                                                           
 EWS Quality Improvement Team                                                  
  
~ Interview not needed for MFIP to SNAP transition  --/--/--  PROG updated ~  
* MFIP to SNAP transition no interview required updated PROG to reflect this                                                          
                                                              
~ Withdrawal completed on PND2 when no interview has been completed ~       
* per case note client requested withdrawal --/--/--
* Client clarified that cash was not requested/needed and the application was 
withdrawn using PACT                                                          
                  
 ~ Application interview ~                                               
* Client is in an IMD FACI and is not required to complete interview  
* Updated PROG to ensure case is processed correctly   

~ Client has not completed application interview ~                            
* Interview is still need for FS, client has 30 days from date of application 
  to complete it. However, the appt letter provides a date of --/--/-- and     
  case was not pended timely a NOMI still needs to be sent and adequate time  
  provided to the client to comply.                                           

~ Client has not completed CASH app interview ~                               
* Interview is still need for FS, client has 30 days from date of application 
  to complete it. However, the appt letter provides a date of --/--/-- and     
  case was not pended timely a NOMI was sent and adequate time provided to    
  the client to comply.                                                       

~ Denied CASH/SNAP ~                              
* Reason for denial: interview was not completed timely. 
* Application date: --/--/--  
* NOMI sent to client on: --/--/--  

~ IDENTIFIED AS START TODAY ~
* EXTENDED APPLICATION DEADLINE DUE TO UNIQUE GRH PROCESSING
* Please allow a worker or HSS from Adults HS GRH team to review case before 
  denying. Thank you.

**Comment by C-Love** [comment]
My thoughts for this - remove the correction selection portion of this functionality make it separate process for case note templates only.

**Comment by MiKaylaH22** [comment]
copy the dialog to code and comment it out, make it a checkbox version instead of a dropbox align with email corrections as a stand alone script.

**Comment by IlseFerris** [comment]
Update - script will be updated to be only a case note. Email correction associated actions will be evaluated at a later time as this may be changing with task-based processing coming into the mix.

**Comment by C-Love** [comment]
No additional work, this is done.
