### ISSUE TITLE
QI XFS process add Count Columns Carryover

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#191]
Idea from Keith - 'have columns on the spreadsheets to allow us to check which one of these categories they fall into, so we know if the case has been counted already, or if additional action is needed, going through and counting all of these would be much easier and less redundant'

Add columns to the work list for XFS for each of the counts. 

Update Work Assignment Completed to read these columns if 'Y' is coded then change it to 'X' 

For the XFS Assignment Script carry the information in these columns from day to day.

**Comment by C-Love** [comment]
First of @IlseFerris - this functionality is SOO cool. LOVE IT. 

I do think two of the headers of the new notes columns are off. We can chat on in on the meeting. 

I have the updates to Work Assignment Completed updated.

**Comment by C-Love** [comment]
ADMIN - Work Assignment Completed is ready for testing on this issue.

**Comment by C-Love** [comment]
@IlseFerris - I was able to run a quick check on Work Assignment Completed with the data that was in the file. There are a couple of stability pieces I added and it appears to be working. We are ready to MERGE!!!

**Comment by IlseFerris** [comment]
Yay, pull request completed. Closing issue!
