### ISSUE TITLE
Move Instruction Files for SharePoint Online

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#198]
When all of the SharePoint moves to Online our Instruction files need to be changed. 

We are getting help with this.

This needs to be done when the move happens.

**Comment by C-Love** [comment]
I will update the Complete list of scripts with the new main folder url and then communicate when it is done for Laurie to test.

**Comment by C-Love** [comment]
@IlseFerris Updates to Complete List of Scripts has be made and pushed out. 

The Instructions buttons should be working! We are ready for testing.

**Comment by IlseFerris** [comment]
Associated with issue #163 and #246

**Comment by IlseFerris** [comment]
All updates have been made save for needing to write instructions for ADMIN - WF1 Case Status

**Comment by IlseFerris** [comment]
ADMIN - WF1 Case Status Complete. 4 QI scripts need review for local instructions. Discuss at next meeting.
