### ISSUE TITLE
Expedited APPROVAL at Determination

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#208]
This is an automation script that will run at the time of expedited determination. 

Th goal will be for the script to guide through the entire expedited process:
1. Guide the worker through the determination of expedited to identify if a case is expedited.
2. Update MAXIS and generate a accurate ELIGIBILITY results.
3. APPROVE the eligibility results to ensure expedited is processed. 
4. CASE:NOTE correctly (either the approval OR a determination that indicates NOT expedited or expedited but delayed).

**Comment by IlseFerris** [comment]
Project SPARQ issues on hold for Project TBD #351.

**Comment by C-Love** [comment]
Need to handle for FIATing of SPON income - which will handle the issue #173 and incorporate it all into one thing. Solve these together.

**Comment by C-Love** [comment]
Need to handle for the EBT card issuance/REI information and communication.

**Comment by C-Love** [comment]
Associated with QI Project Board - Postponed EXP SNAP Notice Verbiage in Project Board

**Comment by IlseFerris** [comment]
Closing as a won't fix. As an agency we are not in a place of quality processing to move this forward.
