### ISSUE TITLE
New script NDNH HIRE

### ISSUE THREAD

**Issue by MiKaylaH22** [Hennepin-County/MAXIS-scripts#212]
Create a script that runs on all remaining NDNH New Hire messages on 10 Day Cutoff. It would check to be sure the initial request was sent (using CASE:NOTE) and 10 days had lapsed. We might need to update the NDNH to provide better confirmation of the verif request sent. Then it would close for no verif and add a WCOM.

These could always be Reopened if docs are received in time manually by worker.

**Comment by C-Love** [comment]
Closing - This will be handled in #514
