### ISSUE TITLE
PARIS MATCH CLEARED 

### ISSUE THREAD

**Issue by MiKaylaH22** [Hennepin-County/MAXIS-scripts#218]
- [ ] We do not have a script for Paris Match – Claim Entered NO DAIL Can we make the dail script to run without a dail ? 
- [ ] What we need is the written policy and procedure outside of this script that defines the email and the case and need to be written in the HSR manual 
- [ ] Use the supplemental questionnaire after the questions are completed
- [ ] After 10 days run again to clear
- [ ] If fail to resolve then add pact panel reminder to check for all programs and change addr to "no"
- [ ] NON COOP no handling currently 
- [ ] Handle for multiple HH members

**Comment by IlseFerris** [comment]
Closing issue as won't fix. These issues have not been reported by the team, and detailed processes for clearing PARIS matches have not been provided.
