### ISSUE TITLE
CSES for SNAP BULK DAIL MSG

### ISSUE THREAD

**Issue by MiKaylaH22** [Hennepin-County/MAXIS-scripts#219]
We could add a BUNCH of support to review CS income and case and PRISM and UPDATE UNEA and do a potential approval.

**Comment by IlseFerris** [comment]
#671 Might be able to handle for this for SNAP, or at least for SNAP 6 month reporter cases.

**Comment by IlseFerris** [comment]
Won't fix. Will be supporting in Unclear Information project.
