### ISSUE TITLE
October Annual Changes - Multi Script/Function

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#229]
HEST Standard Changes for the following scripts:

- [x] NOTES - APPLICATION RECEIVED
- [x] NOTES - CAF
- [x] NOTES - CAF ADDENDUM
- [x] NOTES - EXPEDITED SCREENING

Income Standard Changes for the following scripts/functions: 
- [x] NOTES - IMIG - SPONSOR INCOME
- [x] Income_test_SNAP_categorically_elig
- [x] income_test_SNAP_gross
- [x] Income_test_SNAP_net

MHC- Enrollment script informationrequired:
- [x] Capitation dates for next year - reach out to MHC team for new dates (script update not needed until December)
- [x] Enrollment plans for next year - reach out to MHC team for new plans - update will be needed in October if there are changes. There are often no changes.

**Comment by IlseFerris** [comment]
@C-Love take it away!

**Comment by C-Love** [comment]
@IlseFerris Confirmed that there is nothing to change in CAF Addendum.

**Comment by IlseFerris** [comment]
October 1 tasks and changes complete. @C-Love will be creating a new issue to update the MHC information.
