### ISSUE TITLE
Desert Island Menu - CA - APPLICATION RECIEVED was replaced by NOTES - APPLICATION RECIEVED

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#230]
See above.

**Comment by C-Love** [comment]
This is done. These files are local by nature and there are no commits for this issue. 

We need to make sure the monthly backups are set up correctly and we have the right files. Then we need to discuss the folder I added for retiring desert island scripts.

We also need to see how much we care about testing on this.

**Comment by C-Love** [comment]
This is completed and all tasks done.
