### ISSUE TITLE
DEU - Match Cleared process questions

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#236]
Errors reported on Match Cleared have raised a few questions:

1. Program specific resolution codes. 
2. Clearing matches with more than one program. 
3. Claim handling - this should be separate from the creation of the claim. 
4. Possible policy discrepancy review.

Need additional review/information.

**Comment by IlseFerris** [comment]
Changed to WAIT status. Waiting for HSS to complete written processes to align staff expectations and the scripts.

**Comment by IlseFerris** [comment]
Closing as a won't fix. The DEU group has not specified issues with these scripts nor provided detailed documentation to use for evaluation of script updates.
