### ISSUE TITLE
Identification and review of potential Waived Interview ER cases

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#238]
This has two main components:

1. BULK script to assess a list of cases (ie the ER list generated with Interview Required)
2. INDIVIDUAL evaluator for HSRs to determine potential eligibility for having an interview waived.

FOR THE BULK SCRIPT:
Review if the case is on the list of adjusted ERs for the specific ER month. Add the active cash programs to a case.

FOR THE INDIVIDUAL SCRIPT:
Need to handle for if HSR finds a case that might be waived and needs QI to review.

To include:
Check the adjusted list
Be sure there is a CAF
Do you need to send a referral?
Maybe other things

Needs:
1. The approved Process
2. Can workers make the assessment of waiving an interview or do they need 'approval' from a specfic group?
3. Where do these requests go to?
4. What words/verbiage do we need to add to remind workers about how to handle these cases?

This can be a fairly quick turnaround but we need to be able to communicate.

**Comment by IlseFerris** [comment]
[Link](onenote:///T:\Eligibility%20Support\Restricted\QI%20-%20Quality%20Improvement\QI%20Meetings\Shared%20Projects.one#SNAP%20Recert%20Waiver%20&section-id={7ADFA72B-894D-4E97-B9EE-1C476CD8CBA1}&page-id={E5726803-CBE1-413B-B2A0-5C0480C4663E}&end) to SNAP Recert Waiver Information in OneNote

**Comment by C-Love** [comment]
This commit is not connected to this issue.

**Comment by C-Love** [comment]
We now have an approved individual process. We will be finalizing the verbiage of that and publishing it to the HSR manual. 

The individual script is in development.

**Comment by C-Love** [comment]
Both the individual script and the bulk script are done and have been tested and are in good use. 

DONE!
