### ISSUE TITLE
Remove mention of VGO/ESSO from scripts

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#257]
Testing of shutting down ESSO was added to specific script files, but was not removed when ESSO retired. Remove coding in the following scripts:
- locally-installed-files/redirect-admin-main-menu.vbs
- managed-care/mc-enrollment-note.vbs

**Comment by IlseFerris** [comment]
Clean up complete. Closing issue.

**Comment by MiKaylaH22** [comment]
admin/on-demand-waiver-applications.vbs
retired-scripts/language-stats.vbs
deu/rept-ievc-list.vbs
admin/basket-review.vbs
admin/vendor-list.vbs
