### ISSUE TITLE
Create support and resources for HSSs around use of Scripts and Activity Report

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#263]
Script usage is being used as a performative measure and we need to provide detail and information around this structure and report out. This is also tied to other work in performance management.

**Comment by IlseFerris** [comment]
Depending on the decision here, next steps could include creating a PowerPoint, BZ Roadshow, communication to HSR's, etc. to promote message of Comprehensive Use of Scripts.

**Comment by IlseFerris** [comment]
We are holding on this for now. Will discuss again post-peacetime emergency.

**Comment by IlseFerris** [comment]
Closing as won't fix. Guidance exists in performance management re: comprehensive use of scripts.
