### ISSUE TITLE
Instructions button in UTILITIES MAIN MENU link is broken for ADD WCOM 

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#275]
It appears to not be working due ADD WCOM script does not have an identified category in the class structure. Casey will confirm/do additional discovery.

**Comment by IlseFerris** [comment]
@C-Love - the hyperlink in ADMIN - SEND EMAIL CORRECTION will also need to be reviewed after fix.

**Comment by C-Love** [comment]
This was actually hard coded INTO the menu because it doesn't follow the normal system/process that the '?' buttons do. I also updated the COMPLETE LIST OF SCRIPTS so the correct Instructions URL can be generated using the class if needed.

**Comment by C-Love** [comment]
Jacob tested this and it is working and done
