### ISSUE TITLE
Changes Reported Project - workflow? dashboard?

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#288]
We will be looking at updating how changes reported operates, adding more functionality and actions and allowing for ease of access and use. This may integrate with Client Contact.

We will incorporate as many common changes as we can and allow them to update well and guide users through gathering the correct data and entering it into STAT and NOTEs accurately and quickly. 

This is a LARGE project and this issue serves as a placeholder.

**Comment by C-Love** [comment]
There is a folder in the BZ Projects > Projects folder for BOWIE that has some information saved from previous discussion and DHS issues.

**Comment by IlseFerris** [comment]
#390 - Consider this update when rebuilding CLIENT CONTACT.

**Comment by C-Love** [comment]
We are working more toward using the HSR steps to connect to work to be done. So this work will be handled in Client Contact Updates and Docs Received updates since that is what is being done when changes are reported.
#390 
#425
