### ISSUE TITLE
MFIP Special Diet

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#29]
Requested by Kela Williams and Yanisha Mak on 1/25/17

This is for MFIP ONLY.

Will need BULK MONY/CHCK and offline MFIP Special Diet support needed. Tammy Coenen lead for this part of the process.

**Comment by IlseFerris** [comment]
I will follow up with Faughn re: BULK MONY/CHCK to see if this is still needed.

**Comment by IlseFerris** [comment]
Written procedure does not exist for MFIP special diet process in the HSR manual. Will contact project requester. May open at a later date if procedure is identified.
