### ISSUE TITLE
UTILITIES - QI AVS Request Enhancement

### ISSUE THREAD

**Issue by MiKaylaH22** [Hennepin-County/MAXIS-scripts#293]
With regards to the QI AVS Request script, would it be possible to enhance it to have a check box for Sponsor and Sponsor Spouse?  Along with this to also read from the SPON panel and if nothing is there, require the HSR to input the information, as this is needed for AVS?
If SPON panel exists but information is not great, also for work to enter information. 

Also add support for not selecting members under 18 or without SSN's.

**Comment by IlseFerris** [comment]
Due to functionality planned for the DASH process/Project TBD, we will not make updates to this script as it will be planned for retirement.
