### ISSUE TITLE
MHC Client Contact is not pulling Info into NOTE

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#298]
The Client Contact script for MMIS/MHC is not pulling information to the note.

**Comment by C-Love** [comment]
@IlseFerris can I move this to critical since this has not been working since PRIOR to Sept 2017. It does not actually put the information in the case note.

**Comment by IlseFerris** [comment]
@C-Love oh my, yes.

**Comment by C-Love** [comment]
Moving to active develoment to resolve critical bug

**Comment by C-Love** [comment]
Client contact MHC note is now putting everything in it.
