### ISSUE TITLE
BULK script for GA Advanced Age

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#30]
Request by Faughn Ramisch-Church on 5/16/17

Look for GA active cases/Over 55 years-old/coded 12 on WREG panel/read employment, assess date/CASH/GRH status/DISA begin date.

**Comment by IlseFerris** [comment]
I will confirm with Faughn if this is a project that we still want to work on.

**Comment by IlseFerris** [comment]
Changing to a wait status due to being a lower priority project.

**Comment by IlseFerris** [comment]
Per [CM0013.50.30](https://www.dhs.state.mn.us/main/idcplg?IdcService=GET_DYNAMIC_CONVERSION&RevisionSelectionMethod=LatestReleased&dDocName=CM_00131530), assessments for employment are needed. BULKing out this work is not advised. Project sponsor agreed. Closing issues.
