### ISSUE TITLE
NDNH NEW HIRE add script run low down

### ISSUE THREAD

**Issue by MiKaylaH22** [Hennepin-County/MAXIS-scripts#302]
Error occurred on 12/8/2020 at 8:21:11 AM 
Error type - BUG - something happened that was wrong 
Script name - DAIL - NEW HIRE NDNH.vbs was run on Case #1672266 with a runtime of 1662.242 seconds. 
Information: THE C/NOTE WAS NOT COMPLETE. THE SYSTEM KEPT FLICKERING. NOT SURE UNTIL AFTER I CLOSE THIS WINDOW WHAT ALL WAS AFFECTED, SO I MARKED THE 3 AREA'S I THOUGHT COULD HAVE BEEN AFFECTED.
Script has issues/concerns in the following areas: 
 - CASE/NOTE 
 - Update in STAT 
Closing message: Success! MAXIS updated for new HIRE message, a case note made, and a TIKL has been sent for 10 days from now. An Employment Verification and Verif Req Form should now be sent. The job is at MASTERSON STAFFING S.

**Comment by C-Love** [comment]
Closing - This will be handled in #514
