### ISSUE TITLE
Docs Received - ATRs (Authorization to Release) add handling for written AND verbal

### ISSUE THREAD

**Issue by MiKaylaH22** [Hennepin-County/MAXIS-scripts#305]
Can we create a BZ for authorizations? 
Similar to the significant change script and don’t have to go through case to be able to see if the auth is on file 
Docs rcvd enhancement maybe *authorization for each employer 
Using the one source format as a model 
What is the process?
where is it written down?
- client contact if it is verbal, check a box for open docs rcvd and who is the member when was it allowed and expired and a new case note Is it a process for HC to provide a separate case note for an HSR to create a separate case note each time

We can read the case note for the verbal attestation piece and pull to get the auth

**Comment by IlseFerris** [comment]
Hey let's make this one a function too!
