### ISSUE TITLE
Returned Mail - review script add handling for pending programs

### ISSUE THREAD

**Issue by MiKaylaH22** [Hennepin-County/MAXIS-scripts#309]
Will only case note active programs, needs line by line review

**Comment by C-Love** [comment]
Needs handling for an INACTIVE CASE. 

Also - @C-Love and @MiKaylaH22 to do a line by line review/rewrite at some future time.

**Comment by MiKaylaH22** [comment]
Removed duplicate lines 355-366 
Add handling for users entering same address as current address on ADDR

**Comment by MiKaylaH22** [comment]
ADHI - review

**Comment by MiKaylaH22** [comment]
case note what was the old address and what is the new address?

**Comment by MiKaylaH22** [comment]
add handling for pending programs ensure that PACT panel

**Comment by MiKaylaH22** [comment]
The pending programs ended up only mattering when closing using PACT and that is specific to no response being received

**Comment by MiKaylaH22** [comment]
Reviewed with Ilse line by line, added/replaced with functions and handling, no issues reported so far. Programs are only affected by the need of the pact panel updated to contain handling therein.
