### ISSUE TITLE
2022 Standardization Effort - Ensure Worker Signature is in all scripts that CASE/NOTE

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#316]
We need to double check that there is field for worker_signature and that it's mandatory. More information to come in discovery.

**Comment by C-Love** [comment]
We might want to use #125 to guide/support this standardization effort.

**Comment by MiKaylaH22** [comment]
- [ ] ACTIONS	Send SVES
- [ ] ADMIN	UNEA Updater
- [ ] ADMIN	CS Good Cause
- [ ] ADMIN	Individual Appointment Letter
- [ ] ADMIN	Individual NOMI
- [ ] ADMIN	MONT Report
- [ ] ADMIN	On Demand Notes
- [ ] ADMIN	MFIP Sanction FIATer
- [ ] ADMIN	Individual Recertification Notices
- [ ] ADMIN	Review Report
- [ ] BULK	Case Transfer
- [ ] DAIL	Incarceration
- [ ] DAIL	Citizenship Verified
- [ ] DAIL	FMED Deduction
- [ ] DAIL	New Hire
- [ ] DAIL	Postponed Expedited SNAP Verifications
- [ ] DAIL	New Hire NDNH
- [ ] DEU	BULK - DEU-MATCH CLEARED
- [ ] DEU	NOTES - DEU-APPEAL SUMMARY COMPLETED
- [ ] DEU	NOTES - DEU-EBT OUT OF STATE
- [ ] DEU	ACTIONS - DEU-OVERPAYMENT CLAIM ENTERED
- [ ] DEU	ACTIONS - DEU-PARIS MATCH CLEARED
- [ ] DEU	NOTES - DEU-ADH INFO HEARING
- [ ] NOTES	Citizenship Identity Verified
- [ ] NOTES	Disaster Food Replacement
- [ ] NOTES	IMIG - STATUS
- [ ] NOTES	Vendor
- [ ] NOTES	Drug Felon
- [ ] NOTES	GRH NON HRF POSTPAY
- [ ] NOTES	LTC - Hospice Form Received
- [ ] NOTES	LTC - COLA Summary
- [ ] NOTES	Application Check
- [ ] NOTICES	Verifications Still Needed
- [ ] NOTICES	PA Verif Request
- [ ] SHELTER	NOTES - SHELTER-2 PM RETURN
- [ ] SHELTER	NOTES - SHELTER-311
- [ ] SHELTER	NOTES - SHELTER-ACF REQUEST PENDING
- [ ] SHELTER	NOTES - SHELTER-BUS TICKET ISSUED
- [ ] SHELTER	NOTES - SHELTER-CES SCREENING APPT
- [ ] SHELTER	NOTES - SHELTER-CLIENT SHELTERED BY WINDOW A
- [ ] SHELTER	NOTES - SHELTER DIVERSION PROGRAM REFFERRAL RESULT
- [ ] SHELTER	NOTES - SHELTER DIVERSION PROGRAM REFFERRAL
- [ ] SHELTER	NOTES - SHELTER-EA APPROVED
- [ ] SHELTER	NOTES - SHELTER-EA EXTENSION
- [ ] SHELTER	NOTES - SHELTER-HOMELESSNESS VERIFIED
- [ ] SHELTER	NOTES - SHELTER-MANDATORY VENDOR APPROVED
- [ ] SHELTER	NOTES - SHELTER-PARTNER CALLS
- [ ] SHELTER	NOTES - SHELTER-PERMANENT HOUSING FOUND
- [ ] SHELTER	NOTES - SHELTER-PERSONAL NEEDS
- [ ] SHELTER	NOTES - SHELTER-PNOTE
- [ ] SHELTER	NOTES - SHELTER-REIM SHELTER ACCT
- [ ] SHELTER	NOTES - SHELTER-SHELTER ALTERATIVE
- [ ] SHELTER	SHELTER-SHERIFF FORECLOSURE
- [ ] SHELTER	NOTES - SHELTER-SPECIAL EA
- [ ] SHELTER	NOTES - SHELTER-UTILITY INFO
- [ ] SHELTER	NOTES - SHELTER-VOUCHER EXTENDED
- [ ] SHELTER	NOTES - SHELTER-NSOPW CHECKED
- [ ] SHELTER	NOTES - SHELTER-ACF USED
- [ ] SHELTER	NOTICES - SHELTER-MAND VENDOR MEMO

**Comment by MiKaylaH22** [comment]
In the specialty teams Shelter and DEU the team name was listed in lieu of the worker signature and the worker signature has been added. After the script was released it was determined that the workers will determine their worker signature with their teams and this is out of the scope of this project. The team name in the signature will be removed for the following scripts: 
REMOVE - "DEBT ESTABLISHMENT UNIT 612-348-4290 PROMPTS 1-1-1"
NOTES - DEU-ADH INFO HEARING
NOTES - DEU-APPEAL SUMMARY COMPLETED
NOTES - DEU-ATR RECEIVED
BULK - DEU-MATCH CLEARED
NOTES - DEU-EBT OUT OF STATE
ACTIONS - DEU-MATCH CLEARED
ACTIONS - DEU-OVERPAYMENT CLAIM ENTERED
ACTIONS - DEU-PARIS MATCH CLEARED CC
ACTIONS - DEU-PARIS MATCH CLEARED
---------------------------------------------------------
REMOVE - "Hennepin County Shelter Team"
NOTES - SHELTER-2 PM RETURN
NOTES - SHELTER-ACF REQUEST PENDING
NOTES - SHELTER-ACF USED
NOTES - SHELTER-BUS TICKET ISSUED
NOTES - SHELTER-CES SCREENING APPT
NOTES - SHELTER-CLIENT SHELTERED BY WINDOW A
NOTES - SHELTER DIVERSION PROGRAM REFFERRAL RESULT
NOTES - SHELTER-EA APPROVED
NOTES - SHELTER-EA EXTENSION
NOTES - SHELTER-HOMELESSNESS VERIFIED
NOTES - SHELTER-MANDATORY VENDOR APPROVED
NOTES - SHELTER-NSOPW CHECKED
NOTES - SHELTER-PNOTE
NOTES - SHELTER-PARTNER CALLS
NOTES - SHELTER-PERMANENT HOUSING FOUND
NOTES - SHELTER-PERSONAL NEEDS
NOTES - SHELTER-REIM SHELTER ACCT
NOTES - SHELTER-REVOUCHER
NOTES - SHELTER-SHELTER ALTERATIVE
NOTES - SHELTER-SHELTER INTERVIEW
NOTES - SHELTER-SHERIFF FORECLOSURE
NOTES - SHELTER-SPECIAL EA
NOTES - SHELTER-UTILITY INFO
NOTES - SHELTER-VOUCHER EXTENDED

**Comment by MiKaylaH22** [comment]
In the specialty teams Shelter and DEU the team name was listed in lieu of the worker signature and the worker signature has been added. After the script was released it was determined that the workers will determine their worker signature with their teams and this is out of the scope of this project. The team name in the signature will be removed for the following scripts: 
---------------------------------------------------------
REMOVE - "DEBT ESTABLISHMENT UNIT 612-348-4290 PROMPTS 1-1-1"
NOTES - DEU-ADH INFO HEARING
NOTES - DEU-APPEAL SUMMARY COMPLETED
NOTES - DEU-ATR RECEIVED
BULK - DEU-MATCH CLEARED
NOTES - DEU-EBT OUT OF STATE
ACTIONS - DEU-MATCH CLEARED
ACTIONS - DEU-OVERPAYMENT CLAIM ENTERED
ACTIONS - DEU-PARIS MATCH CLEARED CC
ACTIONS - DEU-PARIS MATCH CLEARED
---------------------------------------------------------
REMOVE - "Hennepin County Shelter Team"
NOTES - SHELTER-2 PM RETURN
NOTES - SHELTER-ACF REQUEST PENDING
NOTES - SHELTER-ACF USED
NOTES - SHELTER-BUS TICKET ISSUED
NOTES - SHELTER-CES SCREENING APPT
NOTES - SHELTER-CLIENT SHELTERED BY WINDOW A
NOTES - SHELTER DIVERSION PROGRAM REFFERRAL RESULT
NOTES - SHELTER-EA APPROVED
NOTES - SHELTER-EA EXTENSION
NOTES - SHELTER-HOMELESSNESS VERIFIED
NOTES - SHELTER-MANDATORY VENDOR APPROVED
NOTES - SHELTER-NSOPW CHECKED
NOTES - SHELTER-PNOTE
NOTES - SHELTER-PARTNER CALLS
NOTES - SHELTER-PERMANENT HOUSING FOUND
NOTES - SHELTER-PERSONAL NEEDS
NOTES - SHELTER-REIM SHELTER ACCT
NOTES - SHELTER-REVOUCHER
NOTES - SHELTER-SHELTER ALTERATIVE
NOTES - SHELTER-SHELTER INTERVIEW
NOTES - SHELTER-SHERIFF FORECLOSURE
NOTES - SHELTER-SPECIAL EA
NOTES - SHELTER-UTILITY INFO
NOTES - SHELTER-VOUCHER EXTENDED
