### ISSUE TITLE
Application Received Script- add Retro Request for Auto Newborn

### ISSUE THREAD

**Issue by MiKaylaH22** [Hennepin-County/MAXIS-scripts#322]
1.	I am requesting an additional check box be added in the Application Received Script: that reads                               “Retro Request for Auto Newborn”
2.	We would also want the script to add a case note that specifies the request to appl was for an auto newborn, which is why only the baby and parent were appl’d on the case.

 
We were thinking the check boxes reflect these below:

 MA Transition
 METS Retro Coverage
               Team 603 (i.e. 601) will process
               Auto Newborn Request

3.	I am also requesting the script pull household composition members; that way we would be able to select which household members are requesting HC. This addition would then eliminate the MEMB # for HC field.

**Comment by MiKaylaH22** [comment]
1. Old scripts showed the x127—on the case note, but the new scripts did not showed the x127n—on the case note.
Can you add the x127—back into the case note? Because the HSR can follow up with that x127—on the case note, when they have question about the case. 
talked with Casey about discussing a separate script to help tracking so that we dont have to have worker numbers in case notes

**Comment by MiKaylaH22** [comment]
Possible enhancement to update the Request to APPL portion and use the end message to track the requested_user

**Comment by IlseFerris** [comment]
REQUEST to APPL Useform says the following ---
Use this form if you have: 
- An application in ECF that needs to be APPLed in MAXIS, 
- An MA Transition Case
- Or a METS Case that needs Retro coverage. 

Based on this, we should keep the X number out. I can discuss this with the PM if necessary.

**Comment by IlseFerris** [comment]
Testing period completed. Was in testing for 2 week. New issue created to address X number field to be removed (see comment above). #354 is new issue.
