### ISSUE TITLE
Spelling Error "Recieved" in Multiple Scripts

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#327]
From Rachel Ferguson: I noticed that application check case note misspells * Verifications Rec**ei**ved: as * Verifications Rec**ie**ved:

**Comment by IlseFerris** [comment]
- [ ] DAIL - NEW HIRE
- [ ] DAIL - NEW HIRE NDNH
- [ ] NOTES - APPLICATION CHECK
- [ ] NOTES - CAF ADDENDUM
- [ ] NOTES - DISASTER FOOD REPLACEMENT
- [ ] NOTES - DOCUMENTS RECEIVED
- [ ] NOTES - OVERPAYMENT
- [ ] TEST SCRIPTS OUT OF STATE CORRESPONDENCE
- [ ] TEST SCRIPTS OUT OF STATE CORRESPONDENCE CASEY DID THINGS

**Comment by IlseFerris** [comment]
Resolved all existing spelling errors for 'received' or 'receive'.
