### ISSUE TITLE
Function update: HH_member_custom_dialog(HH_member_array) add a parameter to select HH members or not

### ISSUE THREAD

**Issue by MiKaylaH22** [Hennepin-County/MAXIS-scripts#338]

**Comment by MiKaylaH22** [comment]
make sure we dont leave nothing checked

**Comment by IlseFerris** [comment]
We as a team decided we are going to revisit this function update at a later date. Ideas to enhance the function include adding option to check or uncheck HH_members in initial dialog, displaying more information (like relationship code) in initial dialog, whether or not to add more functionality to the function for output/MEMB information to array, etc.

**Comment by IlseFerris** [comment]
Closing as a won't fix. This handling should be in individual scripts.
