### ISSUE TITLE
Script Tools for QC

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#34]
Create scripts or a script with a dashboard for sending MEMOs and adding NOTES for QC actions taken. There are certain processes that need to be handled for. Talk to Mandora about specific needs. Additionally we will want to add functionality to update DISQ at some point. 

Requested by Mandora Young on 03/06/19:

Ideas for support include:
• Creating notes and memos for QC case actions
• Create email re: QC information/request
• Updating DISQ panels.

This is Phase 2 from ADMIN - QC Results. Email from Madora with more details.

**Comment by IlseFerris** [comment]
I'll follow up with Mandora for a possible Q3 project.

**Comment by IlseFerris** [comment]
Mandora still wants support here, but based on scope let's look more at Q4. @MiKaylaH22  do you want to take this one on?

**Comment by C-Love** [comment]
Any needs from QI should come in from QI and we will assess upon request. Additional details about theses needs have not been provided for 2 years. Closing this issue.
