### ISSUE TITLE
Expedited Determination Enhancements

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#345]
Enhance functionality within the NOTES - CAF and NOTES - EXPEDITED DETERMINATION scripts to have more information in the headers and acceptable delay reasons. IE - delay due to no ID, delay due to currently in INEL SNAP facility, etc.

Associated with work being done on #343

**Comment by IlseFerris** [comment]
Other ideas for enhancement: Add Help Button for common error prone scenarios. 
EXP determination can reflect a "FALSE" determination for several reasons.
For example:

- Case is Uncle Harry FS with MFIP Pending.
- Income and Asset Information is incorrect on STAT panels.

The Enhancement will add a question mark icon to the dialog. When the user presses the question mark a message box will appear listing common areas of error and instruct worker to review case.
This is from DHS project issue [2893](https://github.com/MN-Script-Team/DHS-MAXIS-Scripts/issues/2893).

**Comment by IlseFerris** [comment]
Metrics to capture for EXP SNAP based on our conversation today with Jennifer:
- Case number
- Worker Name
- X number (to figure out population)
- Date of application 
- Date of interview 
- Expedited screening status
- Expedited determination status
- Date of approval
- SNAP Denial date
- SNAP denial reason 
- ID on file
- End date of snap in another state
- Expedited approve previously postponed (Boolean)
- Explain Approval Delays (all of them)
- Postponed verifications
- What are the postponed verifications 
- Date of script run

**Comment by C-Love** [comment]
Need to call out the DETERMINATION CONCLUSION needs a better call out in FORMATING. The verbiage is good.

**Comment by C-Love** [comment]
Functionality released and well tested. DONE
