### ISSUE TITLE
ADMIN - On Demand Waiver Applications - Add Default Call to open the file by todays date

### ISSUE THREAD

**Issue by MiKaylaH22** [Hennepin-County/MAXIS-scripts#347]
Look at expedited

**Comment by IlseFerris** [comment]
Check out ADMIN - EXPEDITED REVIEW for the file default code. It defaults to the previous business day, accounting for holidays and weekends.

**Comment by IlseFerris** [comment]
In testing for a week, and users confirmed it's working. Closing issue.
