### ISSUE TITLE
Process support for handling EVFs correctly

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#35]
Request from Zaki Issac on 4/19/19

---
1. Workers must request EVF/stop work   verifications and allow 10 days before taking actions.      
2. Clients need to sign and date ATR for Employers.      
3. Workers can pull work# upon clients’ consents.      
4. Workers can call employers upon clients’ consents.     
5. When all other attempts by client and agency to obtain employment   information is unsuccessful, agency can accept clients’ written statement   that includes clients’ full name, employer names, last date of employment,   last check date and gross amounts and hours, and clients’ signature and date.        
6. Workers must casenote in details on every steps taken and include list   all individuals’ names and telephone numbers contacted and the reason or   difficulty of obtaining the verifications from the employers.      Completing an ATR     Signed EVF is enough to call employer     ATR or EVF is needed     *Will spell out for clarification in talking points
---

https://hennepin.sharepoint.com/teams/hs-es-manual/SitePages/Acceptable_Verification.aspx

**Comment by IlseFerris** [comment]
Closing as a won't fix. #305, #719 and #390 will resolve the majority of these issues. This is a policy heavy process vs procedure  heavy process, and the scope of staff needing to take all these steps is small enough to not be able to be measured.
