### ISSUE TITLE
NOTES-APPLICATION RCVD - Remove X127 from case note

### ISSUE THREAD

**Issue by MiKaylaH22** [Hennepin-County/MAXIS-scripts#354]
OS staff has used this to track who had submitted the request but 
REQUEST to APPL Useform says the following ---
Use this form if you have:
An application in ECF that needs to be APPLed in MAXIS, An MA Transition Case Or a METS Case that needs Retro coverage.

**Comment by MiKaylaH22** [comment]
Suggested that ECF form be sent to ECF for tracking purposes

**Comment by C-Love** [comment]
This is done and working.
