### ISSUE TITLE
DAIL - POSTPONED EXP SNAP VERIFICATIONS enhancement: Add MEMO to functionality

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#363]
This is an issue from the statewide project from @C-Love dated 04/21/17: It has been requested to help with communication to add a tool to send an explanatory memo out to clients about postponed verifications not being received and so SNAP will not continue. The DAIL Scrubber script already acts on the DAIL message alert to a case auto-closing with a case note and so would be a natural place to add this.
The idea is to increase the amount of information that is in this memo to the client about their SNAP closure.

**Comment by C-Love** [comment]
Associated with QI Project Board - Postponed EXP SNAP Notice Verbiage in Project Board
