### ISSUE TITLE
NOTES - RETURNED MAIL RECEIVED: HC active/pending procedure

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#365]
There is a lack of procedure for MAXIS based health care case in pending or active statuses. Brenda R is reaching out to HC policy for guidance. May need to update the script to only support CASH and SNAP.

**Comment by IlseFerris** [comment]
Update from DHS - HCEA group will review procedural steps and evaluate updates to OneSource to account for MAXIS system cases.

**Comment by MiKaylaH22** [comment]
OneSource - provided updates 01/27/22 

- [ ] Cases cannot be closed for address unknown currently (HC)
- [ ] Contact with the client should be case noted(even if only attempted)

**Comment by IlseFerris** [comment]
Discuss at next meeting to talk to Casey about work with Jake, etc. around when we need to contact a resident and what those notes should look like.

**Comment by MiKaylaH22** [comment]
[#427 NOTES RETURNED MAIL - update PROG](url)

**Comment by MiKaylaH22** [comment]
Returned mail with forwarding address
1. Call the household to confirm the current address information.
2. Update the case with the new address and forward the mail.
	A. If the enrollee has moved out of your agency, follow current procedures to transfer the case to the new county or tribal agency.
	B. If the enrollee has moved out-of-state, follow current procedures to close the case.
Returned mail with no forwarding address
1. If the mail was returned as undeliverable, compare the address on the returned mail with the following systems for the most up-to-date address:
	MAXIS
	METS (evidence dashboard, person record(s), case notes)
	Case file documents
	MMIS
2. If the address for the case contains errors or there is a more current address:
	A. Update the case with the correct or new address and forward the mail.
3. If after following the steps above, there is no explanation why the mail was returned, call the household to confirm the current address information:
	A. If new address information is provided, update the case with the new address, case note and forward the mail.
	B. If they have moved out of your agency, follow the current procedure to transfer case to the new county or tribal agency.
	C. If unable to make contact, follow steps in POLI/TEMP TE09.24.04 Whereabouts Unknown.

**Comment by MiKaylaH22** [comment]
from discovery on the ADDR panel: the county code is being removed as we are only updating the mailing address .
We will not be updating the "OT" as that is also in the residential section.

**Comment by MiKaylaH22** [comment]
No issues reported but reviewing usage to ensure all issues are addressed
