### ISSUE TITLE
Find Member in MMIS with recent HC Eligibility

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#37]
Create a tool to look up any affiliated cases in MAXIS.

Possible add-on, determine if duplicate PMI exists. This may need its own issue and script.

Request from Aaron Gardner-Kocher on 5/7/19

**Comment by IlseFerris** [comment]
Question - should this one be on the power pad?

**Comment by IlseFerris** [comment]
Per the team's conversation, as this will be primarily a UTILITY type of script vs. a NAV script, and will not be placed on the power pad.

**Comment by IlseFerris** [comment]
Create a function that can also be added into Client Contact, etc. Parallel task #390

**Comment by C-Love** [comment]
Changing the scope here to look for active or recently closed cases in MMIS for an individual as opposed to a whole case. 

The script will select an individual from a case and then use PMI, SSN, DOB, and Name in different combinations to find multiple PMIs in MMIS. These PMIs will all be searched for any active HC span or any HC span that closed in the past 4 months and capture that Case Number and PMI for a display of informaiton.

**Comment by C-Love** [comment]
DaNM -Update the powerpad to replace NAV- POLI TEMP with this new script
![image](https://github.com/user-attachments/assets/a19b913a-3ff8-4c63-9452-bbfa7590d37c)

**Comment by C-Love** [comment]
Power pad and redirect files changed on the LAN today to support this script.

**Comment by C-Love** [comment]
Script is done.
