### ISSUE TITLE
MAXIS_Dialog_Navigation function: Add more navigation supports

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#372]
We have only one case based nav supported in this function (CASE CURR). Let's add some more!

Starting with CASE ADHI because we want to use it today, but then adding more as we go. This will be helpful as we move more nav to in-script support vs. power pad. 

With the power pad update recently #113 we've removed most of the NAV scripts off of the power pad. Let's add more in the function to make it more comprehensive:

Panels to add to function:

- [x] CASE ADHI
- [x] MONY INQB
- [x] MONY INQD
- [x] MONY INQX

**Comment by MiKaylaH22** [comment]
it didnt break
