### ISSUE TITLE
BUG - DAIL - MEDI CHECK

### ISSUE THREAD

**Issue by MiKaylaH22** [Hennepin-County/MAXIS-scripts#374]
Information: When running script it only shows *ECF reviewed. *Other:. The entire PEPR message does not show in case notes. Only two lines plus signature. 
Need handling in dialog for checkbox

**Comment by C-Love** [comment]
Possible update to HSR manual on processing these - this DAIL is not included.

**Comment by C-Love** [comment]
Fixed the dialog err_msg logic and fixed some date handling.
