### ISSUE TITLE
New Script - Requesting Claim Adjustment

### ISSUE THREAD

**Issue by MiKaylaH22** [Hennepin-County/MAXIS-scripts#381]
Claims: Underpayments, Adjustments, and Closing
Can I get a BZ script for claim adjustment.  This is a script that we have to case note when a claim was already entered and we need accounting to make a correction on  the claim.

***Requested Claim Adjustment****
Claim number:
Period:
Original Amount:
Correct Amount:
Reason for correction:

Right now, the only script we have out there is the Overpayment script.  If we can add a feature to include a drop down to add this when we need to do a case note to make a claim adjustment/correction, it would be great.  Please let me know.  Thank you.

Use correcting claim errors on sharepoint site

**Comment by IlseFerris** [comment]
Connected with MH (DEU), we've agreed that the CCOL note will be VERY clear that the HSR requesting the adjustment is only requesting the adjustment. Not taking any action in CCOL.

**Comment by MiKaylaH22** [comment]
one thing that may need to be updated on the claim adjustment -- if the claim is mfip the adjustment note will need to provide to AR the mfip program that needs adjustment.  

i know AR will need this information.   Sorry to add more to the claim adjustment note

    Thinking that the mfip adjustment programs could be added in other notes.   Keo was stating something about adding verifications received in other notes.   deu staff must add something about why they are requesting an adjustment.
