### ISSUE TITLE
Health Care - Create CASE:NOTE for Auto Close Cases with closure detail (REVW MONT Closure)

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#388]
Take the old REVW MONT Closure process and reevaluate and merge into our processes.

The idea here is to capture some details FROM MAXIS on cases that will/have autoclosed due to REVW and add it to the CASE:NOTE for quick case understanding.

Effort in Quality CASE NOTES.

This issue is for any case associated with any 6 mo or 12 mo REVW that is not pulled in On Demand- so any review or program that would NOT end up on the REVIEW REPORT.

There are separate issues for:

- All REVIEW REPORT REVW Cases - #387 
- ALL HRFS - #389

**Comment by IlseFerris** [comment]
Changed scope of this issue to Health Cases when HC renewals are back in effect. All other programs on REVW are already accounted for in #387.

**Comment by C-Love** [comment]
The current PHE is set to expire after July 14 2022. If this is not extended HC renewals COULD resume for October 2022. This could be later and if the PHE is extended, it would likely be extended to Mid-October which would mean the renewals would be months after that time. It appears the earliest renewals could happen would be October. Recommend to move this to Q3 as we should know by that time if this work would be needed for cases to be processed in Sept for Oct renewals.

**Comment by C-Love** [comment]
ADDITIONALLY - review functionality in Review Report to ensure that all required steps are in place for HC - tracking, notices, statistics, etc.

**Comment by C-Love** [comment]
Discuss at next meeting - Does the changes to HC review processing change the timing on this issue?

**Comment by C-Love** [comment]
This will not need to be run until 2/1/2024 at the very earliest, rescheduling this for Q1 2024 to be completed in January.

**Comment by C-Love** [comment]
Done!
