### ISSUE TITLE
IV-E Annual Review Note Script

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#39]
Create a script to CASE:NOTE the completion of the IV-E Annual Review.

Request by Brianna Fleeman Schneider on 7/22/19

I’m   wondering if you are able to assist me. Jackie Poidinger and I have been   looking at ways to help IVE be more consistent when they’re processing their   annual review and process holistically. They consistently are not completing   a case note due to the lack of panels being updated during this process and   the fact a notice doesn’t go to the customer. To help resolve this issue, I   would like to have them use a blue zone. This will help their number of   approvals match their blue zones so I have a better overall picture as well.
--

I’m   requesting a blue zone be created for their annual permanency review. The   following is what I was picturing:      Subject: Permanency Review Completed     Court Order Receive Date:      STAT/FCLD Panel Updated? Yes/No. Responded 08/17/19, sent her project   request form.
--

**Comment by IlseFerris** [comment]
This was completed in Dec 2019 by @MiKaylaH22. Closing issue.
