### ISSUE TITLE
Client Contact Dashboard

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#390]
Big project

Include Standard Contact Flow
Create a 'End Result' Flow

**Comment by C-Love** [comment]
IDEA - Interpreter

Have the script pull Y/N and Language from MEMB after the Case Number portion of standard contact flow

This will allow workers to:

- Offer an interpreter if MAXIS is coded as 'Y'
- Remove interpreter Y from MAXIS if resident expresses no ongoing need.

This will improve the standard contact flow and provide more specific service based on known information.

**Comment by C-Love** [comment]
Notes from the DHS Issue List

Request for a couple enhancements to this script:
-Add more options for WHO is being contacted. For instance with EMER requests we are contacting landlords or utility companies.
-Can we put multiple contacts in once case note?
-Possibly increase the field length for the name of the contact.
-Include FACI worker in the dropdown
-Have phone number autofill from ADDR or add formatting to the field for writing into case notes
-Allow the worker to select the interpreter language from a dropdown or have it autofill from MEMB
-Update it so that if the RE field is blank the RE is taken out of the case note
-Add some functionality for EMER contact specific needs.

**Comment by C-Love** [comment]
CiC

**Comment by C-Love** [comment]
Add function created from #37 to find affiliated case in MMIS and a navigate functionality here

**Comment by C-Love** [comment]
Add option to resent or print:
 - Most recent ELIG Notice
 - Most recent Closure Notice
This should require confirmation of the address to send it

**Comment by C-Love** [comment]
CREATE AN MMIS FUNCTIONALITY!!!!

Remove the MHC Client Contact script and have that button redirect to client contact and follow the standard contact flow. make this script be able to identify if this is functioning in MMIS or MAXIS to connect in the right ways and with the right parameters and information. 

This then allows us to close issue #300 because it will incorporate all the updates.

**Comment by C-Love** [comment]
Create functionality from the resources notifier, then access during the course of the client contact script to give other resources to the client. From #53 

This would still have an option for WORD DOC or MEMO

**Comment by C-Love** [comment]
Closed #144 because it will be handled naturally here.

**Comment by C-Love** [comment]
[This is a test of a ONE NOTE Link](onenote:///T:\Eligibility%20Support\Restricted\QI%20-%20Quality%20Improvement\BZ%20scripts%20project\BZ\BZST.one#Team%20Mission/Vision%20Statements&section-id={F5157A95-357B-474F-A9B9-12DF71D5A497}&page-id={7921E7D2-83EB-416D-BB19-2A8698CB9AAC}&end)

**Comment by C-Love** [comment]
This script does not align with policy and process need to update/assess.

**Comment by C-Love** [comment]
IDEA - change the name of the script to - Case Communication

**Comment by IlseFerris** [comment]
Check for AREP, and add phone number from list if AREP is present in phone number list selection.
