### ISSUE TITLE
Enhancements to NOTICES - Method B WCOM

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#391]
There are likely   multiple enhancements needed here. 

The HSR Manual likely need some updates just before or alongside the script updates.

One thing to make sure to include is autofilling of STAT information - particularly BILS

**Comment by IlseFerris** [comment]
Enhancements will be determined as it is being evaluated for integration into ELIG Summary #123

**Comment by IlseFerris** [comment]
Closing issue. Will be addressed in #1783
