### ISSUE TITLE
MTAF Update - Check to Ensure Interview Date is on PROG

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#392]
Need to review the needs of the DWP group to create the best script support for the MTAF process.

**Comment by C-Love** [comment]
This is not a whole review but an update to support functionality. Project Request from RK:

Due to the interview requirements for the MTAF being removed, occasionally incomplete MTAFs are put into pending status for verifications without coding an interview date on PROG.  This results in these cases being pulled into QI’s On-Demand process when they do not need an interview.

Ideally the MTAF Script would check to ensure that the interview date is coded with the same date as the APPL Date (when the MTAF was received) or at least remind the worker to check that PROG is coded correctly.

**Comment by IlseFerris** [comment]
[Link ](https://hennepin.sharepoint.com/:b:/r/teams/QualityImprovement/Shared%20Documents/FW_%20DWP_MTAF%20-%20QI%20Procedure%20Questions.pdf?csf=1&web=1&e=N4gGFj)to supplemental document created by Ryan K.

**Comment by C-Love** [comment]
This appears to be working.
