### ISSUE TITLE
ACTIONS - TRANSFER CASE: Should this case note in all situations?

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#393]
Transferring in-county is an internal process. As we are evaluating case notes and their functions we should review when a transfer is created in a universal caseload model.

**Comment by MiKaylaH22** [comment]
Error reported: "CURRENT FIN RESP CO MUST BE BLANK IF EXCLUDED TIME CASE (Y/N) IS N"

**Comment by MiKaylaH22** [comment]
testing workers reported they prefer the script to open the transfer case use form automatically but for now we are leaving the script as is. Can close per Ilse
