### ISSUE TITLE
SNAP When MFIP Is Closing Supports

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#395]
We 100% need supports for workers as this is a process that is challenging and many times forgotten. Some references for policy, procedures and supports include:

•	HSR Manual: SNAP When MFIP Ends
•	DHS - 4412 MFIP To Food Support Check list
•	POLI TEMP TE02.08.143 SNAP When MFIP is Closed
•	CM0008.06.01 – Implementing Changes – Program Provisions

**Comment by C-Love** [comment]
Handling to include in this issue:

1. Reminder when closing MFIP to pend SNAP OR a NOTE as to why not pended (in NOTES - Eligibility Summary)
2. Be sure to enter interview date for SNAP on PROG when pending (new script functionality)
3. Clear CASE/NOTE of why SNAP is pended - no Application Form (new script functionality)
4. Process steps/CASE NOTE of processing including references to policy and procedure (new script functionality ie NOTES - MFIP to SNAP transition)

**Comment by courtrightd** [comment]
Won't fix, creating a new issue to just look at enhancing elig summary to help with this issue.

**Comment by C-Love** [comment]
Elig Summ work will happen on #1901
