### ISSUE TITLE
Project TBD - Update APP Received to work for RECERT Apps as well

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#398]
The idea here:
Be able to use the script NOTES - APPLICATION RECEIVED to note the receipt of a CAF or other Application that will be used for a Recertification.

The logic would need to be changed for the expedited screening portion and appt letter portions to match the needs of a recertification. 

This would work very well once we have DASH running because we can move the noting of APP received to OS and have them update the CAF Date on REVW only. Then we can know that there is recert work to be done by the existence of a CAF Date but NO Interview date. 

This will also better accommodate apps that are BOTH app and recert.

**Comment by IlseFerris** [comment]
Closing issue. Project TBD has morphed into ES Workflow, and work being done with the Application Foundations project will bring about their own project issues. Project AF is fully aware of this pain point.
