### ISSUE TITLE
Support change reporting and communication Agency Wide (this includes CiC)

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#40]
Case Note script for the Change in Circumstance process. 

Request by Amorette Robeck on 8/9/19

I had an   idea for a BlueZone case note… Change in Circumstance… we are required to use   the CIC form to communicate with METS, but there is no CIC or METS BZ   template.
--

Asked for   template or written procedure:   https://dept.hennepin.us/hsphd/manuals/hsrm/MNsure%20Documents/METS%20Change%20in%20Circumstances%20Form%20and%20Workflow%20Communication.pdf
--

**Comment by C-Love** [comment]
This is a process that we need to support as a part of TBD. This is a big part of the work we need to handle for. 

This would NOT be a NOTES script but a workflow/process that is handled. 

This is actually needed agency wide. CiC is only a part of that.

**Comment by C-Love** [comment]
This will also cover issue #38 
Communicating between E&T and EWS. We will accommodate that with TBD.

**Comment by IlseFerris** [comment]
Closing as won't fix. MJ is the planner working on a project for ES around CIC's and change reporting. We will continue to consult with her group and with the InfoKeep/ES Workflow groups.
