### ISSUE TITLE
New ACTIONS script to help clean up stat

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#408]
This is from the DHS Issue List. https://github.com/MN-Script-Team/DHS-MAXIS-Scripts/issues/2602

A script that will guide a worker through updating and removing STAT panels so that cases are cleaner and easier to work with and update. This can find blanks in required fields of STAT panels and use panel dates and the application dates and panel types to identify panels that need review and possible deletion.

Worker will still make decision, the script would identify potential problematic panels.

We need retention schedule information from DHS. 

This could build incrementally from View PNLP.

**Comment by IlseFerris** [comment]
@C-Love and Knowledge Coordinator met to talk about this and this is going to a 2024 project.
