### ISSUE TITLE
Transfer Script - Embed basket structure to assist with selecting the assignment

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#41]
I think once all the populations   move to having the baskets restructured to the One Hennepin and all that, we   should make a new transfer script. We could have the script define the   rotation that is used and the baskets OR assign randomly OR use times/dates   or whatever each population wants. Users would just access the transfer case   script and select the population and whatever else there may be (specialties,   case status) and we use a list of baskets to do the transferring. That way no   one needs to remember rotations and all that. This also informs that EGA ask   about transferring after completion. This would require a process written,   but I was just reading the Hot Topics and they have that transfer rotation   defined right there.

**Comment by IlseFerris** [comment]
I'm going to bring this to Faughn. There's a possibly that pending case loads is going away, and that pending cases would be a part of ongoing population-based baskets. Random x numbers, round robin, days of the week for certain baskets, etc.

**Comment by C-Love** [comment]
We could also add an indicator to tell if there is outstanding work to be completed by the new population (this would work for internal transfers only). This would create a task reassignment for the next population. Associated with Issue #343

**Comment by C-Love** [comment]
This will be a part of TBD because we will need to reassign and redirect work to the right place.

**Comment by IlseFerris** [comment]
Closing as case assignment rotational process is in flux. Project TBD/Dash would support this process.
