### ISSUE TITLE
NOTES - client contact is used the suggested q flow population - BUG

### ISSUE THREAD

**Issue by MiKaylaH22** [Hennepin-County/MAXIS-scripts#412]
Can someone look into this?  EN7 is the basket assigned for the week to use when transferring cases to adults.  This is an old ADS basket.  When the script for client contact is used the suggested q flow population indicates ADS.  It is resulting in misqued tickets to ADS.  They should be going to ADULTS.

add error_reporting to the script end

**Comment by IlseFerris** [comment]
Tested and working. Closing issue.
