### ISSUE TITLE
NEW Script - PA Verif Request - Evaluate Public Assistance Request Supports

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#413]
The current iteration of NOTICES - PA VERIF does not follow Hennepin County internal procedures for requesting information from a resident or a community business partner (like Public Housing). There are several references in the HSR Manual that reference steps that should be taken when these requests are made. 

- [Public Housing](https://hennepin.sharepoint.com/teams/hs-es-manual/sitepages/Verifying_Public_Housing.aspx)
- [Data Privacy](https://hennepin.sharepoint.com/teams/hs-es-manual/SitePages/Data_Privacy.aspx)
- [Client Requests](https://hennepin.sharepoint.com/teams/hs-es-manual/SitePages/Client_Requests.aspx)
- [Verify Public Housing](https://hennepin.sharepoint.com/teams/hs-es-manual/sitepages/Verifying_Public_Housing.aspx)

**Comment by IlseFerris** [comment]
There are several issues that are closing that while this process is being evaluated. 

- [Issue #411](https://github.com/Hennepin-County/MAXIS-scripts/issues/411) 
- [Issue #386](https://github.com/Hennepin-County/MAXIS-scripts/issues/386): add completed on date
- [Issue #88](https://github.com/Hennepin-County/MAXIS-scripts/issues/88): HH CASH Member Count
- [Issue #85](https://github.com/Hennepin-County/MAXIS-scripts/issues/85): output to letterhead

**Comment by C-Love** [comment]
New procedure detailed!

Need new script to support the procedure. 

Build as a series of functions to best support accessing this from other scripts in the future.

**Comment by C-Love** [comment]
Script is done, tested and released.
