### ISSUE TITLE
FIAT needed for Retro Budget UHFS cases with 3 paychecks in a month

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#421]
Update/New POLI/TEMP (TE02.10.13) indicates FIAT needed for some/all retro budgeted UHFS as ELIG is not reading the retro budget correctly and may be creating inelig/underbudgeted results. 

This might also be a problem for 5 paycheck months as well.

Need a plan of action.

**Comment by C-Love** [comment]
@IlseFerris  to reach out to QI for a possible study on the impact here - need to determine if this is ALL or SOME retro UHFS cases and the work with that is associated in more detail or if the POLI/TEMP reference is comprehensive.

**Comment by courtrightd** [comment]
Won't fix due to limited scope.
