### ISSUE TITLE
NEW script redirect for Applications and Renewals

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#424]
New script that will get rid of the buttons for:
CAF
Interview Completed
CSR
Application Received?

The script functionality will call the other scripts AND add a workflow to get them to the right script functionality.

This will add redirects to functionality for the HUF and handling for the interview waiver in place.

**Comment by C-Love** [comment]
Need a logic map to share with others for approval/feedback.

**Comment by C-Love** [comment]
Include direction on REINNN vs REAPPL for cases that close for review.

**Comment by C-Love** [comment]
I have a folder in OneDrive for this - OneDrive\Projects\Report Workflows - APPL and Renewal. Word Doc and Visio

**Comment by IlseFerris** [comment]
I think issue #570 and this issue can be combined. Thoughts on closing #570?

**Comment by C-Love** [comment]
This issue was more about the HSR process for actually processing a case.

**Comment by C-Love** [comment]
This is being handled in #1010 in a more cohesive way. Closing this issue.
