### ISSUE TITLE
NOTES-RETURNED MAIL update PROG 

### ISSUE THREAD

**Issue by MiKaylaH22** [Hennepin-County/MAXIS-scripts#427]
- [x]  We need to read PROG to determine for CASH cases if the active program is listed on the Cash 1 line or Cash 2 line in PROG because that is the line of the PACT panel that needs to be updated.
- [x]  Update closing message to point users to WCOM supports in NOTICES - ADD WCOM.
- [x] on the pop up box if you enter apt in on the 2nd line it does not populate on the addr panel but it does show up in the case note - i did enter in the unit # manually to make sure all mailings get to HH correctly

**Comment by C-Love** [comment]
We need to read PROG to determine for CASH cases if the active program is listed on the Cash 1 line or Cash 2 line in PROG because that is the line of the PACT panel that needs to be updated.

**Comment by MiKaylaH22** [comment]
to ensure process integrity we will be creating a dialog that asks the worker to confirm that they are entering a pact panel and agree to do so. also add the poli/temp button. review to remove success message 791 and 743 review verbiage

**Comment by IlseFerris** [comment]
@MiKaylaH22 when you're making this update, you won't need to have the local function view_poli_temp in your code. Issue #839 put the function into the FuncLib.

**Comment by MiKaylaH22** [comment]
No issues reported but reviewing usage to ensure all issues are addressed
