### ISSUE TITLE
New WCOM added to Add WCOM for HC PARIS Matches 

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#431]
There is specific verbiage in OneSource - https://www.dhs.state.mn.us/main/idcplg?IdcService=GET_DYNAMIC_CONVERSION&RevisionSelectionMethod=LatestReleased&dDocName=ONESOURCE-COVID10#Other_Changes 

This process has other details - notes, FIAT and actions as well. The WCOM is a quick fix but we might need more support as well.

**Comment by C-Love** [comment]
One of us will take this if we have the opportunity.

**Comment by C-Love** [comment]
Need to review if this is an ongoing policy - or COVID Waiver related.

**Comment by IlseFerris** [comment]
No issues reported. Closing issue.
