### ISSUE TITLE
Enhancing Customer Service Idea - Welcome letter to new cases to Hennepin County

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#436]
When cases are transferred into the ICT basket it would be awesome to send them a memo with the information about contacting us: our offices, phone number/hours and the virtual drop box, etc. 

And maybe some case status or renewal information. 

Some discovery would need to be done to see what the current process is, and who manages the ICT basket. Thoughts?

**Comment by IlseFerris** [comment]
Floated this idea by Faughn and Jennifer today and they love it. They want to assign someone on QI to develop the process in Q3.

**Comment by IlseFerris** [comment]
Additional suggestion from team - Sending this information yearly to keep our existing residents annually to inform them of contact and service delivery options would be a great way to re-envision our service delivery. 

Would need Hennepin County cover letter and to coordinate with ECF/Website workgroup for forms, etc. before moving on this.

**Comment by IlseFerris** [comment]
#436 is being closed to incorporate the idea into this issue. ICT xfer's, new applicants letters, etc. would be a part of this issue.

**Comment by MiKaylaH22** [comment]
T is placing this on the Help Wanted board

**Comment by courtrightd** [comment]
This is being covered by non-script means through application packets. Won't fix.
