### ISSUE TITLE
ACTIONS - Transfer Case - In County Transfers - Move the NOTE to after the XFER confirmed

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#442]
We read to ensure the transfer action was successful, but the script creates the CASE:NOTE before this confirmation so a failed transfer would still get a case note. 

Move the CASE:NOTE to a nested IF statement that indicates the XFER was successful. 
Then leave the NOTE in EDIT mode. 

There MAY be some unintended consequences in this action and we will need to monitor that.

**Comment by MiKaylaH22** [comment]
Because we are unable to move the transfer to AFTER the case note this issue is a wont fix but we have done our best to ensure that the script will notify the worker if the case is not transferred.

**Comment by MiKaylaH22** [comment]
Closing as #393 remains open for testing
