### ISSUE TITLE
Hot Topic Power Pad Button to Open a list of BZST Hot Topics

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#452]
We publish information about our scripts in Hot Topics and have space in the CLOS to save the dates and URLs for Hot Topics by script.

This script project would:
1. Create a dialog that uses the CLOS to have a dynamic display of all of the scripts information and Buttons to open a link to each article. 
2. Have the dialog still have a link to the main Hot Topic Page

We will also need to review all the Hot Topic articles for BZST and update CLOS to put in our Hot Topic article history.

**Comment by IlseFerris** [comment]
Update: 

- [ ] Phase One: Link to the BZ SharePoint Page, change button name to reference BZ Hot Topics
- [ ] Phase Two: 
    - Create a dialog that uses the CLOS to have a dynamic display of all of the scripts information and Buttons to open a link to each article.
    - Focus on ONLY BlueZone Script articles.

**Comment by IlseFerris** [comment]
Phase 1 is complete.

**Comment by IlseFerris** [comment]
Added announcement, closing issue.
