### ISSUE TITLE
Update Complete List of Testers

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#454]
Since setting up the complete list of testers there have been some changes to how we set up our workforce that the testers list will now need to account for. We will evaluate this further in the near future, but for now we know that the following needs to be updated: 

- [x] Regional offices are no longer a categorization of our work
- [x] Supervisor changes for many HSR's

**Comment by C-Love** [comment]
This issue requires that we changes some of the tester class paramenters

We will also need every tester to reconfirm their tester information. We will need to tell testers this is coming. 

Need to know when the shake out has settled a little for restructure.

**Comment by C-Love** [comment]
Do this in June.

**Comment by C-Love** [comment]
This is currently active as testers respond.

**Comment by C-Love** [comment]
Tester confirmations completed

No work remaining - testing not required
