### ISSUE TITLE
Create a FAVORITES script

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#46]
New script access/menu that users can identify the scripts they use most to have a personalized menu.

**Comment by C-Love** [comment]
Should we move this out to everyone to try it out?

**Comment by C-Love** [comment]
Bug reported. Exception Error started to happen. I've added some new dialog redefinition. Maybe that will help!

**Comment by C-Love** [comment]
Plan to deploy this to everyone once the the Exception error is hopefully resolved. 

Goal - release by 7/31/2020 pending the IT support and resolution.

**Comment by IlseFerris** [comment]
NAV scripts for to add to favorites. User asked today about the DAIL/WRIT script.
