### ISSUE TITLE
ACTIONS - Transfer Case - Restrict transfer of cases to CCL with the script

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#466]
There is a batch process to correctly transfer cases to CCL at the appropriate time. Workers should NOT be transferring cases on an individual case basis. 

https://hennepin.sharepoint.com/teams/hs-es-manual/SitePages/Closing_Case_Records.aspx

This is manual reference to support this.

Update the script to prevent transfer to x127CCL with messaging to the worker that these transfers should not be happening.

**Comment by MiKaylaH22** [comment]
Closing as #393 remains open for testing
