### ISSUE TITLE
Script to 'enroll' in Script Demos hosted on TEAMS

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#47]
We will be hosting script demos virtually to show script functionality and updates. These demos will happen in TEAMs.

We will have a script that will allow users to be aware of demos available and enroll in them. 

1. Add the demo time to Outlook calendar with the meeting link in the description
2. Send an email to the BZST to alert us to planned attendance.

**Comment by C-Love** [comment]
@IlseFerris - I think this is mostly done. Do we want to just put this out? I would have to add the functionality to say 'We don't have any scheduled - click here to suggest one!' Or should we wait until we have one to put out?

**Comment by IlseFerris** [comment]
@C-Love I'd be fine rolling this one out sooner if it's nearly ready. Would this go into UTILITIES until the new power pad update goes live?

**Comment by C-Love** [comment]
@IlseFerris I am good with and/ or. It will get a special button in TAGS.

We could just create the script and keep in buried in UTILITIES since we don't have any to promote. Then once we have some, it is an easy thing to add the button to the power pad. 

We could also just start with having them both out there - the UTILITIES button (and in the TAGS menu) and a Power Pad button. This issue is only to create the script, so I will be able to close it even if it doesn't have a special spot on the Power Pad. 

I will move this to Q3 and finish the script then we can make Power Pad decisions later. 

Connects to issue #113

**Comment by C-Love** [comment]
This is released - no real announcement at this time. Working on the power pad and all the new redirects.

**Comment by C-Love** [comment]
Need instructions still. 

Will start communication around the new Power Pad and include information about this functionality in it. There is no separate Hot Topic needed for this individually.

**Comment by C-Love** [comment]
Instructions are completed and Script is released.
