### ISSUE TITLE
DAIL- SCRUBBER - navigation to ensure we are in production

### ISSUE THREAD

**Issue by MiKaylaH22** [Hennepin-County/MAXIS-scripts#476]
Add navigate DAIL/WRIT to ensure worker is not in INQUIRY
- [ ] CATCH ALL
- [ ] CITIZEN VERIF
- [ ] COLA REVIEW & APP
- [ ] CSES SCRUBBER
- [ ] DISA MSG
- [ ] ES REF MISSING
- [ ] FIN ORIENTATION MISSING
- [ ] FMED DEDUCTION
- [ ] INCACERATION
- [ ] LTC REMEDIAL CARE
- [ ] MEDI CHECK
- [ ] NDNH
- [ ] NEW HIRE
- [ ] OVERDUE BABY
- [ ] PAPERERLESS DAIL
- [ ] POSTPONED EXP

**Comment by IlseFerris** [comment]
Idea - update DAIL SCRUBBER with in_inquiry = true/false, then update the DAIL SCRUBBER to continue or script end depending on the process.

**Comment by C-Love** [comment]
Functionality in place and testing well. Next step is to assess each DAIL Scrubber individual script to script_end_procedure where appropriate. Good for little issues day.

**Comment by C-Love** [comment]
this appears to be working without being noticed.
