### ISSUE TITLE
Review ALL Dialog titles for more detail about what is happening/which script is running

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#486]
We have a lot of generic dialog titles... or they just say 'Dialog' 

It would be good to have some detail in these dialogs. 
This is very true for the first 'Case Number' Dialog - also screen shots would be more helpful because we would know WHICH SCRIPT. 

This is also relevant in #125 to create a function to start the script - we want the script name in the dialog.

**Comment by IlseFerris** [comment]
#125 will support new scripts (get this script started function). To complete this issue CLOSING ISSUE DOCUMENTATION will be updated to include checking the dialog name for information and space.
