### ISSUE TITLE
Add functionality to include 'was this reported timely' to scripts as appropriate for CASE NOTING

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#495]
We should be documenting if information that is reported as an 'unscheduled reporting of change' or other 'non report' reporting. 

This requires that we have a single HSR Manual page with redirects to policy for all of the different programs, reporting types, and program statuses so that we can provide direction to support for this field on scripts. 

We would then create functionality to add a question to dialogs where these reports might be recorded:

- Text - Was this reported timely?
- DropListBox - Yes or No 
- PushButton - Open the HSR Manual Page with all of the redirects/links listed above. 

This would then CASE:NOTE the detail entered.

Need the support in HSR manual first. 
Need discovery of which scripts this belongs in.

**Comment by IlseFerris** [comment]
#390 and #425 - This work makes the most sense when these are also released. Coordinate this work.
