### ISSUE TITLE
Add MNBenefits information to Appointment Letter/NOMI/Informational Notices

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#501]
For September renewals, ES Leadership members are requesting MNBenefit renewal forms and proofs submission. 

This will also likely be added to appointment letters and NOMI's for applications too, but I'll need to check with the sponsors before that goes out.

**Comment by C-Love** [comment]
Testing completed for Renewal notices. 

Next step will be to update Application process scripts at the end of this month.

**Comment by C-Love** [comment]
Do we need NEW notice examples?

**Comment by C-Love** [comment]
Notices updated. We are not creating new notice examples at this time.
