### ISSUE TITLE
Function add sort_date to FuncLib

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#527]
Add to Funclib, remove from individual scripts. 

- [x] FuncLib add
- [x] Remove from misc/hss-maxis-facility-report.vbs
- [x] Remove from misc/hss-service-authorization-update.vbs
- [x] Remove from notices/pa-verif-request.vbs
- [x] Remove from actions/earned-income-budgeting.vbs

**Comment by C-Love** [comment]
These are all still working - function is now global.
