### ISSUE TITLE
Script Idea: Submission of Internal Resources support

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#53]
From user Amorette Robeck:

I had an idea for a possible BZ script.
We now have to submit all requests for a navigator/BNA assessment/CMA (not sure what they are calling it these days) with useform (CAP form).
I couldn’t find a BZ script to support my action, so I made my own.
Is it possible to get a navigator requested BZ script?

[Link](https://dept.hennepin.us/hsphd/manuals/hsrm/_layouts/15/listform.aspx?PageType=4&ListId=%7BE6A91629%2D26B2%2D4977%2DB1EB%2DE8899E5C341D%7D&ID=68&ContentTypeID=0x01040024E6E2B60E37CA43AD043B8F7C452615
) to Announcement re: procedure: 
Unable to find other procedure in HSR manual to date. 

Possible script support: add check box to case note referral/use form was made. Add link to useform(s) in user dialog to the following scripts: 

- NOTICES - RESOURCES NOTIFIER

- NOTES - CLIENT CONTACT

- NOTES - Interview

**Comment by MiKaylaH22** [comment]
Idea create a button for a useform and handling for submitting the useform casenote

**Comment by C-Love** [comment]
@MiKaylaH22 - you mean in RESOURCES NOTIFIER? We could update the functionality of that script to allow for ONLY useform information as well, currently it HAS to send a notice but if all that is happening is the Useform, a notice doesn't need to go.

OR would we WANT clients to get an alert that we referred them to additional resources?

**Comment by IlseFerris** [comment]
Per our weekly issues and projects meeting discussion @IlseFerris will reach out to worker to ask what the trigger point is for this action.

**Comment by IlseFerris** [comment]
Per the team's discussion, this would be a function that is build to easily be added into any script we would need it for. Will ask QI for trigger points and provide details as we are working on issue #390

**Comment by C-Love** [comment]
The procedure around the requirement for these BNA/Navigator requests do not have enough clarity to provide script support. We cannot update any area of the script project for this. Closing this as a 'Wont Fix'
