### ISSUE TITLE
NOTES OVERPAYMENT/DEU OP - retire DEU OP script and merge to notes OP 

### ISSUE THREAD

**Issue by MiKaylaH22** [Hennepin-County/MAXIS-scripts#536]
- [ ] Retire DEU OP and write the script to recognize DEU via worker number to do the additional handling in IEVP 

- [ ] update the dialog to gather the claim number - Instead of the worker entering the information recreate the dialog to just pull in the claim number and read from CCOL also ensure the claim has been fully entered and the worker has exited. The HC portion will remain.

- [ ] The script output the ‘Case Number’ in the report – which is what it is supposed to do. However in this case the number is actually associated with the CLAIM that the worker wanted to enter the note/information about. Perhaps there is some handling/verbiage we could update on this. 

- [ ] Add handling to ensure we transferred to correct basket - Ensure that the  worker has been updated to X127720

**Comment by C-Love** [comment]
This might be a larger issue/project. We had a huge conversation around this. 

A couple highlights:

- We need more supports around claim entry - really enhanced supports. 
- There is also the issue of the claim discovery tracking.
- Larger issues around the overpayment computation and documentation

We are not going to work actively on this right now. We are going to do some skill building and discovery on the best operation of this that we can. 

Fix Claim Entry and save the world.

**Comment by IlseFerris** [comment]
Talk about lessons learned/discovery from auto-close pause tier 2.

**Comment by C-Love** [comment]
This is resolved with a redirect. Notes updated and the button is still in the DEU menu for now.
