### ISSUE TITLE
Create a 'kill-switch' to wipe the replacable data from On Demand Applications

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#545]
This will be functionality available to BZT users that can erase the dates and action data stored in the Working Excel for On Demand Applications. Then the On Demand Script can be run again to refill the information and ensure it is of the best quality. This second run will take time.

New Script for the BZ Area of Admin. 

This will:

- Remove dates 
- Remove Next Action Needed
- Remove formatting
- Remove specialized info columns
- LEAVE NOTES ?
- LEAVE EMAIL DETAILS

There is no interaction with MAXIS needed here.

**Comment by IlseFerris** [comment]
Closing as won't fix. On Demand Next Gen makes this unnecessary.
