### ISSUE TITLE
ADMIN - On Demand Applications - enhance the 'red' formatting

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#546]
We use the red font formatting to identify cases that need work done when the On Demand Applications script completes it's run. 

This is currently put in place for deny at day 30 cases and cases that indicate in the notes to 'process manually'.

Updates:

- [x] Reset the format of all the rows at the initial read so that red isn't carrying over
- [x] Format as Red Text all Deny at Day 30/ or Review Denial cases
- [x] Review the 'Next Action' information to determine which actions should get red formatting
- [x] Assess other cases/information on the excel to determine if there are other situations that require attention
- [x] Review all the 'Comments' and what information is being added. Ensure information/verbiage is not duplicated.

The goal is for all the cases that need manual work/review to be formatted as red and ONLY those cases to be formatted as red so that this formatting is value added for QI.

**Comment by IlseFerris** [comment]
No script issues reported by QI users. Closing issue.
