### ISSUE TITLE
FUNC LIB Correct HH member function 

### ISSUE THREAD

**Issue by MiKaylaH22** [Hennepin-County/MAXIS-scripts#552]
DIM all_client_array()
ReDim all_clients_array(total_clients, 1) remove S 

additionally can we look at reading all information from MEMB

**Comment by IlseFerris** [comment]
We will be addressing this when we are rebuilding the project in association with a language update.

**Comment by IlseFerris** [comment]
Enhance function to allow user to select additional criteria to custom the array information, including weather or not the boxes are checked or unchecked.
