### ISSUE TITLE
FUNCTION - Resources Notifier - error/err msg when selecting ONLY Virtual Dropbox

### ISSUE THREAD

**Issue by MiKaylaH22** [Hennepin-County/MAXIS-scripts#557]
Script name - ACTIONS - INTERVIEW.vbs was run on Case #XXX with a runtime of 1596.969 seconds. 
Information: I tried sending the email/virtual dropbox info to clt and the script kept giving me an error. This is the first time I tried sending just that without any other resources, it's always worked with multiple selections.

The error said something like “Select Resource or Check None” and even though I selected the email/virtual dropbox option it kept popping up that message. I gave the clt the info verbally while trying several times so finally just hit none so that we could move on.

**Comment by C-Love** [comment]
This is an issue with the Function for the resources notifier and will need to be resolved in the FuncLib.

**Comment by C-Love** [comment]
This is working now. Bug squashed
