### ISSUE TITLE
New Script: Request Access to Priv Case

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#56]
We need a process detailed about what to do with Priv Cases and then we can create a tool.

We can also add a transfer tool for the transfer worker to use and make the updates using a secondary worker.

Ilse to talk to Faughn about creating a workgroup to do discovery on this. 

![image](https://user-images.githubusercontent.com/13418322/84526572-32ca8000-aca3-11ea-88a1-84b34b7b6d72.png)

**Comment by IlseFerris** [comment]
Jennifer F/QI is working on the PRIV case support written process.

**Comment by C-Love** [comment]
As is process has been received. Need to review and discuss

**Comment by C-Love** [comment]
This should be prioritized. 

We need to create a logic map and approval by Jen/Faughn.

**Comment by C-Love** [comment]
Process documents have been created and need approval and implementation. 
These are saved in my One Drive under the Project folders.

**Comment by C-Love** [comment]
This script has been created and released and available to all staff. 

There is an outstanding issue of potentially updating the current process for PRIV requests to align more with an automation that we could create. This process has to be reviewed and adopted  before any additional development in this script can take place. 

With the new Task Based process, this may be able to be a part of the Task Based reassignment. 

Closing this issue as this is done for now and we can create a new issue if any enhancement can be added.
