### ISSUE TITLE
NOTES - Interview - Add handling for completing a 'Phone CAF' 

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#561]
If we are completing a CAF form for a resident at the same time as an interview, can we accommodate the PHONE CAF functionality within the Interview script. This will build off the base questions and process flow in #62.

**Comment by C-Love** [comment]
This needs to wait for actual procedure on the ONGOING Phone CAF policy in Cash programs.

**Comment by IlseFerris** [comment]
Closing as a won't fix. This procedural issue is not about the interview so supports will not be built into the interview script. #562 has supports for these situations.
