### ISSUE TITLE
NOTES - Interview - Add handling for cases with APP that HAVE NOT BEEN PENDED YET

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#562]
If we are requesting pending, but have the resident for an Interview, can we indicate that MAXIS isn't pended and 'hold' the information until it has been pended, then utilize the 'save your work' to dump it all into the right place. Basically run the script in stages. 

This will be two variations on the same process - one for Applications that does NOT update MAXIS/ECF and one for Renewals that CAN update MAXIS/ECF. 

Connected to #62. 

When this is completed - we will need to update the HSR manual for process instructions for Application and Renewals in directing workers to complete the interview without the form and save until form is received/on file.

**Comment by C-Love** [comment]
Need process for CA and HSRs on how to work these cases.

**Comment by courtrightd** [comment]
This is less of an issue after the end of the PHE, and implementation would require changes in HSRs APPLing or potential other changes. Won't fix for now.
