### ISSUE TITLE
UTILITIES - QI AVS REQUEST - add the date stamp the avs form was received

### ISSUE THREAD

**Issue by MiKaylaH22** [Hennepin-County/MAXIS-scripts#574]
Request:  add the date the avs form was received to the request

Reason: we have new apps after denials but no new avs form and people don't look at that before sending the request

**Comment by IlseFerris** [comment]
Also remove CHANGE IN BASIS as an option in the APPL_TYPE drop list. A change in basis is a new application in the legacy system. This aligns with what's in the AVS system, and NOTES - AVS script.

**Comment by IlseFerris** [comment]
Tested and working. Closing issue.
