### ISSUE TITLE
Develop a script to submit a script idea or enhancement

### ISSUE THREAD

**Issue by MiKaylaH22** [Hennepin-County/MAXIS-scripts#58]
create canned response for non script instance

**Comment by C-Love** [comment]
Connected to power pad redesign Issue #113 

Casey will create a script that will allow users to report out to BZST about issues an errors WITHOUT having to get to script_end_procedure to use a script to report. 

This will report errors, ideas, enhancements, bugs, typos, anything. 

If these emails generate information about larger projects, we can respond to the emails with the Project request form.

Once the script is done - MiKayla will create canned responses for our BZST one note with the same verbiage so we can gather similar detail from other emails that come to us.

**Comment by C-Love** [comment]
This is available now to all users. Flagging it as 'In Testing' so that we can track it for a week or so to see if there are any specific errors or issues. Made task item to close issue next week if no errors are reported with the script.

**Comment by C-Love** [comment]
This has been created and is available. Work completed - closing issue.
