### ISSUE TITLE
Rewrite NOTES - CSR to follow form/process

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#59]
The current version of the CSR script does not provide adequate level of detail or case actions. 

The script should follow the form and the process for completing the form.

**Comment by C-Love** [comment]
Recommended updates:

1. Fix the workflow to have fewer steps - merge the yes/no and field dialogs. 
2. Add some information about why we ask all the questions and what we are doing.
3. Add some support/detail about phone completed forms and phone signatures.

**Comment by C-Love** [comment]
Testing responses and updates to make:

1. Align the Yes/No/Did not answer with the details/left blank part for each question so each question only has to be reviewed once.
2. Check the functionality of the 'Next' Button and the err_msg handling.
3. Add detail about verbal date/signature to the signature dialog.
4. Explain why we ask all the questions even if only SNAP or HC case.
5. Question 19 is only required if the case has an ABAWD
6. Review the second phase - not a lot of detail around the second phase of the script yet.

**Comment by C-Love** [comment]
Added some updates based on responses. Will make a new demo video.

**Comment by C-Love** [comment]
This script needs an updated process and policy. We need to change our understanding of how a CSR is supposed to be processed. Once this shift happens, the script will make more sense and provide more efficiency and support.

**Comment by C-Love** [comment]
Discussed with testers and with all changes happening and current processes they agree suspending testing might be the best course of action. 

Secondarily - we need to provide some really clear written direction/process on CSRs.

**Comment by C-Love** [comment]
We have stopped testing at this time. 
I am moving this out of Q4 since we will not be able to complete this project in this quarter.

**Comment by IlseFerris** [comment]
[Combined Six-Month Report Forms Resuming](https://www.dhssir.cty.dhs.state.mn.us/MAXIS/Lists/MAXIS%20Announcements/DispForm.aspx?ID=7491&RootFolder=%2FMAXIS%2FLists%2FMAXIS%20Announcements&Source=https%3A%2F%2Fwww%2Edhssir%2Ecty%2Edhs%2Estate%2Emn%2Eus%2FPages%2FDefault%2Easpx). This was initially reported by DHS as starting Jan for March 2022, but now will be Feb for April 2022 processing.

**Comment by C-Love** [comment]
Ideas for updates/ resuming work on CSR updates:

1. Align the dialog sizes to match the interview - make it more like a dashboard.
2. It appears the CSR form has not been changed - confirm this is the form that was sent (5576)
3. Possible - update the script to have PANEL information in-line with the form questions and a method for the worker to indicate the information is either: 'update with script'/'panel manually updated'/'no change - no update needed'. This would be for the MAIN panels (ADDR, HEST, SHEL, JOBS, ACCT, UNEA, others?)
4. Move the form review detail to an access point from a larger dashboard.

Need to review this in more detail and make a plan for updating this script.

**Comment by C-Love** [comment]
Much of the work on developing this work and script functionality. There was limited testing. This functionality needs to be incorporated into a larger effort/workflow. #1010
