### ISSUE TITLE
FUNCLIB Bug - soonest working day doesn't check for today

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#594]
When using the soonest _working_day function it might pop back the current date (or even could be a past date... 

so that needs to be resolved.

Add a to the function to be able to chose if we go forward or backward.

**Comment by C-Love** [comment]
Scrips to update the function call:

- [ ] Update Function
- [ ] ADMIN - Individual Appt Letter
- [ ] ADMIN - Expedited Review
- [ ] ADMIN - Task Based Assistor
- [ ] NOTES - Interview No Show
- [ ] ACTIONS - PF11 Actions
- [ ] NOTES - IMIG Status
- [ ] NOTES - Application Received
- [ ] ADMIN - On Demand Waiver Applications

**Comment by C-Love** [comment]
@IlseFerris The change for the function is in place in MASTER and pulled in. Please update Expedited Review when you pull in to Master.

**Comment by IlseFerris** [comment]
@C-Love Done and done!

**Comment by C-Love** [comment]
Tested and working - we didn't break the world.
