### ISSUE TITLE
October/Fall 2021 Changes to Scripts and Functions

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#611]
Hey it's Mass Change time! There are a set of updates that occur for 10/01 each year. Here are the tasks to be completed for October 2021 changes:
- [x] NOTES - SPONSOR INCOME - update 130% of FPG
- [x] Provide NOTES - SPONSOR INCOME to TRIC and MN-Script-Team
- [x] Provide NOTES - EXPEDITED SCREENING to TRIC and MN-Script-Team
- [x] MHC - ENROLLMENT - Capitation date for the next year & Enrollment Plans
- [x] MISC - Health Care Information Report: Enrollment plan (Review health plan codes in [MMIS User Manual](https://www.dhs.state.mn.us/main/idcplg?IdcService=GET_DYNAMIC_CONVERSION&RevisionSelectionMethod=LatestReleased&dDocName=ID_001563l))
- [x] ADMIN - BUDGET ESTIMATOR: pulling out of Complete List of scripts. Will be putting functionality into the Interview supports. 
- [x] Constants from FuncLib: income_test_SNAP_catergorically_elig
- [x] Constants from FuncLib: income_test_SNAP_gross
- [x] Constants from FuncLib: income_test_SNAP_net

HEST/Standard Utility Allowance (SUA) work is out of the scope. See issue #553 for details of that work. 
Normally ACTIONS - PF11 would be updated with 275% FPG for the NSI policy, but this will be removed as PF11 is no longer needed for NSI process. See issue #530.

**Comment by C-Love** [comment]
Health Plans updated. No capitation dates yet.

**Comment by C-Love** [comment]
DONE! Housekeeping resolved... for now.
