### ISSUE TITLE
Adding InfoKeep Information to Script Supported Notices/Memos

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#612]
Awareness has been created with Mary M, business project lead, that adding InfoKeep information to notices has been requested. More information to come. See issue #52 for details of adding virtual options for notices for residents.

**Comment by C-Love** [comment]
Confirmation of verbiage created for APPT NOTC and NOMI requested from MM and MD. Once received we can start this work. Email sent today 5/4/22.

**Comment by C-Love** [comment]
Verbiage confirmed by MM.

**Comment by IlseFerris** [comment]
ADMIN - DAIL 12 MONTH CONTACT and NOTICES - 12 MONTH CONTACT scripts still have the virtual drop box as the only digital options on those notices. Updating these notices with this work would be ideal.

**Comment by C-Love** [comment]
Scripts with the virtual dropbox in a MEMO or WCOM:

- [ ] DAIL - FMED Deduction
- [ ] DAIL - Overdue Baby
- [ ] NOTICES - Add WCOM
- [ ] NOTES - Denied Programs
- [ ] NOTICES - Eligibility Notifier
- [ ] NOTICES - Verification Still Needed
- [ ] ADMIN - DAIL 12 Month Contact 
- [ ] ACTIONS - Job Change Reported
- [ ] NOTICES - 12 Month Contact
- [ ] ADMIN - On Demand Waiver Applications
- [ ] ADMIN - DAIL FMED Deduction
- [ ] MASTER FUNCTIONS LIBRARY - function - provide_resources_information

**Comment by C-Love** [comment]
This is done, no errors reported.
