### ISSUE TITLE
Audit claim-based scripts for CASE:NOTE guidance provided by DHS

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#616]
DEU Supervisor provided training from DHS re: claims training (Claims 101) This training provided specific guidance on what claim notes should contain and what Claim Referral Tracking notes should claim. The following scripts will need to be audited to ensure that CASE:NOTE guidelines are being supported. 

Scripts to audit for claim and/or claim referral tracking notes:
- [x] ACTIONS - CLAIM REFERRAL TRACKING
- [x] DAIL - NEW HIRE
- [x] DAIL - NEW HIRE NDNH
- [x] DEU - ATR RECEIVED
- [x] DEU - MATCH CLEARED
- [x] DEU - OVERPAYMENT CLAIM ENTERED
- [x] DEU - PARIS MATCH CLEARED CC CLAIM ENTERED
- [x] NOTES - OVERPAYMENT

List of procedural references
- TE02.09.07 Claim entry initiates transaction
- TE02.09.47 Claim referral tracking
- TE02.09.02 Case and Person based CLRA
- TE02.09.05 Correct mistake on a claim already entered
- Te02.09.00 Demand Letters for Overpayment
- TE02.08.095 CASE NOTE III: Claims/Systems/Transfers

**Comment by MiKaylaH22** [comment]
Scripts reviewed - ALL will need to be updated to align with current case note requirements

**Comment by MiKaylaH22** [comment]
Created issue #687 after reviewing all scripts for case note compliance, scripts meet DHS requirements and will all have upcoming enhancements.

**Comment by MiKaylaH22** [comment]
Each script has been reviewed and needs to have a setup in place for the new claim referral tracking function
ACTIONS - CLAIM REFERRAL TRACKING
DAIL - NEW HIRE
DAIL - NEW HIRE NDNH - no claim referral tracking built in
DEU - ATR RECEIVED
DEU - MATCH CLEARED
DEU - OVERPAYMENT CLAIM ENTERED
DEU - PARIS MATCH CLEARED CC CLAIM ENTERED
NOTES - OVERPAYMENT
