### ISSUE TITLE
Project Time Bandit - BZST Time Tracking via scripts

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#622]
Lets make our time tracking an annual thing and updated/viewed via scripts!

**Comment by C-Love** [comment]
Add  + and - button to switch dates in Hours Report..

**Comment by C-Love** [comment]
Adding discovery on  functionality to support time off tracking.

**Comment by MiKaylaH22** [comment]
my requests for time off are not being received by our HSS. I am getting the success messages and have confirmed I am on the master branch

**Comment by C-Love** [comment]
This functionality isn't done - iI am not surprised it isn't working fully. We will need to set up a time for functionality review and testing.

**Comment by C-Love** [comment]
New plan - turn off the access to the start of the request time off functionality and complete/close this issue.

**Comment by C-Love** [comment]
Add functionality to futurize the date creations within the script so that we don't have to hard code change for dates.

**Comment by C-Love** [comment]
This is DONE!
