### ISSUE TITLE
QI Script to Report Out for an assignment

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#63]
In order to track work done in daily or weekly assignment in QI we need a way to create a report of work completed. The easiest way to do this is to create a script, this way the information reported out can be added to:

1. A Word Document Report
2. An Excel Spreadsheet to track the trends in the work
3. Email

This will be able to get us data on the work being completed

**Comment by C-Love** [comment]
Potentially add a count for EXP SNAP to know how many cases have called in to request an interview and have not completed one.

**Comment by C-Love** [comment]
Remove DAY THIRTY Option

**Comment by C-Love** [comment]
We are asking Jen if she wants this currently for the regular On Demand assignment as well. 

If she does, I will work on this with this issue. If she does NOT want this at this time, we will complete and close this issue and would just make a new issue in the future if she decides she wants it.

**Comment by IlseFerris** [comment]
Affirmative, Jennifer does not want the this reporting at this time. @C-Love feel free to close the issue.

**Comment by MiKaylaH22** [comment]
Why can I see all of this!!~

**Comment by C-Love** [comment]
Removed the Day 30 Option.
Jen does not want regular On Demand to have an option at this time.
No additional work needed. Testing done.
