### ISSUE TITLE
NOTES - Interview adding detail about Work Number and Authorization

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#632]
Request to add an indicator about Work Number for jobs.

- Is the job on Work Number
- Gather verbal authorization information 
- Request written authorization
- Create separate CASE:NOTE with this detail

Also maybe somewhere else?

**Comment by IlseFerris** [comment]
#305 - this is an associated issue. Consideration for a function for verbal and/or documented releases should be evaluated for these issues.

**Comment by C-Love** [comment]
https://hennepin.sharepoint.com/teams/hs-es-manual/SitePages/The-Work-Number.aspx

This is ready. Plan:
 - Add questions to the Interview Script to ask the resident if they authorize the Work Number and if they Authorize it ongoing for monthly reports.
 - Create a separate CASE/NOTE if Authorization is YES.
 - Maybe make this a function and available in client contact?

**Comment by C-Love** [comment]
Meeting today with JA and KS to confirm script functionality details. 

This functionality should be available in:
 - Interview
 - Client Contact 
 - Stand Alone Script

When accessed within another script, there will be a button to detail Work Number Authorization that will open the dialog. 

The function will have its own dialog to detail the authorization to check the Work Number, it will also create a separate note for EACH job authorized. 

Mock Ups and additional details in OneDrive Project folder.

**Comment by C-Love** [comment]
DaNM - Recommend won't fix - https://hennepin.sharepoint.com/teams/hs-es-manual/SitePages/The-Work-Number.aspx

**Comment by C-Love** [comment]
Won't fix as this does not align with worker direction.
