### ISSUE TITLE
CSES - INFC interface - create new script 

### ISSUE THREAD

**Issue by MiKaylaH22** [Hennepin-County/MAXIS-scripts#64]
CSES MM YY MM/DD/YY REFERRAL/AB PARENT #xxxxxxx: COMPLETE INFC PANELS 
This message occurs when a new ABPS panel has been added to a case and MFIP benefits have been approved prior to INFC/CSIA-B-C-D panels being completed.
Action needed/Time frame: Complete the INFC series of panels immediately in order to prevent PRISM from establishing duplicate IV-D cases. 
this script will support both the work being done at approval and in the DAIL scrubber but will direct line navigate to INFC/CSI panels.

**Comment by C-Love** [comment]
Referrals to Supports and Collections – i.e. it has been received and data entered?  Not really update panels – 
In my mind – the blue zone case note would say 
Referral to support and collections received – yes
Date received
CSIA – CSID panels updated  - yes / no  
Who does it pertain to – father / mother / both
Brief recap of what was entered – i.e. job/address/phone #

**Comment by IlseFerris** [comment]
Closing as a won't fix. Will create another issue to create a function.
