### ISSUE TITLE
UTILITIES - UC VERIFICATION REQUEST - Updates to the dropdown and dialog

### ISSUE THREAD

**Issue by MiKaylaH22** [Hennepin-County/MAXIS-scripts#644]
Previous issue #187  - I have shared the scrip info with the  ES- supervisors and they already asking me about the script. I have noticed that  HSPH.ES.DEED@hennepin.us option is not included in the dropdown and Central/NE and South need to be removed.  Also we will be adding the NW team to the DEED email starting next week and it needs to be removed afterwards.

**Comment by IlseFerris** [comment]
Closing issue. Work complete.
