### ISSUE TITLE
NOTES - Application Received - Add new NOTC to alert to picking up a EBT Card

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#662]
Have the script check MONY/DISB for when SNAP or Cash are pending and if there is no card indicated on MONY/DISB then send a second notice alerting the resident:

''It appears you may not have ever received an EBT card. If this is true, you can come in right away and get a card before your benefit request has been processed. This will make it quicker to access any future approval"  - need more words and approval of the words.

**Comment by MiKaylaH22** [comment]
Figure out what this notice might say
Determine what we might give them
