### ISSUE TITLE
FUNCTION - Add 130% FPG references to a bunch of scripts and places

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#665]
Add a button to the PowerPad
Add to Client Contact
Add to Interview

  - What is 130% FPG by HH Size - based on entry by the worker (EditBox)
  - What is the 130% FPG for a specific case - case number editbox

**Comment by IlseFerris** [comment]
CM reference for 130% FPG: https://www.dhs.state.mn.us/main/idcplg?IdcService=GET_DYNAMIC_CONVERSION&RevisionSelectionMethod=LatestReleased&dDocName=CM_001906. This updates every October 1.

**Comment by C-Love** [comment]
This work has shifted. A function was created during work on #123 and this function can be moved to FuncLib and closed. This function is determine_130_percent_of_FPG. Once available in FuncLib, it can be added to any script.

**Comment by C-Love** [comment]
this function is now available and ready. No errors report
