### ISSUE TITLE
Docs Received - Special Diet Form

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#67]
Script for handling special diets for MSA cases. Additional detail/documentation provided.

**Comment by C-Love** [comment]
This looks like a duplicate to me - ISSUE #36 is about MSA Eligibility and should probably include special diets. 

@IlseFerris @MiKaylaH22 should we label this as duplicate and close this issue?

**Comment by C-Love** [comment]
This is NOT at eligibility determination - but at receipt of the Special Diet FORM. 
Add to Docs Received. 
Look until PROJECTS > Special Diets for a start on this.

**Comment by C-Love** [comment]
For MFIP - this may need to make a PERSON NOTE to validate the processing of MONY/CHCK in the BULK way.
Connected  to Issue #29
