### ISSUE TITLE
UTILITIES Menu is too large and is causing a Program Exception Error

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#675]
The symptom is showing up in UC Verification Request.

Too many buttons, adding a new dialog with a different variable designation is causing the overload. 

We need to update the menu to NOT have so many items.

**Comment by IlseFerris** [comment]
Review the category buttons (TOOL, POLICY, MAXIS). Have the top tools that are not on the power pad directly on the 1st/main page which include the following scripts: 
- Calculate rate 2 units
- Display benefits
- Insert MBI from MMIS
- POLI TEMP to Word
- Search Case Notes
- UC Verification Request
- Update Check dates 
- VA Verification Request

**Comment by C-Love** [comment]
Additional notes in LAN in the Project folder.

**Comment by C-Love** [comment]
This is working with new layout. No errors reported.
