### ISSUE TITLE
NOTES - INTERVIEW: Update CASE:NOTE's to include application form question information

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#677]
User has requested that more information about the application form questions should be available in CASE;NOTE's to support the next eligibility worker picking up the work/assignment. Issue #560 is adjacent to this request since as we have multiple forms, this may be completely necessary. 

Creating issue until a decision is determined. May close and work-in issue #560.

**Comment by C-Love** [comment]
This is done and working
