### ISSUE TITLE
Tracking 65+ enrollees in METS by MHC Team - other data source

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#684]
This is likely more of a discovery project than a script solution. The need here is to find enrollees who are 65 and older and still enrolled through METS. 

Currently:
1. METS team/mgmt gets a list from somewhere
2. MHC workers ALSO come across these cases and save them to an Excel spreadsheet to send to the METS team for handling. 

In the discovery that has been done by previous MHC supervisor the lists do not duplicate, which is confusing because it seems that a background data source should be able to find these. 

The original ask on this was to create a script that would allow for the tracking of these cases as MHC workers discovered them. While this is possible, it seems there might be a more efficient way to resolve this. 

Possible ask to Mark or Mary D.

(Additional information may be in an email Casey has from 7/20/21)

**Comment by IlseFerris** [comment]
This is out of scope of our work. Closing issue as won't fix.
