### ISSUE TITLE
Create Claim Referral Tracking Function and add to needed scripts

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#687]
We need to document every time we evaluate income if there is a possible overpayment or supplement on a case. The scripts that evaluate income should have a required field where workers need to identify if there is an overpayment or supplement or not. This would then call the Claim Referral Tracking functionality. 

Need discovery on which scripts need this functionality.

**Comment by IlseFerris** [comment]
I tagged me since I ended up working on this one with you @MiKaylaH22

**Comment by IlseFerris** [comment]
Closing issue. Will be opening another issue to discover claim referral tracking process to meet both state and federal regulations. How can this be incorporated into ES workflow?
