### ISSUE TITLE
SNAP Work Rules function and add to Interview

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#689]
In order to improve communication with SNAP participants subject to a work requirement, the E&T final rule (at 7 CFR 273.7(c)(1)(i) and (ii)) instituted a new requirement to provide a consolidated work notice and oral explanation to all households where at least one member is subject to a work requirement describing the pertinent work requirements. For the purposes of this notice the work requirements are the general work rules and the time‐limited work rules for Able‐bodied Adults Without Dependents (ABAWDs).

### What Does This Mean
Effective 01/01/2021 at application, renewal*, and when a resident's FSET status changes from an exempt status to a non-exempt status (26% residents) **a written and verbal notice** must be provided regarding work provisions and time-limited SNAP rules**.

If residents do not comply with work rules, then good cause will need to be determined and documented. If good cause doesn't exist, then the resident and/or their unit members can be sanctioned. 

In addition to integrating a verbal 'script' into workers processes, there is also a need to document a 'good faith' effort when attempting to contact residents to meet the verbal notice requirements. 

*Not required at renewals as long as the SNAP renewal interview is waived. Currently waived through 03/31/2022.
**Time Limited information does not need to be provided while an ABAWD waiver is in effect. Current ABAWD waiver through 06/30/2022. 

### Combined Manual 
- [CM0028.07 GENERAL WORK RULES FOR SNAP](https://www.dhs.state.mn.us/main/idcplg?IdcService=GET_DYNAMIC_CONVERSION&RevisionSelectionMethod=LatestReleased&dDocName=CM_002807) is a new section about general work rules for SNAP. 
- [CM0028.09 ES OVERVIEW/SNAP E&T ORIENTATION ](https://www.dhs.state.mn.us/main/idcplg?IdcService=GET_DYNAMIC_CONVERSION&RevisionSelectionMethod=LatestReleased&dDocName=CM_002809)
- [CM0028.18.03 SUITABLE/UNSUITABLE WORK in SNAP](https://www.dhs.state.mn.us/main/idcplg?IdcService=GET_DYNAMIC_CONVERSION&RevisionSelectionMethod=LatestReleased&dDocName=CM_00281803)
- [CM0028.21 GOOD CAUSE NON-COMPLIANCE-SNAP/MSA/GA/GRH](https://www.dhs.state.mn.us/main/idcplg?IdcService=GET_DYNAMIC_CONVERSION&RevisionSelectionMethod=LatestReleased&dDocName=cm_002821#)
- [CM0028.30.06 TYPE/LENGTH OF SNAP E&T SANCTIONS](https://www.dhs.state.mn.us/main/idcplg?IdcService=GET_DYNAMIC_CONVERSION&RevisionSelectionMethod=LatestReleased&dDocName=cm_00283006#)
- [CM0028.30.09 REFUSING OR TERMINATING EMPLOYMENT](https://www.dhs.state.mn.us/main/idcplg?IdcService=GET_DYNAMIC_CONVERSION&RevisionSelectionMethod=LatestReleased&dDocName=cm_00283009#)
- [CM0011.24 - ABLE-BODED ADULTS WITHOUT DEPENDENTS ABLE-BODIED ADULTS WITHOUT DEPENDENTS](https://www.dhs.state.mn.us/main/idcplg?IdcService=GET_DYNAMIC_CONVERSION&RevisionSelectionMethod=LatestReleased&dDocName=CM_001124)

### Code of Federal Regulations
- [CFR 273.7 Work Provisions ](https://www.ecfr.gov/current/title-7/subtitle-B/chapter-II/subchapter-C/part-273/subpart-C/section-273.7)
- [CFR 273.24 Time Limit for Able-Bodied Adults](https://www.ecfr.gov/current/title-7/subtitle-B/chapter-II/subchapter-C/part-273/subpart-G/section-273.24)

The objective of this issue will be to integrate support for SNAP Work Rules into our current scripts and workflows, and create new scripts if necessary. Initial ideas include:
- Creating SPEC/MEMO for each person to meet written work rules and/or time limited rules
- Talking points/verbal 'script' into ACTIONS - INTERVIEW script
- Case Note/talking points support in Client Contact re: Good Cause and Good Faith effort to meet verbal requirements. 
- Script to support sanctions: both imposing and lifting sanctions (see former FSET Sanction script)

**Comment by C-Love** [comment]
This is documented in SIR and the CM. JA suggests we do not update HSR Manual with further details and just use the DHS references.

**Comment by IlseFerris** [comment]
#123 Tagging elig summary as this work will be incorporated into that work.

**Comment by C-Love** [comment]
There is a lot here that we are not going to handle.

Here are the steps we are going to take:
1. Create a function to review the information required by this policy in a dialog with an indicator that it was finish and for who. 
2. Call this function in the NOTES - Interview script and create a line in the CASE/NOTE about this being completed
3. Add this to Client Contact as it is updated (review issue once steps 1 & 2 are done to see if this needs it's own issue or can be added to existing client contact issue)
