### ISSUE TITLE
Replace APPPLYMN applications with ONLINE applications in script

### ISSUE THREAD

**Issue by MiKaylaH22** [Hennepin-County/MAXIS-scripts#697]
ApplyMN will no longer be available after January 31, 2022. New applications are no longer accepted on ApplyMN. 

Now through January 31, ApplyMN will only be available for people with partial or incomplete applications. On February 1, any partial or incomplete ApplyMN applications will no longer be available. If you go to the ApplyMN page (on or after this date) you will be redirected to MNbenefits. 

Because we have a delay in APPLs being processed this will not sundown until 02/14/22 

- [x] utilities/lost-applymn.vbs - this one needs to be able to look back retroactive
- [x] misc/complete-task.vbs
- [x] misc/tasks-dash.vbs
- [x] notices/eligibility-notifier.vbs
- [x] notes/application-received.vbs
- [x] notes/application-check.vbs
- [x] retired-scripts/waived-er-interview-screening.vbs
- [x] actions/full-interview.vbs

**Comment by MiKaylaH22** [comment]
Ilse may take this one

**Comment by IlseFerris** [comment]
No issues or updates reported/requested. Closing issue.
