### ISSUE TITLE
NOTES - SHELTER-SHELTER INTERVIEW - remove self-pay

### ISSUE THREAD

**Issue by MiKaylaH22** [Hennepin-County/MAXIS-scripts#698]
- [ ] Elimination of Self-Pay: Effective January 1st, 2022, families experiencing homelessness entering Hennepin County contracted Shelters will no longer be required to contribute towards shelter cost, also known as Self-Pay.

Our goal is to have a system that keeps the need for shelter rare, brief, and non-recurring. By eliminating self-pay, this will put income from employment, public benefits, and other income sources into the hands of the families, which will empower them to use the funds how they see fit. For example, they can use the funds for necessities, such as car payment, cell phones, public storage, car insurance etc.
• Effective January 1, 2022, families will no longer be required to contribute towards shelter cost.
• Families will only need to pay for shelter through December 31st night (see example under FAQs).
• Shelter team will work with Hennepin County accounting department to remove the release of January’s MFIP benefits that are captured for shelter.
• Shelter providers will no longer be required to collect self-pay payments from families after December 31st.

This will change the verbiage in the dialog as well as the script.  Instead of "do not release funds",  because fund now can be released to EBT card while in shelter.  No more self pay. also the title of the dialog has a spelling error. 

- [ ] REMOVE :Amt issued to EBT Line and replace with PN $70 PER HH member

- [ ] REMOVE: 100% of cash benefits -[REPLACE WITH remaining balance to HCEA shelter Account #52871]()

- [ ] REMOVE: 1st two asterisks at  the bottom

**Comment by IlseFerris** [comment]
@MiKaylaH22 is meeting with Shelter Team Leadership tomorrow to review changes needed to Shelter script set based on self-pay changes in policy.

**Comment by IlseFerris** [comment]
Closing issue, will be addressed in #721
