### ISSUE TITLE
DEU - BULK MATCH CLEARED - bring the script out of retirement 

### ISSUE THREAD

**Issue by MiKaylaH22** [Hennepin-County/MAXIS-scripts#700]
This was initially established as a QTR 1 pivot  due to changes in circumstance it is no longer identified as a PIVOT but a long term assistant to the HSS's process/procedure. This script will reduce the amount of copy and paste that is manually done by the HSS of the team. We will limit the use to only the HSS.

**Comment by IlseFerris** [comment]
Part 1 of issue - release original version for DEU. This will come out today. 
Part 2 of issue - update script with planned enhancements (@MiKaylaH22 will list these in a comment), which includes restricting the usage to MH only.

**Comment by MiKaylaH22** [comment]
No bugs reported
