### ISSUE TITLE
ACTIONS - Earned Income Budgeting - combine paychecks from the same day

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#711]
When multiple checks from the same day and same employer are received the script does not correctly calculate or update in the panel. 

Enhancement plan:
 - Encourage workers to enter checks separately in the EIB dialog.
 - Combine check amounts from the same day when calculating and entering information into MAXIS JOBS panels
 - Keep checks separated in the CASE NOTE
 - Add a single line to CASE NOTE of the combination in JOBS if that happens. 

This needs additional discovery on HOW to get this done.

**Comment by C-Love** [comment]
@IlseFerris  - I realized after our discussion that I would like to add some verbiage on the paycheck entry dialog to combine checks when entering for now to prevent errors. Do you think that is a value added stop gap measurement for this issue?

**Comment by IlseFerris** [comment]
@C-Love go for launch on this.

**Comment by C-Love** [comment]
No errors reported. Closing.
