### ISSUE TITLE
Function - Get Program and Case Status - how does it read when 'APP CLOSE' is the CURR status

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#716]
In using the function 'determine_program_and_case_status_from_CASE_CURR' there are programs reading as 'not active' when the status listed on CASE CURR for that program is 'APP CLOSE'. Need to determine what we would like to see for this status and ensure the function runs as expected.

Scripts to Update:

- [x] ACTIONS - Job Change Reported
- [x] ADMIN - AVS Report
- [x] ADMIN - DAIL 12 Month Contact
- [x] ADMIN - Expedited Review
- [x] ADMIN - MONT Report
- [x] ADMIN - On Demand Notes
- [x] ADMIN - Review Report
- [x] ADMIN - UNEA Updater
- [x] BULK - Find MAEPD MEDI CEI
- [x] NAV - Postponed Actions Tracking
- [x] NOTES - Application Received
- [x] NOTES - Returned Mail Received
- [x] NOTICES - PA Verif Request

Each script needs to have a new parameter added 'case_status' and to be assessed to determine if the program string should be 'ACTIVE' for that script in the case of 'APP OPEN' or 'APP CLOSE'.

**Comment by C-Love** [comment]
Upon review of the code, currently the string output for each program status is acutare and 'APP CLOSE' and 'APP OPEN' listed programs appear as 'ACTIVE'.

We are going to update the function to output the actual string from CASE CURR. 

We then need to evaluate each script that calls that function to determine if the handling should be updated to act differently for 'APP CLOSE' and 'APP OPEN' cases or if the functionality should operated like and 'ACTIVE' status. 

Will create a list of scripts that call this functionality.

**Comment by C-Love** [comment]
Add an emer_status parameter and EMER boolean

**Comment by C-Love** [comment]
@IlseFerris and @MiKaylaH22 - any thoughts on timing for this? We have another issue in the FuncLib so I want to be careful with timing.

**Comment by C-Love** [comment]
Question:
ADMIN - 12 Month Contact - do we only care if SNAP is actually listed as ACTIVE or does APP OPEN or APP CLOSE work?

**Comment by IlseFerris** [comment]
I'm going with just ACTIVE. APP OPEN assumes they haven't been open for 12 months necessitating a 12 month contact, and if it's APP CLOSE then we don't need to make the contact. Agree @C-Love?

**Comment by C-Love** [comment]
I think that sounds right @IlseFerris, anything other than 'ACTIVE' indicates some kind of contact is already happening.

**Comment by C-Love** [comment]
Added two new parameters to this function - a string of the list of pending programs and a string of the list of active programs.

**Comment by C-Love** [comment]
Test Scripts and Retired Scripts not evaluated

**Comment by C-Love** [comment]
No issues reported - work is done.
