### ISSUE TITLE
Create a specific functionality/script to document attempted contacts that are NOT Interviews

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#719]
There are many issues in which we need to attempt to contact the resident for clarification:

- Income on SNAP
- Incomplete HRF
- Verification searches
- others

Sometimes these require follow up with a conversation and sometimes failing this connection requires sending a verification request for completion or information. 

We need a good and consistent way to document this.

**Comment by C-Love** [comment]
This needs to start with a conversation on expectations and written direction. I will be setting up a meeting to start this conversation.

**Comment by IlseFerris** [comment]
DaNM: Should we create this separately or in connection with updates to Verifications Needed?

**Comment by C-Love** [comment]
Let's start by making this a standalone script initially, it can be built with the ability to become a function at some point, but initial roll out, process development, and testing will be easier as a stand alone script.

**Comment by C-Love** [comment]
Idea for Initial functionality - search CASE/NOTE for Verifs Requested and find a way to incorporate that into the script experience.

**Comment by C-Love** [comment]
Closing this issue as we have completed this as a part of SNAP Waived Interview and have issues #1784, #1785, #1786 to handle for this in other current forms.
