### ISSUE TITLE
UTILITIES - COPY PANELS TO WORD: Enhance to include the PIC

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#735]
Request from Ann S. (appeals) to add PIC information to COPY PANELS TO WORD script functionality. This would include the PIC for all income based panels for SNAP and GRH. 

Initial idea on how to complete this request: Add question to each income based panel to see if user needs the PIC, and for which program(s).

**Comment by C-Love** [comment]
No errors reported.
