### ISSUE TITLE
INTERVIEW Script Clean Up Issue

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#739]
A few clean ups have been identified through the script QC process and/or reported by our users. The clean up will include the following tasks (test case #309879 used to review):
- [x] Out of county information is in the case notes, but not in the worker interview form notes
- [x] Q18's INTERVIEW NOTES information appears twice in case note
- [x] Disability Review Information asks if the worker has confirmed the Domestic Violence Information. Change to Disability.
- [x] "Interviewee Information" in the worker interview form notes and in case note appears as "N/A" when ran test case in training region. Find source of where this information comes from. - NO CHANGE - seems correct
- [x]  Worker Interview Form notes: CAF 1 Expedited Questions section does not output utility information. 
- [x] Spelling error in dialog, case note and  worker interview form notes "AREP AUTHORIZATION: AREP authorized verball"
- [x] Make sure 'living_situation' cannot be 'Select'
- [x] Don't go to CM + 2

**Comment by C-Love** [comment]
Interviewee Information is from the EditBox "If interview is NOT with a Household Adult, explain relationship and add any details:" on the first page of the interview dialog. This would be worker entered.

**Comment by C-Love** [comment]
New reported bug - IF the script thinks that we are working on a REVW for CM + 2 it sets the footer month to CM +2 - which is not a place we can go. 

Additional question - WHEN processing for REVW - what should we have the footer month set to? The REVW month? What if we are working on CM + 2?

**Comment by C-Love** [comment]
These are done.
