### ISSUE TITLE
NOTES - APPLICATION RECEIVED: PRIV handling in SPEC/MEMO issue reported

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#767]
Still waiting for more information from the CA team, but here's what the script is supposed to do, but HA is reporting there are issues:

'SENDING a SPEC/MEMO - this happens AFTER the transfer so that the correct team information is on the notice.
'there should not be an issue with PRIV cases because going directly here we shouldn't lose the 'connection/access'

**Comment by C-Love** [comment]
Documentation for this is created and in SharePoint - https://hennepin.sharepoint.com/:w:/r/teams/hs-economic-supports-hub/BlueZone_Script_Instructions/General%20and%20Organizational%20Documents/Application%20Notice%20Verbiage/Script%20Automated%20Appointment%20Notices%20-%20PRIV%20Case%20Handling.docx?d=we54f79b097514fd9bfaa5c6d789b759d&csf=1&web=1&e=AjwsEo 

No Code work to be completed. Confirmed with HA in CA that this is clear and accurate. 

Work completed.
