### ISSUE TITLE
Bug on ADMIN - 12 Month Contact - reading the wrong Case Number

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#789]
The script failed on LH this morning. The script read another DAIL instead of the case number.

We will need to resolve the report from today and fix the script for next month.

**Comment by IlseFerris** [comment]
There was an additional issue with the memo success string. At some point it changed, and the script was outputting a manual update status even though the memo was sent.

**Comment by IlseFerris** [comment]
Closing issue. I ran for 06/22 without issue.
