### ISSUE TITLE
Update 200% FPG NOTES - EMERGENCY

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#792]
Changes effective 04/01/22 from [CM0016.18.01](https://www.dhs.state.mn.us/main/idcplg?IdcService=GET_DYNAMIC_CONVERSION&RevisionSelectionMethod=LatestReleased&dDocName=CM_00161801
)

**Comment by C-Love** [comment]
Code pulled in and added to the Desert Island.

**Comment by IlseFerris** [comment]
No issues reported. Closing issue.
