### ISSUE TITLE
ACTIONS - MA EPD EI FIATer - Add support for budget periods that are not entirely MA EPD

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#798]
Currently the ACTIONS - MA EPD EI FIATer can only FIAT if the entire budget is set up for every month to be EPD. 

Request has come in from KW to enhance this functionality to support FIAT if only a part of the 6 month budget is EPD. This is not currently a large scope for number of cases but was prior to COVID Waivers and will likely be a large issue when normal HC processing returns.

**Comment by C-Love** [comment]
Moving to Q3 to align with HC Renewals resuming.

**Comment by C-Love** [comment]
It's a RACE - who can do this first?!

**Comment by IlseFerris** [comment]
I removed me from assignees. @C-Love you did all the work.

**Comment by C-Love** [comment]
Work is done!
