### ISSUE TITLE
DAIL Scrubber - New Hire - if there are multiple DAILs from different months, we navigate to the wrong month sometimes

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#808]
Because of how we navigate within the DAIL and particularly moving around DAILs to the 'T'op - then we leave the dail, when we come back to the dail the wrong dail may be on top. This is due to how MAXIS navigates, If you use 'S' from the DAIL to go into STAT, we will also go STAT in the month the DAIL is from. 

Example:
2 DAILs, the first is from 02/22 and the second is the New Hire from 04/22. As the script moves, eventually we end up with a 'S' on the first one and navigate into 02/22 instead of 04/22 and we enter information into the wrong month. DAILs are ordered by date and so old dails are on top. 

There is some functionality around this in CSES Scrubber. 

We need to make sure we are acting on the RIGHT DAIL message if there is more than one on the case EVERY TIME we move from the DAIL using direct DAIL naviagation.

**Comment by IlseFerris** [comment]
@MiKaylaH22 do you want me to take this one since I've been working so much in the HIRE DAIL's?

**Comment by IlseFerris** [comment]
Closing issue. Will incorporate into issue #514
