### ISSUE TITLE
FuncLib - access_addr_panel has a spelling error causing autopopulates to not work

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#817]
In the function, the word roommate is spelled roomate. 

This is small potatoes EXCEPT that it prevents the autofil on the living situation to populate correctly if 01 is the reason.

The variable is '01 - Own home, lease or roomate' 
The droplist options is '01 - Own home, lease or roommate'

So then workers ALWAYS have to select if 01 is already filled in. 

This is a quick change - but it is in the functions library. @IlseFerris - let me know if we want to move this to critical.

**Comment by IlseFerris** [comment]
Yes @C-Love, let's escalate this to critical. This has been reported a few times now, and is affecting our end user's experience.

**Comment by C-Love** [comment]
This is done.
