### ISSUE TITLE
ACTIONS - ABAWD Screening Tool - Review functionality and update

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#824]
Review questions and ignore mutually exclusive exemptions

We need to review the questions in the ABAWD Screening Tool.

We need to have the script review the options selected and make sure we don't have errors.

Example, we should not select over 60 and age 16-17 for the same person.
Also, we should review what information we can pull from MAXIS to prevent incorrect options being selected. 

Need a full review of the questions here

**Comment by IlseFerris** [comment]
Closing as a won't fix. This script will be retired issue #1110.
