### ISSUE TITLE
Update FuncLib - navigate_to_MAXIS_screen - have the function read if we are already ON the requested screen

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#829]
To prevent unnecessary moving, update this function to read if we are on the screen that has been entered. 

For example:
If requested to go to CASE/CURR, before any other navigation happens, look on the current screen to see what panel we are on and if already in the right place - don't even move. 

Thoughts here is that we only do the NON-PRIV-CHECK version since the priv check one should always move. What does everyone else think? @IlseFerris & @MiKaylaH22

**Comment by C-Love** [comment]
@IlseFerris the function 'navigate_to_MAXIS_screen' does not check for if we are in the correct footer month. So If we are in STAT already and we want to go to 'STAT', 'MEMB' - it just goes to MEMB without confirming the footer month. It DOES confirm the MAXIS_case_number. Do we want to include that in this update OR should we look at a new issue for that?

**Comment by IlseFerris** [comment]
@C-Love how much time/evaluation would you need to add it to this issue?

**Comment by C-Love** [comment]
I think it would be minimal. I would keep the restriction to STAT and ELIG only. It's mostly a matter of ironing out the logic.

**Comment by IlseFerris** [comment]
If it's minimal, then go ahead and include it in this issue. Thank you @C-Love!

**Comment by C-Love** [comment]
This seems to be working correctly.
