### ISSUE TITLE
ACTIONS - NDNH & SDNH New HIRE review process and align

### ISSUE THREAD

**Issue by MiKaylaH22** [Hennepin-County/MAXIS-scripts#84]
Look at Streamlining the New Hire DAIL scrubber   process.      	• Ensuring JOBS panels get added.      More direction possibly for INFC portion - 2020 project
--MiKayla Handley

could   the jobs panel carry over to following month so we do not have to create a   panel in next month?
-Autumn O'Brien

**Comment by MiKaylaH22** [comment]
Waiting for others to build communication and update HSR manual
CS REPORTED: NEW EMPLOYER FOR CAREGIVER REF NBR:__
currently says to Delete. CSD staff will notify HSR Team of changes using the status update form.

**Comment by IlseFerris** [comment]
Sent email to DAIL Decimator project sponsor re: CS Reported DAIL message becoming an actionable DAIL.

**Comment by MiKaylaH22** [comment]
~~This email is generated from completion of the 'Report to the BZST' Script.~~ 
Case Number relevant/referenced: 2365681 
Script to enhance: DAIL Scrubber 
General Enhancement Info: Add an Automation 
Details about Enhacement Needed: When I was processing this new hire I went to inquiry to calculate the amount saved but never went back to production before clicking ok so it casenoted but did not update infc to clear the HIRE Dail
Additional Notes: not sure if anything can be done for this or not just an idea if you are able to for those like me who check inquiry sometimes to get details for casenotes
--- 
Signed, 
Amy Kelvie

**Comment by MiKaylaH22** [comment]
Look at the earned income script
 
From: Autumn J O'Brien <Autumn.OBrien@hennepin.us> 
Sent: Thursday, November 7, 2019 11:49 AM
To: HSPH.EWS.BlueZoneScripts <HSPH.EWS.BlueZoneScripts@hennepin.us>
Subject: Script Error -- DAIL - NEW HIRE NDNH.vbs (Automated Report)
 
Error occurred on 11/7/2019 at 11:48:46 AM 
Error type - ENHANCEMENT - something could be done better 
Script name - DAIL - NEW HIRE NDNH.vbs was run on Case #1328988 with a runtime of 16.32031 seconds. 
Information: could the jobs panel carry over to following month so we do not have to create a panel in next month? 
Closing message: Success! MAXIS updated for new HIRE message, a case note made, and a TIKL has been sent for 10 days from now. An Employment Verification and Verif Req Form B should now be sent. The job is at GOLDEN EMPLOYMENT GR.
Sent by: A. O'Brien North

**Comment by IlseFerris** [comment]
Reviewed CSES message again as request for worker for support was rec'd in team email. Instruction added for CSES message in HSR Manual: 

CS REPORTED: NEW EMPLOYER FOR CAREGIVER REF NBR:__
Action needed:  check JOBS, STWK, etc. to  see if he job has been reported/acted on. If no, CSD staff will notify HSR Team of changes using the status update form.

Still would need updated instructions before adding DAIL scrubber support for this message.

**Comment by IlseFerris** [comment]
Changed to long game as there are rumored process changes coming in the near future.

**Comment by C-Love** [comment]
Closing - This will be handled in #514

**Comment by IlseFerris** [comment]
Case note only if case is inactive.
