### ISSUE TITLE
SHELTER - all scripts review for consolidation and further automation

### ISSUE THREAD

**Issue by MiKaylaH22** [Hennepin-County/MAXIS-scripts#875]
Script Name
--
‎shelter‎/shelter-2-pm-return.vbs
‎‎shelter‎/shelter-311.vbs
‎‎shelter‎/shelter-acf-request-pend.vbs
shelter/shelter-acf-used.vbs
‎‎shelter‎/shelter-bus-ticket-issued.vbs
‎‎shelter‎/shelter-ces-screening-appt.vbs
‎‎shelter‎/shelter-change-reported.vbs
shelter/shelter-client-sheltered-by-win-a.vbs
‎shelter‎/shelter-diversion-program-referral.vbs
‎shelter‎/shelter-diversion-program-referral-results.vbs
shelter/shelter-ea-approved.vbs
‎‎shelter‎/shelter-ea-extension.vbs
‎‎shelter‎/shelter-homelessness-verified.vbs
‎shelter/shelter-main-menu.vbs
‎‎shelter‎/shelter-mandatory-vendor-approved.vbs
‎‎shelter‎/shelter-mandatory-vendor-memo.vbs
‎‎shelter‎/shelter-nspow-checked.vbs
‎shelter/shelter-partner-calls.vbs
‎‎shelter/shelter-permanent-housing-found.vbs
‎‎shelter‎/shelter-personal-needs.vbs
shelter/shelter-p-note.vbs
shelter/shelter-reimb-shelter-acct.vbs
shelter/shelter-revoucher.vbs
shelter/shelter-shelter-alternative.vbs
‎shelter/shelter-shelter-interview.vbs
‎‎shelter‎/shelter-sheriff-foreclosure.vbs
‎shelter/shelter-special-ea.vbs
‎‎shelter‎/shelter-utility-information.vbs
‎‎shelter‎/shelter-voucher-extended.vbs

**Comment by MeganGeissler** [comment]
Status: Evaluated usage data to identify obsolete scripts and drafted a few dashboard ideas- Megan
Eligibility Support\Restricted\QI - Quality Improvement\BZ scripts project\Projects\Shelter\Shelter Script Summary
Next Step: Meet with Casey & Mark

**Comment by MeganGeissler** [comment]
Shelter team is looking to move away from MAXIS. Until more clarity is provided we will not pursue this bigger overhaul. Instead, we will make a few minor fixes: #1729 and #1730
