### ISSUE TITLE
DEU-PARIS MATCH CLEARED - not clearing

### ISSUE THREAD

**Issue by MiKaylaH22** [Hennepin-County/MAXIS-scripts#880]
Reported:
DEU -  there is a bug in DAIL navigation INFC/INTM for gathering the member #SSN if using the INFC portion of the script. 
DHS has posted an announcement in SIR - DAIL will not clear, despite the match being resolved. 
Recommend: 
Change code to use the same code to gather this information and then go into If...statements for the specific processes ([See issue #814 ](https://github.com/Hennepin-County/MAXIS-scripts/issues/814)).

**Comment by IlseFerris** [comment]
User reported that script is working 'fine'. Closing issue.
