### ISSUE TITLE
NOTES - App Recvd - add info to Email for Request to APPL process

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#887]
Conversation with HA. Need to alert workers in a canned messaging format for the cancelling of the Notice.

This will be a generic statement that will be added to the email verbiage created by the script. This email is created when a 'Request for APPL' is indicated as the source of the APPLing. The statement will tell workers that a MEMO has been created (should be tied to the boolean for creating the MEMO) and if the worker has completed the interview, they should cancel the notice and update STAT with the interview information. Case Assignment is not tasked with cancelling or preventing this notice from being generated. 

While this will not resolve the problems it will add a line of communication to HSRs that CA is not responsible for handling follow up from their interview. 

This is one line of generic verbiage to the EMAIL functionality that already exists.

**Comment by MiKaylaH22** [comment]
None reports
