### ISSUE TITLE
NOTES - INTERVIEW: Add EA/EGA Supports/Questions

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#892]
We are having some issues with HSR's attempting to conduct an interview that does not incorporate all programs. To help reduce this interview questions specific to EMER programs will be added. There may also be some workflow/communication steps. 

 [New EGA Phone Line](https://hennepin.sharepoint.com/teams/hs-economic-supports-hub/SitePages/New-EGA-(Emergency-General-Assistance)-Phone-Line.aspx?xsdata=MDV8MDF8fDk4NmNmZjZhMGY3MzRkMzlkMzY0MDhkYTU5ZDZkN2JlfDhhZWZkZjlmODc4MDQ2YmY4ZmI3NGM5MjQ2NTNhOGJlfDB8MHw2Mzc5MjEwNzY1MDM4MjczMDB8R29vZHxWR1ZoYlhOVFpXTjFjbWwwZVZObGNuWnBZMlY4ZXlKV0lqb2lNQzR3TGpBd01EQWlMQ0pRSWpvaVYybHVNeklpTENKQlRpSTZJazkwYUdWeUlpd2lWMVFpT2pFeGZRPT18MXxNVGs2YldWbGRHbHVaMTlaYWswd1dYcG9hazU2U1hSWlZHc3pUWGt3TUZsNlFtaE1WMFV6VFRKTmRFOUVUbWxhUkVwc1drZFJlbGxVWTNsQWRHaHlaV0ZrTG5ZeXx8&sdata=UWlaTzNveDFDem5EemthMFA1cGZJY2lJVkFXbHhBcThlU1Z1OStYUUFoST0%3D&ovuser=8aefdf9f-8780-46bf-8fb7-4c924653a8be%2CCasey.Love%40hennepin.us&OR=Teams-HL&CT=1656510862740&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiIyNy8yMjA2MDYxNDgwNSIsIkhhc0ZlZGVyYXRlZFVzZXIiOmZhbHNlfQ%3D%3D)

**Comment by C-Love** [comment]
Additional information is in the project folder for Interview in One Drive.
