### ISSUE TITLE
NOTES - INTERVIEW: Add instruction for signing the application

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#904]
Per CM0005.12.06 the application does not need to be signed and dated unless it's a GA application. Supports for instruction on signing the application if app is GA apparent will be added. 

This change will need to be coordinated  with Knowledge Coordinator prior to update.

**Comment by C-Love** [comment]
DHS has confirmed that this signature requirement should likely be changed. JF has been asked if she would support HC specific action to communicate no signature needed. We will update the information in the script based on this.

If we communicate in the script that only GA signature is needed we will add clear instructions and a button to the CM reference on this.

**Comment by C-Love** [comment]
Though this caused mass hysteria, the functionality is sound.
