### ISSUE TITLE
HC FIATer for AMM Spendown

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#91]
TE09.13.10 How to change a spenddown type; HC - SPENDDOWNS AND OBLIGATION PERSON TESTS   TE09.13.07. R standard is the default standard for the AMM cases. Still need to find where this process is documented.

Need to clarify with Kerry/QI

**Comment by IlseFerris** [comment]
I followed up with Kerry on this issue. She believes the R standard is now automated. Unable to find POLI TEMP references to specifically support this. She concurred the issue can be closed.
