### ISSUE TITLE
NOTES - Appeals make Anticipated Date of Decision non-mandatory field

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#910]
Appeal group needs to have a field NOT mandatory. In the 'Hearing Information' selection

Report:
AS, LH, RH-S realized that we should not have the "anticipated date of decision" since we have NO idea when that may be and it can be any time from same day to several months later. Can we make that an optional box?

**Comment by IlseFerris** [comment]
No issues reported. Closing issue.
