### ISSUE TITLE
Non-Citizen Screening Evaluator

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#92]
Requested by Kerry Walsh on 03/13/17

Screening tool for non-citizen cases for eligibility and verifs needed/ imig status

**Comment by MiKaylaH22** [comment]
Will review the flow chart created by Hannah and use filter what emails need to be sent to HP IMIG

**Comment by C-Love** [comment]
This is a process to be handled by HP Immigration and handled in PowerApps.
