### ISSUE TITLE
ACTIONS - PF11, NDNH, SDNH NEW HIRE  - IEVS DAILs with MEMB 00  

### ISSUE THREAD

**Issue by MiKaylaH22** [Hennepin-County/MAXIS-scripts#923]
IEVS DAILs with MEMB 00  
​MNIT is aware that some IEVS and HIRE DAIL messages are displayed for MEMB 00. This is triggered by a status issue for a case member that is no longer part of the household.

- [x] If MEMB 00 is displayed in SDNH HIRE DAIL, workers no longer need to report the case to MAXIS Help Desk and can delete the message with no further actions.

- [x] If MEMB 00 is displayed in NDNH HIRE DAIL, workers need to resolve the match by updating Match Resolution Information on NDNH Match Details panel as following: 

  Was This Employment Known To The Agency? (Y/N) :  N  

  If Unknown: What Action Was Taken By Agency? :  NA

- [x] If MEMB 00 is displayed in IEVS DAIL, workers need to report the problem to MAXIS Help Desk using PF11 functionality.

A new POLI/TEMP section will be added soon with the instructions listed above.  

- [x] Evaluate the DAIL DECIMATOR  - non actionable DAIL removal

**Comment by IlseFerris** [comment]
Upon investigation ACTIONS - PF11 ACTIONS won't be updated, but we will give the users instructions on the message and the option to send a PF11 or not.

**Comment by IlseFerris** [comment]
No NDNH DAIL messages with MEMB 00 cases are available for the 2nd month in a row. Closing issue. Will either reopen issue or create a new one based on user reports.
