### ISSUE TITLE
DEU-NOTES-MATCH-CLEARED addressing DISQ

### ISSUE THREAD

**Issue by MiKaylaH22** [Hennepin-County/MAXIS-scripts#93]
TIME panel - DISQ  for MFIP for DEU staff. add reminder.
--

Tool needed to support DISQ panels, and addin   reminders to staff to re-evaluate TIME panel.
--Me
Review CM for Updating DISQ

**Comment by IlseFerris** [comment]
Closing as a won't fix. The DEU group has not specified issues with these scripts nor provided detailed documentation to use for evaluation of script updates.
