### ISSUE TITLE
Bug Testing and Audit ACTIONS - Job Change Reported

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#936]
Possible bugs on this or possible areas for creating more clear paths/information. Review for bugs and script flow. After audit - suggest changes for review by team and possible update. 

ToDo

- [ ] Update Instructions

Once any changes have been approved and made:
 - Create Hot Topic
 - Schedule for DEMO at Weekly Dish

**Comment by MDR22** [comment]
Received feedback that if user enters various dates in a different format (MM/DD/YYYY vs MM/DD/YY) then the dialog triggers an error that dates do not match, which can be confusing for users. Will want to address as part of audit.

**Comment by MeganGeissler** [comment]
Need to handle for stop work. Must update/add STWK and end job on JOBS panel.

**Comment by MeganGeissler** [comment]
Make this into a function so we can use this in client contact.
