### ISSUE TITLE
NOTES Script to document Unemployment Income

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#939]
Create a script to CASE NOTE details of update of UNEA for Unemployment.

This would document:
 - gross amount
 - deductions
 - which deductions are allowed or not
 - possible end date - maybe a TIKL?
 - pay date
 - compliance
 - more possible

This would autfill if UNEA was already created but maybe could also work if UNEA not completed.

**Comment by C-Love** [comment]
For some ideas of fields, create a training case with UC income on UNEA and run the CAF script. There is specific fields around how UC is budgeted and this can be a starting point for organizing the information.

**Comment by IlseFerris** [comment]
#31 Duplicative issue. Closing as a won't fix.
