### ISSUE TITLE
Full support for Significant Change

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#94]
We need for sig change:

- Evaluator
- NOTE of assessment
- MEMO of elig/inelig
- FIATer
- TIKL for possible second month
- WCOM 
- Maybe MONY/CHCK
- Update to ELIGIBILITY SUMMARY

**Comment by C-Love** [comment]
POLI TEMP TE02.13.11

**Comment by IlseFerris** [comment]
#1098 will evaluate and case note significant change. 
#394 will address the TIKL for follow up. 
@C-love will create an issue for eligibility summary to address the MEMO, WDCOM, FIATer, MONY/CHCK and elig case note.
