### ISSUE TITLE
UTILITIES-NOTICES Fleeing Felon WCOM

### ISSUE THREAD

**Issue by MiKaylaH22** [Hennepin-County/MAXIS-scripts#95]
Add   fleeing felon memo script
Kerry Walsh

Give   option to select the programs effected. Temp reference: TE02.08.187. More   than POLI TEMP. Discovery for FPI process.
--

--

**Comment by IlseFerris** [comment]
Associated with issue #377

**Comment by IlseFerris** [comment]
Duplicate of #377. Closing this issue.
