### ISSUE TITLE
QI Quality Control Review Support

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#96]
Requested by Mandora Young on 03/06/19:

Ideas for support include:
•	Creating notes and memos for QC case actions
•	Create email re: QC information/request
•	Updating DISQ panels. 

I sent an email to her today to see what kind of support she still needs.

**Comment by C-Love** [comment]
@IlseFerris is this different from issue #34 - Script Tools for QC ?

**Comment by IlseFerris** [comment]
Nope, same one. I'll close this issue. Thank you @C-Love!
