### ISSUE TITLE
DAIL -Scrubber SSN message support

### ISSUE THREAD

**Issue by MiKaylaH22** [Hennepin-County/MAXIS-scripts#97]
Add   DAIL support for following message: SSN UNMATCHED DATA EXISTS
--

Kari   Anderson

**Comment by MiKaylaH22** [comment]
Error occurred on 8/15/2020 at 6:44:27 PM 
Error type - DAIL - add support for this DAIL message. 
Script name - DAIL - DAIL SCRUBBER.vbs was run on Case #783585 with a runtime of 0.359375 seconds. 
Information: Any chance we can have a Scrubber for this DAIL? :) 
Script has issues/concerns in the following areas: 
 - There is no space to enter particular information 
Closing message: You are not on a supported DAIL message. The script will now stop. 
The message reads: 692333803  SSN UNMATCHED DATA EXISTS - 1ST ATTEMPTED MATCH 
Please send an error report if you would you like this DAIL to be supported. 
Sent by: A.Wallace HSR Sr/1:1 Connections NWR FAD

**Comment by IlseFerris** [comment]
https://hennepin.sharepoint.com/teams/hs-es-manual/SitePages/INFO.aspx

**Comment by IlseFerris** [comment]
Closing as won't fix. This will be a part of the initial launch of #627.
