### ISSUE TITLE
Discovery on preventing an excel sheet from opening as "read only"

### ISSUE THREAD

**Issue by MiKaylaH22** [Hennepin-County/MAXIS-scripts#982]
Before trying to read or write to a an excel file.

How do I turn off read only in Excel VBA?
Here's how:
Select No when prompted to open the Excel worksheet as read-only.
Choose File, followed by Save As and Browse.
Click Tools at the bottom of the Save As menu and choose General Options.
Under General, find the Read-only Recommended check box and uncheck it.
Click OK and finish saving the document.

**Comment by IlseFerris** [comment]
Closing as a won't fix. This is a user issue vs. functionality issue and is not global.
