### ISSUE TITLE
Complete List of Testers: Potential Enhancements

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#991]
- Adding OS user roles or having 
- Adjusting QI user role 
- User roles for reporting only, etc

This will be picked up as discussion at a later date.

**Comment by C-Love** [comment]
We may have additional information available about user roles in a table in the near future. Review needs once that table access has been granted.

**Comment by C-Love** [comment]
Add a 'User Group' of 'ESS' for those who need access to the Report Tasks.

Review functionality of Tester Population and update to only have BZ team on BZ.

**Comment by C-Love** [comment]
This is done - direct save to the T Drive so no commits.
